/* Copyright (c) 2019 Griefer@Work                                            *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement in the product documentation would be  *
 *    appreciated but is not required.                                        *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */

#define __CRT_HAVE__Exit 1
#define __CRT_HAVE__IO_2_1_stderr_ 1
#define __CRT_HAVE__IO_2_1_stdin_ 1
#define __CRT_HAVE__IO_2_1_stdout_ 1
#define __CRT_HAVE__IO_adjust_column 1
#define __CRT_HAVE__IO_adjust_wcolumn 1
#define __CRT_HAVE__IO_default_doallocate 1
#define __CRT_HAVE__IO_default_finish 1
#define __CRT_HAVE__IO_default_pbackfail 1
#define __CRT_HAVE__IO_default_uflow 1
#define __CRT_HAVE__IO_default_xsgetn 1
#define __CRT_HAVE__IO_default_xsputn 1
#define __CRT_HAVE__IO_do_write 1
#define __CRT_HAVE__IO_doallocbuf 1
#define __CRT_HAVE__IO_fclose 1
#define __CRT_HAVE__IO_fdopen 1
#define __CRT_HAVE__IO_feof 1
#define __CRT_HAVE__IO_ferror 1
#define __CRT_HAVE__IO_fflush 1
#define __CRT_HAVE__IO_fgetpos 1
#define __CRT_HAVE__IO_fgetpos64 1
#define __CRT_HAVE__IO_fgets 1
#define __CRT_HAVE__IO_file_attach 1
#define __CRT_HAVE__IO_file_close 1
#define __CRT_HAVE__IO_file_close_it 1
#define __CRT_HAVE__IO_file_doallocate 1
#define __CRT_HAVE__IO_file_finish 1
#define __CRT_HAVE__IO_file_fopen 1
#define __CRT_HAVE__IO_file_init 1
#define __CRT_HAVE__IO_file_jumps 1
#define __CRT_HAVE__IO_file_open 1
#define __CRT_HAVE__IO_file_overflow 1
#define __CRT_HAVE__IO_file_read 1
#define __CRT_HAVE__IO_file_seek 1
#define __CRT_HAVE__IO_file_seekoff 1
#define __CRT_HAVE__IO_file_setbuf 1
#define __CRT_HAVE__IO_file_stat 1
#define __CRT_HAVE__IO_file_sync 1
#define __CRT_HAVE__IO_file_underflow 1
#define __CRT_HAVE__IO_file_write 1
#define __CRT_HAVE__IO_file_xsputn 1
#define __CRT_HAVE__IO_flockfile 1
#define __CRT_HAVE__IO_flush_all 1
#define __CRT_HAVE__IO_flush_all_linebuffere 1
#define __CRT_HAVE__IO_fopen 1
#define __CRT_HAVE__IO_fprintf 1
#define __CRT_HAVE__IO_fputs 1
#define __CRT_HAVE__IO_fread 1
#define __CRT_HAVE__IO_free_backup_area 1
#define __CRT_HAVE__IO_free_wbackup_area 1
#define __CRT_HAVE__IO_fsetpos 1
#define __CRT_HAVE__IO_fsetpos64 1
#define __CRT_HAVE__IO_ftell 1
#define __CRT_HAVE__IO_ftrylockfile 1
#define __CRT_HAVE__IO_funlockfile 1
#define __CRT_HAVE__IO_fwrite 1
#define __CRT_HAVE__IO_getc 1
#define __CRT_HAVE__IO_getline 1
#define __CRT_HAVE__IO_getline_info 1
#define __CRT_HAVE__IO_gets 1
#define __CRT_HAVE__IO_init 1
#define __CRT_HAVE__IO_init_marker 1
#define __CRT_HAVE__IO_init_wmarker 1
#define __CRT_HAVE__IO_iter_begin 1
#define __CRT_HAVE__IO_iter_end 1
#define __CRT_HAVE__IO_iter_file 1
#define __CRT_HAVE__IO_iter_next 1
#define __CRT_HAVE__IO_least_wmarker 1
#define __CRT_HAVE__IO_link_in 1
#define __CRT_HAVE__IO_list_all 1
#define __CRT_HAVE__IO_list_lock 1
#define __CRT_HAVE__IO_list_resetlock 1
#define __CRT_HAVE__IO_list_unlock 1
#define __CRT_HAVE__IO_marker_delta 1
#define __CRT_HAVE__IO_marker_difference 1
#define __CRT_HAVE__IO_padn 1
#define __CRT_HAVE__IO_peekc_locked 1
#define __CRT_HAVE__IO_popen 1
#define __CRT_HAVE__IO_printf 1
#define __CRT_HAVE__IO_proc_close 1
#define __CRT_HAVE__IO_proc_open 1
#define __CRT_HAVE__IO_putc 1
#define __CRT_HAVE__IO_puts 1
#define __CRT_HAVE__IO_remove_marker 1
#define __CRT_HAVE__IO_seekmark 1
#define __CRT_HAVE__IO_seekoff 1
#define __CRT_HAVE__IO_seekpos 1
#define __CRT_HAVE__IO_seekwmark 1
#define __CRT_HAVE__IO_setb 1
#define __CRT_HAVE__IO_setbuffer 1
#define __CRT_HAVE__IO_setvbuf 1
#define __CRT_HAVE__IO_sgetn 1
#define __CRT_HAVE__IO_sprintf 1
#define __CRT_HAVE__IO_sputbackc 1
#define __CRT_HAVE__IO_sputbackwc 1
#define __CRT_HAVE__IO_sscanf 1
#define __CRT_HAVE__IO_stderr_ 1
#define __CRT_HAVE__IO_stdin_ 1
#define __CRT_HAVE__IO_stdin_used 1
#define __CRT_HAVE__IO_stdout_ 1
#define __CRT_HAVE__IO_str_init_readonly 1
#define __CRT_HAVE__IO_str_init_static 1
#define __CRT_HAVE__IO_str_overflow 1
#define __CRT_HAVE__IO_str_pbackfail 1
#define __CRT_HAVE__IO_str_seekoff 1
#define __CRT_HAVE__IO_str_underflow 1
#define __CRT_HAVE__IO_sungetc 1
#define __CRT_HAVE__IO_sungetwc 1
#define __CRT_HAVE__IO_switch_to_get_mode 1
#define __CRT_HAVE__IO_switch_to_main_wget_a 1
#define __CRT_HAVE__IO_switch_to_wbackup_are 1
#define __CRT_HAVE__IO_switch_to_wget_mode 1
#define __CRT_HAVE__IO_un_link 1
#define __CRT_HAVE__IO_ungetc 1
#define __CRT_HAVE__IO_unsave_markers 1
#define __CRT_HAVE__IO_unsave_wmarkers 1
#define __CRT_HAVE__IO_vfprintf 1
#define __CRT_HAVE__IO_vfscanf 1
#define __CRT_HAVE__IO_vsprintf 1
#define __CRT_HAVE__IO_wdefault_doallocate 1
#define __CRT_HAVE__IO_wdefault_finish 1
#define __CRT_HAVE__IO_wdefault_pbackfail 1
#define __CRT_HAVE__IO_wdefault_uflow 1
#define __CRT_HAVE__IO_wdefault_xsgetn 1
#define __CRT_HAVE__IO_wdefault_xsputn 1
#define __CRT_HAVE__IO_wdo_write 1
#define __CRT_HAVE__IO_wdoallocbuf 1
#define __CRT_HAVE__IO_wfile_jumps 1
#define __CRT_HAVE__IO_wfile_overflow 1
#define __CRT_HAVE__IO_wfile_seekoff 1
#define __CRT_HAVE__IO_wfile_sync 1
#define __CRT_HAVE__IO_wfile_underflow 1
#define __CRT_HAVE__IO_wfile_xsputn 1
#define __CRT_HAVE__IO_wmarker_delta 1
#define __CRT_HAVE__IO_wsetb 1
#define __CRT_HAVE__Unwind_Find_FDE 1
#define __CRT_HAVE____brk_addr 1
#define __CRT_HAVE____tls_get_addr 1
#define __CRT_HAVE___abort_msg 1
#define __CRT_HAVE___adjtimex 1
#define __CRT_HAVE___after_morecore_hook 1
#define __CRT_HAVE___argz_count 1
#define __CRT_HAVE___argz_next 1
#define __CRT_HAVE___argz_stringify 1
#define __CRT_HAVE___asprintf 1
#define __CRT_HAVE___asprintf_chk 1
#define __CRT_HAVE___assert 1
#define __CRT_HAVE___assert_fail 1
#define __CRT_HAVE___assert_perror_fail 1
#define __CRT_HAVE___backtrace 1
#define __CRT_HAVE___backtrace_symbols 1
#define __CRT_HAVE___backtrace_symbols_fd 1
#define __CRT_HAVE___bsd_getpgrp 1
#define __CRT_HAVE___bzero 1
#define __CRT_HAVE___call_tls_dtors 1
#define __CRT_HAVE___check_rhosts_file 1
#define __CRT_HAVE___chk_fail 1
#define __CRT_HAVE___clock_getcpuclockid 1
#define __CRT_HAVE___clock_getres 1
#define __CRT_HAVE___clock_gettime 1
#define __CRT_HAVE___clock_nanosleep 1
#define __CRT_HAVE___clock_settime 1
#define __CRT_HAVE___clone 1
#define __CRT_HAVE___close 1
#define __CRT_HAVE___cmpdi2 1
#define __CRT_HAVE___cmsg_nxthdr 1
#define __CRT_HAVE___confstr_chk 1
#define __CRT_HAVE___connect 1
#define __CRT_HAVE___ctype32_b 1
#define __CRT_HAVE___ctype32_tolower 1
#define __CRT_HAVE___ctype32_toupper 1
#define __CRT_HAVE___ctype_b 1
#define __CRT_HAVE___ctype_b_loc 1
#define __CRT_HAVE___ctype_get_mb_cur_max 1
#define __CRT_HAVE___ctype_init 1
#define __CRT_HAVE___ctype_tolower 1
#define __CRT_HAVE___ctype_tolower_loc 1
#define __CRT_HAVE___ctype_toupper 1
#define __CRT_HAVE___ctype_toupper_loc 1
#define __CRT_HAVE___curbrk 1
#define __CRT_HAVE___cxa_at_quick_exit 1
#define __CRT_HAVE___cxa_atexit 1
#define __CRT_HAVE___cxa_finalize 1
#define __CRT_HAVE___cxa_thread_atexit_impl 1
#define __CRT_HAVE___cyg_profile_func_enter 1
#define __CRT_HAVE___cyg_profile_func_exit 1
#define __CRT_HAVE___daylight 1
#define __CRT_HAVE___dcgettext 1
#define __CRT_HAVE___default_morecore 1
#define __CRT_HAVE___deregister_frame 1
#define __CRT_HAVE___deregister_frame_info 1
#define __CRT_HAVE___deregister_frame_info_b 1
#define __CRT_HAVE___dgettext 1
#define __CRT_HAVE___divdi3 1
#define __CRT_HAVE___dprintf_chk 1
#define __CRT_HAVE___dup2 1
#define __CRT_HAVE___duplocale 1
#define __CRT_HAVE___endmntent 1
#define __CRT_HAVE___environ 1
#define __CRT_HAVE___errno_location 1
#define __CRT_HAVE___fbufsize 1
#define __CRT_HAVE___fcntl 1
#define __CRT_HAVE___fdelt_chk 1
#define __CRT_HAVE___fdelt_warn 1
#define __CRT_HAVE___fentry__ 1
#define __CRT_HAVE___ffs 1
#define __CRT_HAVE___fgets_chk 1
#define __CRT_HAVE___fgets_unlocked_chk 1
#define __CRT_HAVE___fgetws_chk 1
#define __CRT_HAVE___fgetws_unlocked_chk 1
#define __CRT_HAVE___finite 1
#define __CRT_HAVE___finitef 1
#define __CRT_HAVE___finitel 1
#define __CRT_HAVE___fixunsdfdi 1
#define __CRT_HAVE___fixunsxfdi 1
#define __CRT_HAVE___flbf 1
#define __CRT_HAVE___floatdidf 1
#define __CRT_HAVE___fork 1
#define __CRT_HAVE___fortify_fail 1
#define __CRT_HAVE___fpending 1
#define __CRT_HAVE___fprintf_chk 1
#define __CRT_HAVE___fpu_control 1
#define __CRT_HAVE___fpurge 1
#define __CRT_HAVE___frame_state_for 1
#define __CRT_HAVE___fread_chk 1
#define __CRT_HAVE___fread_unlocked_chk 1
#define __CRT_HAVE___freadable 1
#define __CRT_HAVE___freading 1
#define __CRT_HAVE___free_hook 1
#define __CRT_HAVE___freelocale 1
#define __CRT_HAVE___fsetlocking 1
#define __CRT_HAVE___fwprintf_chk 1
#define __CRT_HAVE___fwritable 1
#define __CRT_HAVE___fwriting 1
#define __CRT_HAVE___fxstat 1
#define __CRT_HAVE___fxstat64 1
#define __CRT_HAVE___fxstatat 1
#define __CRT_HAVE___fxstatat64 1
#define __CRT_HAVE___gai_sigqueue 1
#define __CRT_HAVE___gconv_get_alias_db 1
#define __CRT_HAVE___gconv_get_cache 1
#define __CRT_HAVE___gconv_get_modules_db 1
#define __CRT_HAVE___gconv_transliterate 1
#define __CRT_HAVE___getauxval 1
#define __CRT_HAVE___getcwd_chk 1
#define __CRT_HAVE___getdelim 1
#define __CRT_HAVE___getdomainname_chk 1
#define __CRT_HAVE___getgroups_chk 1
#define __CRT_HAVE___gethostname_chk 1
#define __CRT_HAVE___getlogin_r_chk 1
#define __CRT_HAVE___getmntent_r 1
#define __CRT_HAVE___getpagesize 1
#define __CRT_HAVE___getpgid 1
#define __CRT_HAVE___getpid 1
#define __CRT_HAVE___getrlimit 1
#define __CRT_HAVE___gets_chk 1
#define __CRT_HAVE___gettimeofday 1
#define __CRT_HAVE___getwd_chk 1
#define __CRT_HAVE___gmtime_r 1
#define __CRT_HAVE___h_errno 1
#define __CRT_HAVE___h_errno_location 1
#define __CRT_HAVE___internal_endnetgrent 1
#define __CRT_HAVE___internal_getnetgrent_r 1
#define __CRT_HAVE___internal_setnetgrent 1
#define __CRT_HAVE___isalnum_l 1
#define __CRT_HAVE___isalpha_l 1
#define __CRT_HAVE___isascii_l 1
#define __CRT_HAVE___isblank_l 1
#define __CRT_HAVE___iscntrl_l 1
#define __CRT_HAVE___isctype 1
#define __CRT_HAVE___isdigit_l 1
#define __CRT_HAVE___isgraph_l 1
#define __CRT_HAVE___isinf 1
#define __CRT_HAVE___isinff 1
#define __CRT_HAVE___isinfl 1
#define __CRT_HAVE___islower_l 1
#define __CRT_HAVE___isnan 1
#define __CRT_HAVE___isnanf 1
#define __CRT_HAVE___isnanl 1
#define __CRT_HAVE___isoc99_fscanf 1
#define __CRT_HAVE___isoc99_fwscanf 1
#define __CRT_HAVE___isoc99_scanf 1
#define __CRT_HAVE___isoc99_sscanf 1
#define __CRT_HAVE___isoc99_swscanf 1
#define __CRT_HAVE___isoc99_vfscanf 1
#define __CRT_HAVE___isoc99_vfwscanf 1
#define __CRT_HAVE___isoc99_vscanf 1
#define __CRT_HAVE___isoc99_vsscanf 1
#define __CRT_HAVE___isoc99_vswscanf 1
#define __CRT_HAVE___isoc99_vwscanf 1
#define __CRT_HAVE___isoc99_wscanf 1
#define __CRT_HAVE___isprint_l 1
#define __CRT_HAVE___ispunct_l 1
#define __CRT_HAVE___isspace_l 1
#define __CRT_HAVE___isupper_l 1
#define __CRT_HAVE___iswalnum_l 1
#define __CRT_HAVE___iswalpha_l 1
#define __CRT_HAVE___iswblank_l 1
#define __CRT_HAVE___iswcntrl_l 1
#define __CRT_HAVE___iswctype 1
#define __CRT_HAVE___iswctype_l 1
#define __CRT_HAVE___iswdigit_l 1
#define __CRT_HAVE___iswgraph_l 1
#define __CRT_HAVE___iswlower_l 1
#define __CRT_HAVE___iswprint_l 1
#define __CRT_HAVE___iswpunct_l 1
#define __CRT_HAVE___iswspace_l 1
#define __CRT_HAVE___iswupper_l 1
#define __CRT_HAVE___iswxdigit_l 1
#define __CRT_HAVE___isxdigit_l 1
#define __CRT_HAVE___ivaliduser 1
#define __CRT_HAVE___key_decryptsession_pk_L 1
#define __CRT_HAVE___key_encryptsession_pk_L 1
#define __CRT_HAVE___key_gendes_LOCAL 1
#define __CRT_HAVE___libc_alloca_cutoff 1
#define __CRT_HAVE___libc_allocate_rtsig 1
#define __CRT_HAVE___libc_allocate_rtsig_pri 1
#define __CRT_HAVE___libc_calloc 1
#define __CRT_HAVE___libc_clntudp_bufcreate 1
#define __CRT_HAVE___libc_current_sigrtmax 1
#define __CRT_HAVE___libc_current_sigrtmax_p 1
#define __CRT_HAVE___libc_current_sigrtmin 1
#define __CRT_HAVE___libc_current_sigrtmin_p 1
#define __CRT_HAVE___libc_dl_error_tsd 1
#define __CRT_HAVE___libc_dlclose 1
#define __CRT_HAVE___libc_dlopen_mode 1
#define __CRT_HAVE___libc_dlsym 1
#define __CRT_HAVE___libc_enable_secure 1
#define __CRT_HAVE___libc_fatal 1
#define __CRT_HAVE___libc_fork 1
#define __CRT_HAVE___libc_free 1
#define __CRT_HAVE___libc_freeres 1
#define __CRT_HAVE___libc_ifunc_impl_list 1
#define __CRT_HAVE___libc_init_first 1
#define __CRT_HAVE___libc_longjmp 1
#define __CRT_HAVE___libc_mallinfo 1
#define __CRT_HAVE___libc_malloc 1
#define __CRT_HAVE___libc_mallopt 1
#define __CRT_HAVE___libc_memalign 1
#define __CRT_HAVE___libc_msgrcv 1
#define __CRT_HAVE___libc_msgsnd 1
#define __CRT_HAVE___libc_pread 1
#define __CRT_HAVE___libc_pthread_init 1
#define __CRT_HAVE___libc_pvalloc 1
#define __CRT_HAVE___libc_pwrite 1
#define __CRT_HAVE___libc_realloc 1
#define __CRT_HAVE___libc_rpc_getport 1
#define __CRT_HAVE___libc_sa_len 1
#define __CRT_HAVE___libc_scratch_buffer_gro 1
#define __CRT_HAVE___libc_scratch_buffer_set 1
#define __CRT_HAVE___libc_secure_getenv 1
#define __CRT_HAVE___libc_siglongjmp 1
#define __CRT_HAVE___libc_stack_end 1
#define __CRT_HAVE___libc_start_main 1
#define __CRT_HAVE___libc_system 1
#define __CRT_HAVE___libc_thread_freeres 1
#define __CRT_HAVE___libc_valloc 1
#define __CRT_HAVE___libc_vfork 1
#define __CRT_HAVE___longjmp_chk 1
#define __CRT_HAVE___lseek 1
#define __CRT_HAVE___lxstat 1
#define __CRT_HAVE___lxstat64 1
#define __CRT_HAVE___madvise 1
#define __CRT_HAVE___malloc_hook 1
#define __CRT_HAVE___malloc_initialize_hook 1
#define __CRT_HAVE___mbrlen 1
#define __CRT_HAVE___mbrtowc 1
#define __CRT_HAVE___mbsnrtowcs_chk 1
#define __CRT_HAVE___mbsrtowcs_chk 1
#define __CRT_HAVE___mbstowcs_chk 1
#define __CRT_HAVE___memalign_hook 1
#define __CRT_HAVE___memcpy_by2 1
#define __CRT_HAVE___memcpy_by4 1
#define __CRT_HAVE___memcpy_c 1
#define __CRT_HAVE___memcpy_chk 1
#define __CRT_HAVE___memcpy_g 1
#define __CRT_HAVE___memmove_chk 1
#define __CRT_HAVE___mempcpy 1
#define __CRT_HAVE___mempcpy_by2 1
#define __CRT_HAVE___mempcpy_by4 1
#define __CRT_HAVE___mempcpy_byn 1
#define __CRT_HAVE___mempcpy_chk 1
#define __CRT_HAVE___mempcpy_small 1
#define __CRT_HAVE___memset_cc 1
#define __CRT_HAVE___memset_ccn_by2 1
#define __CRT_HAVE___memset_ccn_by4 1
#define __CRT_HAVE___memset_cg 1
#define __CRT_HAVE___memset_chk 1
#define __CRT_HAVE___memset_gcn_by2 1
#define __CRT_HAVE___memset_gcn_by4 1
#define __CRT_HAVE___memset_gg 1
#define __CRT_HAVE___mktemp 1
#define __CRT_HAVE___moddi3 1
#define __CRT_HAVE___modify_ldt 1
#define __CRT_HAVE___monstartup 1
#define __CRT_HAVE___morecore 1
#define __CRT_HAVE___nanosleep 1
#define __CRT_HAVE___netlink_assert_response 1
#define __CRT_HAVE___newlocale 1
#define __CRT_HAVE___nl_langinfo_l 1
#define __CRT_HAVE___nss_configure_lookup 1
#define __CRT_HAVE___nss_database_lookup 1
#define __CRT_HAVE___nss_disable_nscd 1
#define __CRT_HAVE___nss_group_lookup 1
#define __CRT_HAVE___nss_group_lookup2 1
#define __CRT_HAVE___nss_hostname_digits_dot 1
#define __CRT_HAVE___nss_hosts_lookup 1
#define __CRT_HAVE___nss_hosts_lookup2 1
#define __CRT_HAVE___nss_lookup 1
#define __CRT_HAVE___nss_lookup_function 1
#define __CRT_HAVE___nss_next 1
#define __CRT_HAVE___nss_next2 1
#define __CRT_HAVE___nss_passwd_lookup 1
#define __CRT_HAVE___nss_passwd_lookup2 1
#define __CRT_HAVE___nss_services_lookup2 1
#define __CRT_HAVE___obstack_printf_chk 1
#define __CRT_HAVE___obstack_vprintf_chk 1
#define __CRT_HAVE___open 1
#define __CRT_HAVE___open64 1
#define __CRT_HAVE___open64_2 1
#define __CRT_HAVE___open_2 1
#define __CRT_HAVE___open_catalog 1
#define __CRT_HAVE___openat64_2 1
#define __CRT_HAVE___openat_2 1
#define __CRT_HAVE___overflow 1
#define __CRT_HAVE___pipe 1
#define __CRT_HAVE___poll 1
#define __CRT_HAVE___poll_chk 1
#define __CRT_HAVE___posix_getopt 1
#define __CRT_HAVE___ppoll_chk 1
#define __CRT_HAVE___pread64 1
#define __CRT_HAVE___pread64_chk 1
#define __CRT_HAVE___pread_chk 1
#define __CRT_HAVE___printf_chk 1
#define __CRT_HAVE___printf_fp 1
#define __CRT_HAVE___profile_frequency 1
#define __CRT_HAVE___progname 1
#define __CRT_HAVE___progname_full 1
#define __CRT_HAVE___ptsname_r_chk 1
#define __CRT_HAVE___pwrite64 1
#define __CRT_HAVE___rawmemchr 1
#define __CRT_HAVE___rcmd_errstr 1
#define __CRT_HAVE___read 1
#define __CRT_HAVE___read_chk 1
#define __CRT_HAVE___readlink_chk 1
#define __CRT_HAVE___readlinkat_chk 1
#define __CRT_HAVE___realloc_hook 1
#define __CRT_HAVE___realpath_chk 1
#define __CRT_HAVE___recv 1
#define __CRT_HAVE___recv_chk 1
#define __CRT_HAVE___recvfrom_chk 1
#define __CRT_HAVE___register_atfork 1
#define __CRT_HAVE___register_frame 1
#define __CRT_HAVE___register_frame_info 1
#define __CRT_HAVE___register_frame_info_bas 1
#define __CRT_HAVE___register_frame_info_tab 1
#define __CRT_HAVE___register_frame_table 1
#define __CRT_HAVE___res_iclose 1
#define __CRT_HAVE___res_init 1
#define __CRT_HAVE___res_maybe_init 1
#define __CRT_HAVE___res_nclose 1
#define __CRT_HAVE___res_ninit 1
#define __CRT_HAVE___res_randomid 1
#define __CRT_HAVE___res_state 1
#define __CRT_HAVE___resp 1
#define __CRT_HAVE___rpc_thread_createerr 1
#define __CRT_HAVE___rpc_thread_svc_fdset 1
#define __CRT_HAVE___rpc_thread_svc_max_poll 1
#define __CRT_HAVE___rpc_thread_svc_pollfd 1
#define __CRT_HAVE___sbrk 1
#define __CRT_HAVE___sched_cpualloc 1
#define __CRT_HAVE___sched_cpucount 1
#define __CRT_HAVE___sched_cpufree 1
#define __CRT_HAVE___sched_get_priority_max 1
#define __CRT_HAVE___sched_get_priority_min 1
#define __CRT_HAVE___sched_getparam 1
#define __CRT_HAVE___sched_getscheduler 1
#define __CRT_HAVE___sched_setscheduler 1
#define __CRT_HAVE___sched_yield 1
#define __CRT_HAVE___secure_getenv 1
#define __CRT_HAVE___select 1
#define __CRT_HAVE___send 1
#define __CRT_HAVE___sendmmsg 1
#define __CRT_HAVE___setmntent 1
#define __CRT_HAVE___setpgid 1
#define __CRT_HAVE___sigaction 1
#define __CRT_HAVE___sigaddset 1
#define __CRT_HAVE___sigdelset 1
#define __CRT_HAVE___sigismember 1
#define __CRT_HAVE___signbit 1
#define __CRT_HAVE___signbitf 1
#define __CRT_HAVE___signbitl 1
#define __CRT_HAVE___sigpause 1
#define __CRT_HAVE___sigsetjmp 1
#define __CRT_HAVE___sigsuspend 1
#define __CRT_HAVE___snprintf_chk 1
#define __CRT_HAVE___socket 1
#define __CRT_HAVE___sprintf_chk 1
#define __CRT_HAVE___stack_chk_fail 1
#define __CRT_HAVE___statfs 1
#define __CRT_HAVE___stpcpy 1
#define __CRT_HAVE___stpcpy_chk 1
#define __CRT_HAVE___stpcpy_g 1
#define __CRT_HAVE___stpcpy_small 1
#define __CRT_HAVE___stpncpy 1
#define __CRT_HAVE___stpncpy_chk 1
#define __CRT_HAVE___strcasecmp 1
#define __CRT_HAVE___strcasecmp_l 1
#define __CRT_HAVE___strcasestr 1
#define __CRT_HAVE___strcat_c 1
#define __CRT_HAVE___strcat_chk 1
#define __CRT_HAVE___strcat_g 1
#define __CRT_HAVE___strchr_c 1
#define __CRT_HAVE___strchr_g 1
#define __CRT_HAVE___strchrnul_c 1
#define __CRT_HAVE___strchrnul_g 1
#define __CRT_HAVE___strcmp_gg 1
#define __CRT_HAVE___strcoll_l 1
#define __CRT_HAVE___strcpy_chk 1
#define __CRT_HAVE___strcpy_g 1
#define __CRT_HAVE___strcpy_small 1
#define __CRT_HAVE___strcspn_c1 1
#define __CRT_HAVE___strcspn_c2 1
#define __CRT_HAVE___strcspn_c3 1
#define __CRT_HAVE___strcspn_cg 1
#define __CRT_HAVE___strcspn_g 1
#define __CRT_HAVE___strdup 1
#define __CRT_HAVE___strerror_r 1
#define __CRT_HAVE___strfmon_l 1
#define __CRT_HAVE___strftime_l 1
#define __CRT_HAVE___strlen_g 1
#define __CRT_HAVE___strncasecmp_l 1
#define __CRT_HAVE___strncat_chk 1
#define __CRT_HAVE___strncat_g 1
#define __CRT_HAVE___strncmp_g 1
#define __CRT_HAVE___strncpy_by2 1
#define __CRT_HAVE___strncpy_by4 1
#define __CRT_HAVE___strncpy_byn 1
#define __CRT_HAVE___strncpy_chk 1
#define __CRT_HAVE___strncpy_gg 1
#define __CRT_HAVE___strndup 1
#define __CRT_HAVE___strpbrk_c2 1
#define __CRT_HAVE___strpbrk_c3 1
#define __CRT_HAVE___strpbrk_cg 1
#define __CRT_HAVE___strpbrk_g 1
#define __CRT_HAVE___strrchr_c 1
#define __CRT_HAVE___strrchr_g 1
#define __CRT_HAVE___strsep_1c 1
#define __CRT_HAVE___strsep_2c 1
#define __CRT_HAVE___strsep_3c 1
#define __CRT_HAVE___strsep_g 1
#define __CRT_HAVE___strspn_c1 1
#define __CRT_HAVE___strspn_c2 1
#define __CRT_HAVE___strspn_c3 1
#define __CRT_HAVE___strspn_cg 1
#define __CRT_HAVE___strspn_g 1
#define __CRT_HAVE___strstr_cg 1
#define __CRT_HAVE___strstr_g 1
#define __CRT_HAVE___strtod_internal 1
#define __CRT_HAVE___strtod_l 1
#define __CRT_HAVE___strtod_nan 1
#define __CRT_HAVE___strtof_internal 1
#define __CRT_HAVE___strtof_l 1
#define __CRT_HAVE___strtof_nan 1
#define __CRT_HAVE___strtok_r 1
#define __CRT_HAVE___strtok_r_1c 1
#define __CRT_HAVE___strtol_internal 1
#define __CRT_HAVE___strtol_l 1
#define __CRT_HAVE___strtold_internal 1
#define __CRT_HAVE___strtold_l 1
#define __CRT_HAVE___strtold_nan 1
#define __CRT_HAVE___strtoll_internal 1
#define __CRT_HAVE___strtoll_l 1
#define __CRT_HAVE___strtoq_internal 1
#define __CRT_HAVE___strtoul_internal 1
#define __CRT_HAVE___strtoul_l 1
#define __CRT_HAVE___strtoull_internal 1
#define __CRT_HAVE___strtoull_l 1
#define __CRT_HAVE___strtouq_internal 1
#define __CRT_HAVE___strverscmp 1
#define __CRT_HAVE___strxfrm_l 1
#define __CRT_HAVE___swprintf_chk 1
#define __CRT_HAVE___sysconf 1
#define __CRT_HAVE___sysctl 1
#define __CRT_HAVE___syslog_chk 1
#define __CRT_HAVE___sysv_signal 1
#define __CRT_HAVE___tdelete 1
#define __CRT_HAVE___tfind 1
#define __CRT_HAVE___timezone 1
#define __CRT_HAVE___toascii_l 1
#define __CRT_HAVE___tolower_l 1
#define __CRT_HAVE___toupper_l 1
#define __CRT_HAVE___towctrans 1
#define __CRT_HAVE___towctrans_l 1
#define __CRT_HAVE___towlower_l 1
#define __CRT_HAVE___towupper_l 1
#define __CRT_HAVE___tsearch 1
#define __CRT_HAVE___ttyname_r_chk 1
#define __CRT_HAVE___twalk 1
#define __CRT_HAVE___tzname 1
#define __CRT_HAVE___ucmpdi2 1
#define __CRT_HAVE___udivdi3 1
#define __CRT_HAVE___uflow 1
#define __CRT_HAVE___umoddi3 1
#define __CRT_HAVE___underflow 1
#define __CRT_HAVE___uselocale 1
#define __CRT_HAVE___vasprintf_chk 1
#define __CRT_HAVE___vdprintf_chk 1
#define __CRT_HAVE___vfork 1
#define __CRT_HAVE___vfprintf_chk 1
#define __CRT_HAVE___vfscanf 1
#define __CRT_HAVE___vfwprintf_chk 1
#define __CRT_HAVE___vprintf_chk 1
#define __CRT_HAVE___vsnprintf 1
#define __CRT_HAVE___vsnprintf_chk 1
#define __CRT_HAVE___vsprintf_chk 1
#define __CRT_HAVE___vsscanf 1
#define __CRT_HAVE___vswprintf_chk 1
#define __CRT_HAVE___vsyslog_chk 1
#define __CRT_HAVE___vwprintf_chk 1
#define __CRT_HAVE___wait 1
#define __CRT_HAVE___waitpid 1
#define __CRT_HAVE___wcpcpy_chk 1
#define __CRT_HAVE___wcpncpy_chk 1
#define __CRT_HAVE___wcrtomb_chk 1
#define __CRT_HAVE___wcscasecmp_l 1
#define __CRT_HAVE___wcscat_chk 1
#define __CRT_HAVE___wcscoll_l 1
#define __CRT_HAVE___wcscpy_chk 1
#define __CRT_HAVE___wcsftime_l 1
#define __CRT_HAVE___wcsncasecmp_l 1
#define __CRT_HAVE___wcsncat_chk 1
#define __CRT_HAVE___wcsncpy_chk 1
#define __CRT_HAVE___wcsnrtombs_chk 1
#define __CRT_HAVE___wcsrtombs_chk 1
#define __CRT_HAVE___wcstod_internal 1
#define __CRT_HAVE___wcstod_l 1
#define __CRT_HAVE___wcstof_internal 1
#define __CRT_HAVE___wcstof_l 1
#define __CRT_HAVE___wcstol_internal 1
#define __CRT_HAVE___wcstol_l 1
#define __CRT_HAVE___wcstold_internal 1
#define __CRT_HAVE___wcstold_l 1
#define __CRT_HAVE___wcstoll_internal 1
#define __CRT_HAVE___wcstoll_l 1
#define __CRT_HAVE___wcstombs_chk 1
#define __CRT_HAVE___wcstoul_internal 1
#define __CRT_HAVE___wcstoul_l 1
#define __CRT_HAVE___wcstoull_internal 1
#define __CRT_HAVE___wcstoull_l 1
#define __CRT_HAVE___wcsxfrm_l 1
#define __CRT_HAVE___wctomb_chk 1
#define __CRT_HAVE___wctrans_l 1
#define __CRT_HAVE___wctype_l 1
#define __CRT_HAVE___wmemcpy_chk 1
#define __CRT_HAVE___wmemmove_chk 1
#define __CRT_HAVE___wmempcpy_chk 1
#define __CRT_HAVE___wmemset_chk 1
#define __CRT_HAVE___woverflow 1
#define __CRT_HAVE___wprintf_chk 1
#define __CRT_HAVE___write 1
#define __CRT_HAVE___wuflow 1
#define __CRT_HAVE___wunderflow 1
#define __CRT_HAVE___xmknod 1
#define __CRT_HAVE___xmknodat 1
#define __CRT_HAVE___xpg_basename 1
#define __CRT_HAVE___xpg_sigpause 1
#define __CRT_HAVE___xpg_strerror_r 1
#define __CRT_HAVE___xstat 1
#define __CRT_HAVE___xstat64 1
#define __CRT_HAVE__authenticate 1
#define __CRT_HAVE__dl_addr 1
#define __CRT_HAVE__dl_argv 1
#define __CRT_HAVE__dl_find_dso_for_object 1
#define __CRT_HAVE__dl_mcount_wrapper 1
#define __CRT_HAVE__dl_mcount_wrapper_check 1
#define __CRT_HAVE__dl_open_hook 1
#define __CRT_HAVE__dl_starting_up 1
#define __CRT_HAVE__dl_sym 1
#define __CRT_HAVE__dl_vsym 1
#define __CRT_HAVE__environ 1
#define __CRT_HAVE__exit 1
#define __CRT_HAVE__flushlbf 1
#define __CRT_HAVE__itoa_lower_digits 1
#define __CRT_HAVE__libc_intl_domainname 1
#define __CRT_HAVE__longjmp 1
#define __CRT_HAVE__mcleanup 1
#define __CRT_HAVE__mcount 1
#define __CRT_HAVE__nl_default_dirname 1
#define __CRT_HAVE__nl_domain_bindings 1
#define __CRT_HAVE__nl_msg_cat_cntr 1
#define __CRT_HAVE__nss_files_parse_grent 1
#define __CRT_HAVE__nss_files_parse_pwent 1
#define __CRT_HAVE__nss_files_parse_sgent 1
#define __CRT_HAVE__nss_files_parse_spent 1
#define __CRT_HAVE__null_auth 1
#define __CRT_HAVE__obstack 1
#define __CRT_HAVE__obstack_allocated_p 1
#define __CRT_HAVE__obstack_begin 1
#define __CRT_HAVE__obstack_begin_1 1
#define __CRT_HAVE__obstack_free 1
#define __CRT_HAVE__obstack_memory_used 1
#define __CRT_HAVE__obstack_newchunk 1
#define __CRT_HAVE__res 1
#define __CRT_HAVE__res_hconf 1
#define __CRT_HAVE__rpc_dtablesize 1
#define __CRT_HAVE__rtld_global 1
#define __CRT_HAVE__rtld_global_ro 1
#define __CRT_HAVE__seterr_reply 1
#define __CRT_HAVE__setjmp 1
#define __CRT_HAVE__sys_errlist 1
#define __CRT_HAVE__sys_nerr 1
#define __CRT_HAVE__sys_siglist 1
#define __CRT_HAVE__tolower 1
#define __CRT_HAVE__toupper 1
#define __CRT_HAVE_a64l 1
#define __CRT_HAVE_abort 1
#define __CRT_HAVE_abs 1
#define __CRT_HAVE_accept 1
#define __CRT_HAVE_accept4 1
#define __CRT_HAVE_access 1
#define __CRT_HAVE_acct 1
#define __CRT_HAVE_addmntent 1
#define __CRT_HAVE_addseverity 1
#define __CRT_HAVE_adjtime 1
#define __CRT_HAVE_adjtimex 1
#define __CRT_HAVE_advance 1
#define __CRT_HAVE_alarm 1
#define __CRT_HAVE_aligned_alloc 1
#define __CRT_HAVE_alphasort 1
#define __CRT_HAVE_alphasort64 1
#define __CRT_HAVE_argp_err_exit_status 1
#define __CRT_HAVE_argp_error 1
#define __CRT_HAVE_argp_failure 1
#define __CRT_HAVE_argp_help 1
#define __CRT_HAVE_argp_parse 1
#define __CRT_HAVE_argp_program_bug_address 1
#define __CRT_HAVE_argp_program_version 1
#define __CRT_HAVE_argp_program_version_hook 1
#define __CRT_HAVE_argp_state_help 1
#define __CRT_HAVE_argp_usage 1
#define __CRT_HAVE_argz_add 1
#define __CRT_HAVE_argz_add_sep 1
#define __CRT_HAVE_argz_append 1
#define __CRT_HAVE_argz_count 1
#define __CRT_HAVE_argz_create 1
#define __CRT_HAVE_argz_create_sep 1
#define __CRT_HAVE_argz_delete 1
#define __CRT_HAVE_argz_extract 1
#define __CRT_HAVE_argz_insert 1
#define __CRT_HAVE_argz_next 1
#define __CRT_HAVE_argz_replace 1
#define __CRT_HAVE_argz_stringify 1
#define __CRT_HAVE_asctime 1
#define __CRT_HAVE_asctime_r 1
#define __CRT_HAVE_asprintf 1
#define __CRT_HAVE_atexit 1
#define __CRT_HAVE_atof 1
#define __CRT_HAVE_atoi 1
#define __CRT_HAVE_atol 1
#define __CRT_HAVE_atoll 1
#define __CRT_HAVE_authdes_create 1
#define __CRT_HAVE_authdes_getucred 1
#define __CRT_HAVE_authdes_pk_create 1
#define __CRT_HAVE_authnone_create 1
#define __CRT_HAVE_authunix_create 1
#define __CRT_HAVE_authunix_create_default 1
#define __CRT_HAVE_backtrace 1
#define __CRT_HAVE_backtrace_symbols 1
#define __CRT_HAVE_backtrace_symbols_fd 1
#define __CRT_HAVE_basename 1
#define __CRT_HAVE_bcmp 1
#define __CRT_HAVE_bcopy 1
#define __CRT_HAVE_bdflush 1
#define __CRT_HAVE_bind 1
#define __CRT_HAVE_bind_textdomain_codeset 1
#define __CRT_HAVE_bindresvport 1
#define __CRT_HAVE_bindtextdomain 1
#define __CRT_HAVE_brk 1
#define __CRT_HAVE_bsd_signal 1
#define __CRT_HAVE_bsearch 1
#define __CRT_HAVE_btowc 1
#define __CRT_HAVE_bzero 1
#define __CRT_HAVE_c16rtomb 1
#define __CRT_HAVE_c32rtomb 1
#define __CRT_HAVE_calloc 1
#define __CRT_HAVE_callrpc 1
#define __CRT_HAVE_canonicalize_file_name 1
#define __CRT_HAVE_capget 1
#define __CRT_HAVE_capset 1
#define __CRT_HAVE_catclose 1
#define __CRT_HAVE_catgets 1
#define __CRT_HAVE_catopen 1
#define __CRT_HAVE_cbc_crypt 1
#define __CRT_HAVE_cfgetispeed 1
#define __CRT_HAVE_cfgetospeed 1
#define __CRT_HAVE_cfmakeraw 1
#define __CRT_HAVE_cfree 1
#define __CRT_HAVE_cfsetispeed 1
#define __CRT_HAVE_cfsetospeed 1
#define __CRT_HAVE_cfsetspeed 1
#define __CRT_HAVE_chdir 1
#define __CRT_HAVE_chflags 1
#define __CRT_HAVE_chmod 1
#define __CRT_HAVE_chown 1
#define __CRT_HAVE_chroot 1
#define __CRT_HAVE_clearenv 1
#define __CRT_HAVE_clearerr 1
#define __CRT_HAVE_clearerr_unlocked 1
#define __CRT_HAVE_clnt_broadcast 1
#define __CRT_HAVE_clnt_create 1
#define __CRT_HAVE_clnt_pcreateerror 1
#define __CRT_HAVE_clnt_perrno 1
#define __CRT_HAVE_clnt_perror 1
#define __CRT_HAVE_clnt_spcreateerror 1
#define __CRT_HAVE_clnt_sperrno 1
#define __CRT_HAVE_clnt_sperror 1
#define __CRT_HAVE_clntraw_create 1
#define __CRT_HAVE_clnttcp_create 1
#define __CRT_HAVE_clntudp_bufcreate 1
#define __CRT_HAVE_clntudp_create 1
#define __CRT_HAVE_clntunix_create 1
#define __CRT_HAVE_clock 1
#define __CRT_HAVE_clock_adjtime 1
#define __CRT_HAVE_clock_getcpuclockid 1
#define __CRT_HAVE_clock_getres 1
#define __CRT_HAVE_clock_gettime 1
#define __CRT_HAVE_clock_nanosleep 1
#define __CRT_HAVE_clock_settime 1
#define __CRT_HAVE_clone 1
#define __CRT_HAVE_close 1
#define __CRT_HAVE_closedir 1
#define __CRT_HAVE_closelog 1
#define __CRT_HAVE_confstr 1
#define __CRT_HAVE_connect 1
#define __CRT_HAVE_copysign 1
#define __CRT_HAVE_copysignf 1
#define __CRT_HAVE_copysignl 1
#define __CRT_HAVE_creat 1
#define __CRT_HAVE_creat64 1
#define __CRT_HAVE_create_module 1
#define __CRT_HAVE_ctermid 1
#define __CRT_HAVE_ctime 1
#define __CRT_HAVE_ctime_r 1
#define __CRT_HAVE_cuserid 1
#define __CRT_HAVE_daemon 1
#define __CRT_HAVE_daylight 1
#define __CRT_HAVE_dcgettext 1
#define __CRT_HAVE_dcngettext 1
#define __CRT_HAVE_delete_module 1
#define __CRT_HAVE_des_setparity 1
#define __CRT_HAVE_dgettext 1
#define __CRT_HAVE_difftime 1
#define __CRT_HAVE_dirfd 1
#define __CRT_HAVE_dirname 1
#define __CRT_HAVE_div 1
#define __CRT_HAVE_dl_iterate_phdr 1
#define __CRT_HAVE_dngettext 1
#define __CRT_HAVE_dprintf 1
#define __CRT_HAVE_drand48 1
#define __CRT_HAVE_drand48_r 1
#define __CRT_HAVE_dup 1
#define __CRT_HAVE_dup2 1
#define __CRT_HAVE_dup3 1
#define __CRT_HAVE_duplocale 1
#define __CRT_HAVE_dysize 1
#define __CRT_HAVE_eaccess 1
#define __CRT_HAVE_ecb_crypt 1
#define __CRT_HAVE_ecvt 1
#define __CRT_HAVE_ecvt_r 1
#define __CRT_HAVE_endaliasent 1
#define __CRT_HAVE_endfsent 1
#define __CRT_HAVE_endgrent 1
#define __CRT_HAVE_endhostent 1
#define __CRT_HAVE_endmntent 1
#define __CRT_HAVE_endnetent 1
#define __CRT_HAVE_endnetgrent 1
#define __CRT_HAVE_endprotoent 1
#define __CRT_HAVE_endpwent 1
#define __CRT_HAVE_endrpcent 1
#define __CRT_HAVE_endservent 1
#define __CRT_HAVE_endsgent 1
#define __CRT_HAVE_endspent 1
#define __CRT_HAVE_endttyent 1
#define __CRT_HAVE_endusershell 1
#define __CRT_HAVE_endutent 1
#define __CRT_HAVE_endutxent 1
#define __CRT_HAVE_environ 1
#define __CRT_HAVE_envz_add 1
#define __CRT_HAVE_envz_entry 1
#define __CRT_HAVE_envz_get 1
#define __CRT_HAVE_envz_merge 1
#define __CRT_HAVE_envz_remove 1
#define __CRT_HAVE_envz_strip 1
#define __CRT_HAVE_epoll_create 1
#define __CRT_HAVE_epoll_create1 1
#define __CRT_HAVE_epoll_ctl 1
#define __CRT_HAVE_epoll_pwait 1
#define __CRT_HAVE_epoll_wait 1
#define __CRT_HAVE_erand48 1
#define __CRT_HAVE_erand48_r 1
#define __CRT_HAVE_err 1
#define __CRT_HAVE_errno 1
#define __CRT_HAVE_error 1
#define __CRT_HAVE_error_at_line 1
#define __CRT_HAVE_error_message_count 1
#define __CRT_HAVE_error_one_per_line 1
#define __CRT_HAVE_error_print_progname 1
#define __CRT_HAVE_errx 1
#define __CRT_HAVE_ether_aton 1
#define __CRT_HAVE_ether_aton_r 1
#define __CRT_HAVE_ether_hostton 1
#define __CRT_HAVE_ether_line 1
#define __CRT_HAVE_ether_ntoa 1
#define __CRT_HAVE_ether_ntoa_r 1
#define __CRT_HAVE_ether_ntohost 1
#define __CRT_HAVE_euidaccess 1
#define __CRT_HAVE_eventfd 1
#define __CRT_HAVE_eventfd_read 1
#define __CRT_HAVE_eventfd_write 1
#define __CRT_HAVE_execl 1
#define __CRT_HAVE_execle 1
#define __CRT_HAVE_execlp 1
#define __CRT_HAVE_execv 1
#define __CRT_HAVE_execve 1
#define __CRT_HAVE_execvp 1
#define __CRT_HAVE_execvpe 1
#define __CRT_HAVE_exit 1
#define __CRT_HAVE_faccessat 1
#define __CRT_HAVE_fallocate 1
#define __CRT_HAVE_fallocate64 1
#define __CRT_HAVE_fanotify_init 1
#define __CRT_HAVE_fanotify_mark 1
#define __CRT_HAVE_fattach 1
#define __CRT_HAVE_fchdir 1
#define __CRT_HAVE_fchflags 1
#define __CRT_HAVE_fchmod 1
#define __CRT_HAVE_fchmodat 1
#define __CRT_HAVE_fchown 1
#define __CRT_HAVE_fchownat 1
#define __CRT_HAVE_fclose 1
#define __CRT_HAVE_fcloseall 1
#define __CRT_HAVE_fcntl 1
#define __CRT_HAVE_fcvt 1
#define __CRT_HAVE_fcvt_r 1
#define __CRT_HAVE_fdatasync 1
#define __CRT_HAVE_fdetach 1
#define __CRT_HAVE_fdopen 1
#define __CRT_HAVE_fdopendir 1
#define __CRT_HAVE_feof 1
#define __CRT_HAVE_feof_unlocked 1
#define __CRT_HAVE_ferror 1
#define __CRT_HAVE_ferror_unlocked 1
#define __CRT_HAVE_fexecve 1
#define __CRT_HAVE_fflush 1
#define __CRT_HAVE_fflush_unlocked 1
#define __CRT_HAVE_ffs 1
#define __CRT_HAVE_ffsl 1
#define __CRT_HAVE_ffsll 1
#define __CRT_HAVE_fgetc 1
#define __CRT_HAVE_fgetc_unlocked 1
#define __CRT_HAVE_fgetgrent 1
#define __CRT_HAVE_fgetgrent_r 1
#define __CRT_HAVE_fgetpos 1
#define __CRT_HAVE_fgetpos64 1
#define __CRT_HAVE_fgetpwent 1
#define __CRT_HAVE_fgetpwent_r 1
#define __CRT_HAVE_fgets 1
#define __CRT_HAVE_fgets_unlocked 1
#define __CRT_HAVE_fgetsgent 1
#define __CRT_HAVE_fgetsgent_r 1
#define __CRT_HAVE_fgetspent 1
#define __CRT_HAVE_fgetspent_r 1
#define __CRT_HAVE_fgetwc 1
#define __CRT_HAVE_fgetwc_unlocked 1
#define __CRT_HAVE_fgetws 1
#define __CRT_HAVE_fgetws_unlocked 1
#define __CRT_HAVE_fgetxattr 1
#define __CRT_HAVE_fileno 1
#define __CRT_HAVE_fileno_unlocked 1
#define __CRT_HAVE_finite 1
#define __CRT_HAVE_finitef 1
#define __CRT_HAVE_finitel 1
#define __CRT_HAVE_flistxattr 1
#define __CRT_HAVE_flock 1
#define __CRT_HAVE_flockfile 1
#define __CRT_HAVE_fmemopen 1
#define __CRT_HAVE_fmtmsg 1
#define __CRT_HAVE_fnmatch 1
#define __CRT_HAVE_fopen 1
#define __CRT_HAVE_fopen64 1
#define __CRT_HAVE_fopencookie 1
#define __CRT_HAVE_fork 1
#define __CRT_HAVE_fpathconf 1
#define __CRT_HAVE_fprintf 1
#define __CRT_HAVE_fputc 1
#define __CRT_HAVE_fputc_unlocked 1
#define __CRT_HAVE_fputs 1
#define __CRT_HAVE_fputs_unlocked 1
#define __CRT_HAVE_fputwc 1
#define __CRT_HAVE_fputwc_unlocked 1
#define __CRT_HAVE_fputws 1
#define __CRT_HAVE_fputws_unlocked 1
#define __CRT_HAVE_fread 1
#define __CRT_HAVE_fread_unlocked 1
#define __CRT_HAVE_free 1
#define __CRT_HAVE_freeaddrinfo 1
#define __CRT_HAVE_freeifaddrs 1
#define __CRT_HAVE_freelocale 1
#define __CRT_HAVE_fremovexattr 1
#define __CRT_HAVE_freopen 1
#define __CRT_HAVE_freopen64 1
#define __CRT_HAVE_frexp 1
#define __CRT_HAVE_frexpf 1
#define __CRT_HAVE_frexpl 1
#define __CRT_HAVE_fscanf 1
#define __CRT_HAVE_fseek 1
#define __CRT_HAVE_fseeko 1
#define __CRT_HAVE_fseeko64 1
#define __CRT_HAVE_fsetpos 1
#define __CRT_HAVE_fsetpos64 1
#define __CRT_HAVE_fsetxattr 1
#define __CRT_HAVE_fstatfs 1
#define __CRT_HAVE_fstatfs64 1
#define __CRT_HAVE_fstatvfs 1
#define __CRT_HAVE_fstatvfs64 1
#define __CRT_HAVE_fsync 1
#define __CRT_HAVE_ftell 1
#define __CRT_HAVE_ftello 1
#define __CRT_HAVE_ftello64 1
#define __CRT_HAVE_ftime 1
#define __CRT_HAVE_ftok 1
#define __CRT_HAVE_ftruncate 1
#define __CRT_HAVE_ftruncate64 1
#define __CRT_HAVE_ftrylockfile 1
#define __CRT_HAVE_fts64_children 1
#define __CRT_HAVE_fts64_close 1
#define __CRT_HAVE_fts64_open 1
#define __CRT_HAVE_fts64_read 1
#define __CRT_HAVE_fts64_set 1
#define __CRT_HAVE_fts_children 1
#define __CRT_HAVE_fts_close 1
#define __CRT_HAVE_fts_open 1
#define __CRT_HAVE_fts_read 1
#define __CRT_HAVE_fts_set 1
#define __CRT_HAVE_ftw 1
#define __CRT_HAVE_ftw64 1
#define __CRT_HAVE_funlockfile 1
#define __CRT_HAVE_futimens 1
#define __CRT_HAVE_futimes 1
#define __CRT_HAVE_futimesat 1
#define __CRT_HAVE_fwide 1
#define __CRT_HAVE_fwprintf 1
#define __CRT_HAVE_fwrite 1
#define __CRT_HAVE_fwrite_unlocked 1
#define __CRT_HAVE_fwscanf 1
#define __CRT_HAVE_gai_strerror 1
#define __CRT_HAVE_gcvt 1
#define __CRT_HAVE_get_avphys_pages 1
#define __CRT_HAVE_get_current_dir_name 1
#define __CRT_HAVE_get_kernel_syms 1
#define __CRT_HAVE_get_myaddress 1
#define __CRT_HAVE_get_nprocs 1
#define __CRT_HAVE_get_nprocs_conf 1
#define __CRT_HAVE_get_phys_pages 1
#define __CRT_HAVE_getaddrinfo 1
#define __CRT_HAVE_getaliasbyname 1
#define __CRT_HAVE_getaliasbyname_r 1
#define __CRT_HAVE_getaliasent 1
#define __CRT_HAVE_getaliasent_r 1
#define __CRT_HAVE_getauxval 1
#define __CRT_HAVE_getc 1
#define __CRT_HAVE_getc_unlocked 1
#define __CRT_HAVE_getchar 1
#define __CRT_HAVE_getchar_unlocked 1
#define __CRT_HAVE_getcontext 1
#define __CRT_HAVE_getcwd 1
#define __CRT_HAVE_getdate 1
#define __CRT_HAVE_getdate_err 1
#define __CRT_HAVE_getdate_r 1
#define __CRT_HAVE_getdelim 1
#define __CRT_HAVE_getdirentries 1
#define __CRT_HAVE_getdirentries64 1
#define __CRT_HAVE_getdomainname 1
#define __CRT_HAVE_getdtablesize 1
#define __CRT_HAVE_getegid 1
#define __CRT_HAVE_getenv 1
#define __CRT_HAVE_geteuid 1
#define __CRT_HAVE_getfsent 1
#define __CRT_HAVE_getfsfile 1
#define __CRT_HAVE_getfsspec 1
#define __CRT_HAVE_getgid 1
#define __CRT_HAVE_getgrent 1
#define __CRT_HAVE_getgrent_r 1
#define __CRT_HAVE_getgrgid 1
#define __CRT_HAVE_getgrgid_r 1
#define __CRT_HAVE_getgrnam 1
#define __CRT_HAVE_getgrnam_r 1
#define __CRT_HAVE_getgrouplist 1
#define __CRT_HAVE_getgroups 1
#define __CRT_HAVE_gethostbyaddr 1
#define __CRT_HAVE_gethostbyaddr_r 1
#define __CRT_HAVE_gethostbyname 1
#define __CRT_HAVE_gethostbyname2 1
#define __CRT_HAVE_gethostbyname2_r 1
#define __CRT_HAVE_gethostbyname_r 1
#define __CRT_HAVE_gethostent 1
#define __CRT_HAVE_gethostent_r 1
#define __CRT_HAVE_gethostid 1
#define __CRT_HAVE_gethostname 1
#define __CRT_HAVE_getifaddrs 1
#define __CRT_HAVE_getipv4sourcefilter 1
#define __CRT_HAVE_getitimer 1
#define __CRT_HAVE_getline 1
#define __CRT_HAVE_getloadavg 1
#define __CRT_HAVE_getlogin 1
#define __CRT_HAVE_getlogin_r 1
#define __CRT_HAVE_getmntent 1
#define __CRT_HAVE_getmntent_r 1
#define __CRT_HAVE_getmsg 1
#define __CRT_HAVE_getnameinfo 1
#define __CRT_HAVE_getnetbyaddr 1
#define __CRT_HAVE_getnetbyaddr_r 1
#define __CRT_HAVE_getnetbyname 1
#define __CRT_HAVE_getnetbyname_r 1
#define __CRT_HAVE_getnetent 1
#define __CRT_HAVE_getnetent_r 1
#define __CRT_HAVE_getnetgrent 1
#define __CRT_HAVE_getnetgrent_r 1
#define __CRT_HAVE_getnetname 1
#define __CRT_HAVE_getopt 1
#define __CRT_HAVE_getopt_long 1
#define __CRT_HAVE_getopt_long_only 1
#define __CRT_HAVE_getpagesize 1
#define __CRT_HAVE_getpass 1
#define __CRT_HAVE_getpeername 1
#define __CRT_HAVE_getpgid 1
#define __CRT_HAVE_getpgrp 1
#define __CRT_HAVE_getpid 1
#define __CRT_HAVE_getpmsg 1
#define __CRT_HAVE_getppid 1
#define __CRT_HAVE_getpriority 1
#define __CRT_HAVE_getprotobyname 1
#define __CRT_HAVE_getprotobyname_r 1
#define __CRT_HAVE_getprotobynumber 1
#define __CRT_HAVE_getprotobynumber_r 1
#define __CRT_HAVE_getprotoent 1
#define __CRT_HAVE_getprotoent_r 1
#define __CRT_HAVE_getpt 1
#define __CRT_HAVE_getpublickey 1
#define __CRT_HAVE_getpw 1
#define __CRT_HAVE_getpwent 1
#define __CRT_HAVE_getpwent_r 1
#define __CRT_HAVE_getpwnam 1
#define __CRT_HAVE_getpwnam_r 1
#define __CRT_HAVE_getpwuid 1
#define __CRT_HAVE_getpwuid_r 1
#define __CRT_HAVE_getresgid 1
#define __CRT_HAVE_getresuid 1
#define __CRT_HAVE_getrlimit 1
#define __CRT_HAVE_getrlimit64 1
#define __CRT_HAVE_getrpcbyname 1
#define __CRT_HAVE_getrpcbyname_r 1
#define __CRT_HAVE_getrpcbynumber 1
#define __CRT_HAVE_getrpcbynumber_r 1
#define __CRT_HAVE_getrpcent 1
#define __CRT_HAVE_getrpcent_r 1
#define __CRT_HAVE_getrpcport 1
#define __CRT_HAVE_getrusage 1
#define __CRT_HAVE_gets 1
#define __CRT_HAVE_getsecretkey 1
#define __CRT_HAVE_getservbyname 1
#define __CRT_HAVE_getservbyname_r 1
#define __CRT_HAVE_getservbyport 1
#define __CRT_HAVE_getservbyport_r 1
#define __CRT_HAVE_getservent 1
#define __CRT_HAVE_getservent_r 1
#define __CRT_HAVE_getsgent 1
#define __CRT_HAVE_getsgent_r 1
#define __CRT_HAVE_getsgnam 1
#define __CRT_HAVE_getsgnam_r 1
#define __CRT_HAVE_getsid 1
#define __CRT_HAVE_getsockname 1
#define __CRT_HAVE_getsockopt 1
#define __CRT_HAVE_getsourcefilter 1
#define __CRT_HAVE_getspent 1
#define __CRT_HAVE_getspent_r 1
#define __CRT_HAVE_getspnam 1
#define __CRT_HAVE_getspnam_r 1
#define __CRT_HAVE_getsubopt 1
#define __CRT_HAVE_gettext 1
#define __CRT_HAVE_gettimeofday 1
#define __CRT_HAVE_getttyent 1
#define __CRT_HAVE_getttynam 1
#define __CRT_HAVE_getuid 1
#define __CRT_HAVE_getusershell 1
#define __CRT_HAVE_getutent 1
#define __CRT_HAVE_getutent_r 1
#define __CRT_HAVE_getutid 1
#define __CRT_HAVE_getutid_r 1
#define __CRT_HAVE_getutline 1
#define __CRT_HAVE_getutline_r 1
#define __CRT_HAVE_getutmp 1
#define __CRT_HAVE_getutmpx 1
#define __CRT_HAVE_getutxent 1
#define __CRT_HAVE_getutxid 1
#define __CRT_HAVE_getutxline 1
#define __CRT_HAVE_getw 1
#define __CRT_HAVE_getwc 1
#define __CRT_HAVE_getwc_unlocked 1
#define __CRT_HAVE_getwchar 1
#define __CRT_HAVE_getwchar_unlocked 1
#define __CRT_HAVE_getwd 1
#define __CRT_HAVE_getxattr 1
#define __CRT_HAVE_glob 1
#define __CRT_HAVE_glob64 1
#define __CRT_HAVE_glob_pattern_p 1
#define __CRT_HAVE_globfree 1
#define __CRT_HAVE_globfree64 1
#define __CRT_HAVE_gmtime 1
#define __CRT_HAVE_gmtime_r 1
#define __CRT_HAVE_gnu_dev_major 1
#define __CRT_HAVE_gnu_dev_makedev 1
#define __CRT_HAVE_gnu_dev_minor 1
#define __CRT_HAVE_gnu_get_libc_release 1
#define __CRT_HAVE_gnu_get_libc_version 1
#define __CRT_HAVE_grantpt 1
#define __CRT_HAVE_group_member 1
#define __CRT_HAVE_gsignal 1
#define __CRT_HAVE_gtty 1
#define __CRT_HAVE_h_errlist 1
#define __CRT_HAVE_h_nerr 1
#define __CRT_HAVE_hasmntopt 1
#define __CRT_HAVE_hcreate 1
#define __CRT_HAVE_hcreate_r 1
#define __CRT_HAVE_hdestroy 1
#define __CRT_HAVE_hdestroy_r 1
#define __CRT_HAVE_herror 1
#define __CRT_HAVE_host2netname 1
#define __CRT_HAVE_hsearch 1
#define __CRT_HAVE_hsearch_r 1
#define __CRT_HAVE_hstrerror 1
#define __CRT_HAVE_htonl 1
#define __CRT_HAVE_htons 1
#define __CRT_HAVE_iconv 1
#define __CRT_HAVE_iconv_close 1
#define __CRT_HAVE_iconv_open 1
#define __CRT_HAVE_if_freenameindex 1
#define __CRT_HAVE_if_indextoname 1
#define __CRT_HAVE_if_nameindex 1
#define __CRT_HAVE_if_nametoindex 1
#define __CRT_HAVE_imaxabs 1
#define __CRT_HAVE_imaxdiv 1
#define __CRT_HAVE_in6addr_any 1
#define __CRT_HAVE_in6addr_loopback 1
#define __CRT_HAVE_index 1
#define __CRT_HAVE_inet6_opt_append 1
#define __CRT_HAVE_inet6_opt_find 1
#define __CRT_HAVE_inet6_opt_finish 1
#define __CRT_HAVE_inet6_opt_get_val 1
#define __CRT_HAVE_inet6_opt_init 1
#define __CRT_HAVE_inet6_opt_next 1
#define __CRT_HAVE_inet6_opt_set_val 1
#define __CRT_HAVE_inet6_option_alloc 1
#define __CRT_HAVE_inet6_option_append 1
#define __CRT_HAVE_inet6_option_find 1
#define __CRT_HAVE_inet6_option_init 1
#define __CRT_HAVE_inet6_option_next 1
#define __CRT_HAVE_inet6_option_space 1
#define __CRT_HAVE_inet6_rth_add 1
#define __CRT_HAVE_inet6_rth_getaddr 1
#define __CRT_HAVE_inet6_rth_init 1
#define __CRT_HAVE_inet6_rth_reverse 1
#define __CRT_HAVE_inet6_rth_segments 1
#define __CRT_HAVE_inet6_rth_space 1
#define __CRT_HAVE_inet_addr 1
#define __CRT_HAVE_inet_aton 1
#define __CRT_HAVE_inet_lnaof 1
#define __CRT_HAVE_inet_makeaddr 1
#define __CRT_HAVE_inet_netof 1
#define __CRT_HAVE_inet_network 1
#define __CRT_HAVE_inet_nsap_addr 1
#define __CRT_HAVE_inet_nsap_ntoa 1
#define __CRT_HAVE_inet_ntoa 1
#define __CRT_HAVE_inet_ntop 1
#define __CRT_HAVE_inet_pton 1
#define __CRT_HAVE_init_module 1
#define __CRT_HAVE_initgroups 1
#define __CRT_HAVE_initstate 1
#define __CRT_HAVE_initstate_r 1
#define __CRT_HAVE_innetgr 1
#define __CRT_HAVE_inotify_add_watch 1
#define __CRT_HAVE_inotify_init 1
#define __CRT_HAVE_inotify_init1 1
#define __CRT_HAVE_inotify_rm_watch 1
#define __CRT_HAVE_insque 1
#define __CRT_HAVE_ioctl 1
#define __CRT_HAVE_ioperm 1
#define __CRT_HAVE_iopl 1
#define __CRT_HAVE_iruserok 1
#define __CRT_HAVE_iruserok_af 1
#define __CRT_HAVE_isalnum 1
#define __CRT_HAVE_isalnum_l 1
#define __CRT_HAVE_isalpha 1
#define __CRT_HAVE_isalpha_l 1
#define __CRT_HAVE_isascii 1
#define __CRT_HAVE_isastream 1
#define __CRT_HAVE_isatty 1
#define __CRT_HAVE_isblank 1
#define __CRT_HAVE_isblank_l 1
#define __CRT_HAVE_iscntrl 1
#define __CRT_HAVE_iscntrl_l 1
#define __CRT_HAVE_isctype 1
#define __CRT_HAVE_isdigit 1
#define __CRT_HAVE_isdigit_l 1
#define __CRT_HAVE_isfdtype 1
#define __CRT_HAVE_isgraph 1
#define __CRT_HAVE_isgraph_l 1
#define __CRT_HAVE_isinf 1
#define __CRT_HAVE_isinff 1
#define __CRT_HAVE_isinfl 1
#define __CRT_HAVE_islower 1
#define __CRT_HAVE_islower_l 1
#define __CRT_HAVE_isnan 1
#define __CRT_HAVE_isnanf 1
#define __CRT_HAVE_isnanl 1
#define __CRT_HAVE_isprint 1
#define __CRT_HAVE_isprint_l 1
#define __CRT_HAVE_ispunct 1
#define __CRT_HAVE_ispunct_l 1
#define __CRT_HAVE_isspace 1
#define __CRT_HAVE_isspace_l 1
#define __CRT_HAVE_isupper 1
#define __CRT_HAVE_isupper_l 1
#define __CRT_HAVE_iswalnum 1
#define __CRT_HAVE_iswalnum_l 1
#define __CRT_HAVE_iswalpha 1
#define __CRT_HAVE_iswalpha_l 1
#define __CRT_HAVE_iswblank 1
#define __CRT_HAVE_iswblank_l 1
#define __CRT_HAVE_iswcntrl 1
#define __CRT_HAVE_iswcntrl_l 1
#define __CRT_HAVE_iswctype 1
#define __CRT_HAVE_iswctype_l 1
#define __CRT_HAVE_iswdigit 1
#define __CRT_HAVE_iswdigit_l 1
#define __CRT_HAVE_iswgraph 1
#define __CRT_HAVE_iswgraph_l 1
#define __CRT_HAVE_iswlower 1
#define __CRT_HAVE_iswlower_l 1
#define __CRT_HAVE_iswprint 1
#define __CRT_HAVE_iswprint_l 1
#define __CRT_HAVE_iswpunct 1
#define __CRT_HAVE_iswpunct_l 1
#define __CRT_HAVE_iswspace 1
#define __CRT_HAVE_iswspace_l 1
#define __CRT_HAVE_iswupper 1
#define __CRT_HAVE_iswupper_l 1
#define __CRT_HAVE_iswxdigit 1
#define __CRT_HAVE_iswxdigit_l 1
#define __CRT_HAVE_isxdigit 1
#define __CRT_HAVE_isxdigit_l 1
#define __CRT_HAVE_jrand48 1
#define __CRT_HAVE_jrand48_r 1
#define __CRT_HAVE_key_decryptsession 1
#define __CRT_HAVE_key_decryptsession_pk 1
#define __CRT_HAVE_key_encryptsession 1
#define __CRT_HAVE_key_encryptsession_pk 1
#define __CRT_HAVE_key_gendes 1
#define __CRT_HAVE_key_get_conv 1
#define __CRT_HAVE_key_secretkey_is_set 1
#define __CRT_HAVE_key_setnet 1
#define __CRT_HAVE_key_setsecret 1
#define __CRT_HAVE_kill 1
#define __CRT_HAVE_killpg 1
#define __CRT_HAVE_klogctl 1
#define __CRT_HAVE_l64a 1
#define __CRT_HAVE_labs 1
#define __CRT_HAVE_lchmod 1
#define __CRT_HAVE_lchown 1
#define __CRT_HAVE_lckpwdf 1
#define __CRT_HAVE_lcong48 1
#define __CRT_HAVE_lcong48_r 1
#define __CRT_HAVE_ldexp 1
#define __CRT_HAVE_ldexpf 1
#define __CRT_HAVE_ldexpl 1
#define __CRT_HAVE_ldiv 1
#define __CRT_HAVE_lfind 1
#define __CRT_HAVE_lgetxattr 1
#define __CRT_HAVE_link 1
#define __CRT_HAVE_linkat 1
#define __CRT_HAVE_listen 1
#define __CRT_HAVE_listxattr 1
#define __CRT_HAVE_llabs 1
#define __CRT_HAVE_lldiv 1
#define __CRT_HAVE_llistxattr 1
#define __CRT_HAVE_llseek 1
#define __CRT_HAVE_loc1 1
#define __CRT_HAVE_loc2 1
#define __CRT_HAVE_localeconv 1
#define __CRT_HAVE_localtime 1
#define __CRT_HAVE_localtime_r 1
#define __CRT_HAVE_lockf 1
#define __CRT_HAVE_lockf64 1
#define __CRT_HAVE_locs 1
#define __CRT_HAVE_longjmp 1
#define __CRT_HAVE_lrand48 1
#define __CRT_HAVE_lrand48_r 1
#define __CRT_HAVE_lremovexattr 1
#define __CRT_HAVE_lsearch 1
#define __CRT_HAVE_lseek 1
#define __CRT_HAVE_lseek64 1
#define __CRT_HAVE_lsetxattr 1
#define __CRT_HAVE_lutimes 1
#define __CRT_HAVE_madvise 1
#define __CRT_HAVE_makecontext 1
#define __CRT_HAVE_mallinfo 1
#define __CRT_HAVE_malloc 1
#define __CRT_HAVE_malloc_get_state 1
#define __CRT_HAVE_malloc_info 1
#define __CRT_HAVE_malloc_set_state 1
#define __CRT_HAVE_malloc_stats 1
#define __CRT_HAVE_malloc_trim 1
#define __CRT_HAVE_malloc_usable_size 1
#define __CRT_HAVE_mallopt 1
#define __CRT_HAVE_mallwatch 1
#define __CRT_HAVE_mblen 1
#define __CRT_HAVE_mbrlen 1
#define __CRT_HAVE_mbrtoc16 1
#define __CRT_HAVE_mbrtoc32 1
#define __CRT_HAVE_mbrtowc 1
#define __CRT_HAVE_mbsinit 1
#define __CRT_HAVE_mbsnrtowcs 1
#define __CRT_HAVE_mbsrtowcs 1
#define __CRT_HAVE_mbstowcs 1
#define __CRT_HAVE_mbtowc 1
#define __CRT_HAVE_mcheck 1
#define __CRT_HAVE_mcheck_check_all 1
#define __CRT_HAVE_mcheck_pedantic 1
#define __CRT_HAVE_mcount 1
#define __CRT_HAVE_memalign 1
#define __CRT_HAVE_memccpy 1
#define __CRT_HAVE_memchr 1
#define __CRT_HAVE_memcmp 1
#define __CRT_HAVE_memcpy 1
#define __CRT_HAVE_memfrob 1
#define __CRT_HAVE_memmem 1
#define __CRT_HAVE_memmove 1
#define __CRT_HAVE_mempcpy 1
#define __CRT_HAVE_memrchr 1
#define __CRT_HAVE_memset 1
#define __CRT_HAVE_mincore 1
#define __CRT_HAVE_mkdir 1
#define __CRT_HAVE_mkdirat 1
#define __CRT_HAVE_mkdtemp 1
#define __CRT_HAVE_mkfifo 1
#define __CRT_HAVE_mkfifoat 1
#define __CRT_HAVE_mkostemp 1
#define __CRT_HAVE_mkostemp64 1
#define __CRT_HAVE_mkostemps 1
#define __CRT_HAVE_mkostemps64 1
#define __CRT_HAVE_mkstemp 1
#define __CRT_HAVE_mkstemp64 1
#define __CRT_HAVE_mkstemps 1
#define __CRT_HAVE_mkstemps64 1
#define __CRT_HAVE_mktemp 1
#define __CRT_HAVE_mktime 1
#define __CRT_HAVE_mlock 1
#define __CRT_HAVE_mlockall 1
#define __CRT_HAVE_mmap 1
#define __CRT_HAVE_mmap64 1
#define __CRT_HAVE_modf 1
#define __CRT_HAVE_modff 1
#define __CRT_HAVE_modfl 1
#define __CRT_HAVE_modify_ldt 1
#define __CRT_HAVE_moncontrol 1
#define __CRT_HAVE_monstartup 1
#define __CRT_HAVE_mount 1
#define __CRT_HAVE_mprobe 1
#define __CRT_HAVE_mprotect 1
#define __CRT_HAVE_mrand48 1
#define __CRT_HAVE_mrand48_r 1
#define __CRT_HAVE_mremap 1
#define __CRT_HAVE_msgctl 1
#define __CRT_HAVE_msgget 1
#define __CRT_HAVE_msgrcv 1
#define __CRT_HAVE_msgsnd 1
#define __CRT_HAVE_msync 1
#define __CRT_HAVE_mtrace 1
#define __CRT_HAVE_munlock 1
#define __CRT_HAVE_munlockall 1
#define __CRT_HAVE_munmap 1
#define __CRT_HAVE_muntrace 1
#define __CRT_HAVE_name_to_handle_at 1
#define __CRT_HAVE_nanosleep 1
#define __CRT_HAVE_netname2host 1
#define __CRT_HAVE_netname2user 1
#define __CRT_HAVE_newlocale 1
#define __CRT_HAVE_nfsservctl 1
#define __CRT_HAVE_nftw 1
#define __CRT_HAVE_nftw64 1
#define __CRT_HAVE_ngettext 1
#define __CRT_HAVE_nice 1
#define __CRT_HAVE_nl_langinfo 1
#define __CRT_HAVE_nl_langinfo_l 1
#define __CRT_HAVE_nrand48 1
#define __CRT_HAVE_nrand48_r 1
#define __CRT_HAVE_ntohl 1
#define __CRT_HAVE_ntohs 1
#define __CRT_HAVE_ntp_adjtime 1
#define __CRT_HAVE_ntp_gettime 1
#define __CRT_HAVE_ntp_gettimex 1
#define __CRT_HAVE_obstack_alloc_failed_hand 1
#define __CRT_HAVE_obstack_exit_failure 1
#define __CRT_HAVE_obstack_free 1
#define __CRT_HAVE_obstack_printf 1
#define __CRT_HAVE_obstack_vprintf 1
#define __CRT_HAVE_on_exit 1
#define __CRT_HAVE_open 1
#define __CRT_HAVE_open64 1
#define __CRT_HAVE_open_by_handle_at 1
#define __CRT_HAVE_open_memstream 1
#define __CRT_HAVE_open_wmemstream 1
#define __CRT_HAVE_openat 1
#define __CRT_HAVE_openat64 1
#define __CRT_HAVE_opendir 1
#define __CRT_HAVE_openlog 1
#define __CRT_HAVE_optarg 1
#define __CRT_HAVE_opterr 1
#define __CRT_HAVE_optind 1
#define __CRT_HAVE_optopt 1
#define __CRT_HAVE_parse_printf_format 1
#define __CRT_HAVE_passwd2des 1
#define __CRT_HAVE_pathconf 1
#define __CRT_HAVE_pause 1
#define __CRT_HAVE_pclose 1
#define __CRT_HAVE_perror 1
#define __CRT_HAVE_personality 1
#define __CRT_HAVE_pipe 1
#define __CRT_HAVE_pipe2 1
#define __CRT_HAVE_pivot_root 1
#define __CRT_HAVE_pmap_getmaps 1
#define __CRT_HAVE_pmap_getport 1
#define __CRT_HAVE_pmap_rmtcall 1
#define __CRT_HAVE_pmap_set 1
#define __CRT_HAVE_pmap_unset 1
#define __CRT_HAVE_poll 1
#define __CRT_HAVE_popen 1
#define __CRT_HAVE_posix_fadvise 1
#define __CRT_HAVE_posix_fadvise64 1
#define __CRT_HAVE_posix_fallocate 1
#define __CRT_HAVE_posix_fallocate64 1
#define __CRT_HAVE_posix_madvise 1
#define __CRT_HAVE_posix_memalign 1
#define __CRT_HAVE_posix_openpt 1
#define __CRT_HAVE_posix_spawn 1
#define __CRT_HAVE_posix_spawn_file_actions_ 1
#define __CRT_HAVE_posix_spawnattr_destroy 1
#define __CRT_HAVE_posix_spawnattr_getflags 1
#define __CRT_HAVE_posix_spawnattr_getpgroup 1
#define __CRT_HAVE_posix_spawnattr_getschedp 1
#define __CRT_HAVE_posix_spawnattr_getsigdef 1
#define __CRT_HAVE_posix_spawnattr_getsigmas 1
#define __CRT_HAVE_posix_spawnattr_init 1
#define __CRT_HAVE_posix_spawnattr_setflags 1
#define __CRT_HAVE_posix_spawnattr_setpgroup 1
#define __CRT_HAVE_posix_spawnattr_setschedp 1
#define __CRT_HAVE_posix_spawnattr_setsigdef 1
#define __CRT_HAVE_posix_spawnattr_setsigmas 1
#define __CRT_HAVE_posix_spawnp 1
#define __CRT_HAVE_ppoll 1
#define __CRT_HAVE_prctl 1
#define __CRT_HAVE_pread 1
#define __CRT_HAVE_pread64 1
#define __CRT_HAVE_preadv 1
#define __CRT_HAVE_preadv64 1
#define __CRT_HAVE_printf 1
#define __CRT_HAVE_printf_size 1
#define __CRT_HAVE_printf_size_info 1
#define __CRT_HAVE_prlimit 1
#define __CRT_HAVE_prlimit64 1
#define __CRT_HAVE_process_vm_readv 1
#define __CRT_HAVE_process_vm_writev 1
#define __CRT_HAVE_profil 1
#define __CRT_HAVE_program_invocation_name 1
#define __CRT_HAVE_program_invocation_short_ 1
#define __CRT_HAVE_pselect 1
#define __CRT_HAVE_psiginfo 1
#define __CRT_HAVE_psignal 1
#define __CRT_HAVE_pthread_attr_destroy 1
#define __CRT_HAVE_pthread_attr_getdetachsta 1
#define __CRT_HAVE_pthread_attr_getinheritsc 1
#define __CRT_HAVE_pthread_attr_getschedpara 1
#define __CRT_HAVE_pthread_attr_getschedpoli 1
#define __CRT_HAVE_pthread_attr_getscope 1
#define __CRT_HAVE_pthread_attr_init 1
#define __CRT_HAVE_pthread_attr_setdetachsta 1
#define __CRT_HAVE_pthread_attr_setinheritsc 1
#define __CRT_HAVE_pthread_attr_setschedpara 1
#define __CRT_HAVE_pthread_attr_setschedpoli 1
#define __CRT_HAVE_pthread_attr_setscope 1
#define __CRT_HAVE_pthread_cond_broadcast 1
#define __CRT_HAVE_pthread_cond_destroy 1
#define __CRT_HAVE_pthread_cond_init 1
#define __CRT_HAVE_pthread_cond_signal 1
#define __CRT_HAVE_pthread_cond_timedwait 1
#define __CRT_HAVE_pthread_cond_wait 1
#define __CRT_HAVE_pthread_condattr_destroy 1
#define __CRT_HAVE_pthread_condattr_init 1
#define __CRT_HAVE_pthread_equal 1
#define __CRT_HAVE_pthread_exit 1
#define __CRT_HAVE_pthread_getschedparam 1
#define __CRT_HAVE_pthread_mutex_destroy 1
#define __CRT_HAVE_pthread_mutex_init 1
#define __CRT_HAVE_pthread_mutex_lock 1
#define __CRT_HAVE_pthread_mutex_unlock 1
#define __CRT_HAVE_pthread_self 1
#define __CRT_HAVE_pthread_setcancelstate 1
#define __CRT_HAVE_pthread_setcanceltype 1
#define __CRT_HAVE_pthread_setschedparam 1
#define __CRT_HAVE_ptrace 1
#define __CRT_HAVE_ptsname 1
#define __CRT_HAVE_ptsname_r 1
#define __CRT_HAVE_putc 1
#define __CRT_HAVE_putc_unlocked 1
#define __CRT_HAVE_putchar 1
#define __CRT_HAVE_putchar_unlocked 1
#define __CRT_HAVE_putenv 1
#define __CRT_HAVE_putgrent 1
#define __CRT_HAVE_putmsg 1
#define __CRT_HAVE_putpmsg 1
#define __CRT_HAVE_putpwent 1
#define __CRT_HAVE_puts 1
#define __CRT_HAVE_putsgent 1
#define __CRT_HAVE_putspent 1
#define __CRT_HAVE_pututline 1
#define __CRT_HAVE_pututxline 1
#define __CRT_HAVE_putw 1
#define __CRT_HAVE_putwc 1
#define __CRT_HAVE_putwc_unlocked 1
#define __CRT_HAVE_putwchar 1
#define __CRT_HAVE_putwchar_unlocked 1
#define __CRT_HAVE_pvalloc 1
#define __CRT_HAVE_pwrite 1
#define __CRT_HAVE_pwrite64 1
#define __CRT_HAVE_pwritev 1
#define __CRT_HAVE_pwritev64 1
#define __CRT_HAVE_qecvt 1
#define __CRT_HAVE_qecvt_r 1
#define __CRT_HAVE_qfcvt 1
#define __CRT_HAVE_qfcvt_r 1
#define __CRT_HAVE_qgcvt 1
#define __CRT_HAVE_qsort 1
#define __CRT_HAVE_qsort_r 1
#define __CRT_HAVE_query_module 1
#define __CRT_HAVE_quick_exit 1
#define __CRT_HAVE_quotactl 1
#define __CRT_HAVE_raise 1
#define __CRT_HAVE_rand 1
#define __CRT_HAVE_rand_r 1
#define __CRT_HAVE_random 1
#define __CRT_HAVE_random_r 1
#define __CRT_HAVE_rawmemchr 1
#define __CRT_HAVE_rcmd 1
#define __CRT_HAVE_rcmd_af 1
#define __CRT_HAVE_re_comp 1
#define __CRT_HAVE_re_compile_fastmap 1
#define __CRT_HAVE_re_compile_pattern 1
#define __CRT_HAVE_re_exec 1
#define __CRT_HAVE_re_match 1
#define __CRT_HAVE_re_match_2 1
#define __CRT_HAVE_re_max_failures 1
#define __CRT_HAVE_re_search 1
#define __CRT_HAVE_re_search_2 1
#define __CRT_HAVE_re_set_registers 1
#define __CRT_HAVE_re_set_syntax 1
#define __CRT_HAVE_re_syntax_options 1
#define __CRT_HAVE_read 1
#define __CRT_HAVE_readahead 1
#define __CRT_HAVE_readdir 1
#define __CRT_HAVE_readdir64 1
#define __CRT_HAVE_readdir64_r 1
#define __CRT_HAVE_readdir_r 1
#define __CRT_HAVE_readlink 1
#define __CRT_HAVE_readlinkat 1
#define __CRT_HAVE_readv 1
#define __CRT_HAVE_realloc 1
#define __CRT_HAVE_realpath 1
#define __CRT_HAVE_reboot 1
#define __CRT_HAVE_recv 1
#define __CRT_HAVE_recvfrom 1
#define __CRT_HAVE_recvmmsg 1
#define __CRT_HAVE_recvmsg 1
#define __CRT_HAVE_regcomp 1
#define __CRT_HAVE_regerror 1
#define __CRT_HAVE_regexec 1
#define __CRT_HAVE_regfree 1
#define __CRT_HAVE_register_printf_function 1
#define __CRT_HAVE_register_printf_modifier 1
#define __CRT_HAVE_register_printf_specifier 1
#define __CRT_HAVE_register_printf_type 1
#define __CRT_HAVE_registerrpc 1
#define __CRT_HAVE_remap_file_pages 1
#define __CRT_HAVE_remove 1
#define __CRT_HAVE_removexattr 1
#define __CRT_HAVE_remque 1
#define __CRT_HAVE_rename 1
#define __CRT_HAVE_renameat 1
#define __CRT_HAVE_res_init 1
#define __CRT_HAVE_revoke 1
#define __CRT_HAVE_rewind 1
#define __CRT_HAVE_rewinddir 1
#define __CRT_HAVE_rexec 1
#define __CRT_HAVE_rexec_af 1
#define __CRT_HAVE_rexecoptions 1
#define __CRT_HAVE_rindex 1
#define __CRT_HAVE_rmdir 1
#define __CRT_HAVE_rpc_createerr 1
#define __CRT_HAVE_rpmatch 1
#define __CRT_HAVE_rresvport 1
#define __CRT_HAVE_rresvport_af 1
#define __CRT_HAVE_rtime 1
#define __CRT_HAVE_ruserok 1
#define __CRT_HAVE_ruserok_af 1
#define __CRT_HAVE_ruserpass 1
#define __CRT_HAVE_sbrk 1
#define __CRT_HAVE_scalbln 1
#define __CRT_HAVE_scalblnf 1
#define __CRT_HAVE_scalblnl 1
#define __CRT_HAVE_scalbn 1
#define __CRT_HAVE_scalbnf 1
#define __CRT_HAVE_scalbnl 1
#define __CRT_HAVE_scandir 1
#define __CRT_HAVE_scandir64 1
#define __CRT_HAVE_scandirat 1
#define __CRT_HAVE_scandirat64 1
#define __CRT_HAVE_scanf 1
#define __CRT_HAVE_sched_get_priority_max 1
#define __CRT_HAVE_sched_get_priority_min 1
#define __CRT_HAVE_sched_getaffinity 1
#define __CRT_HAVE_sched_getcpu 1
#define __CRT_HAVE_sched_getparam 1
#define __CRT_HAVE_sched_getscheduler 1
#define __CRT_HAVE_sched_rr_get_interval 1
#define __CRT_HAVE_sched_setaffinity 1
#define __CRT_HAVE_sched_setparam 1
#define __CRT_HAVE_sched_setscheduler 1
#define __CRT_HAVE_sched_yield 1
#define __CRT_HAVE_secure_getenv 1
#define __CRT_HAVE_seed48 1
#define __CRT_HAVE_seed48_r 1
#define __CRT_HAVE_seekdir 1
#define __CRT_HAVE_select 1
#define __CRT_HAVE_semctl 1
#define __CRT_HAVE_semget 1
#define __CRT_HAVE_semop 1
#define __CRT_HAVE_semtimedop 1
#define __CRT_HAVE_send 1
#define __CRT_HAVE_sendfile 1
#define __CRT_HAVE_sendfile64 1
#define __CRT_HAVE_sendmmsg 1
#define __CRT_HAVE_sendmsg 1
#define __CRT_HAVE_sendto 1
#define __CRT_HAVE_setaliasent 1
#define __CRT_HAVE_setbuf 1
#define __CRT_HAVE_setbuffer 1
#define __CRT_HAVE_setcontext 1
#define __CRT_HAVE_setdomainname 1
#define __CRT_HAVE_setegid 1
#define __CRT_HAVE_setenv 1
#define __CRT_HAVE_seteuid 1
#define __CRT_HAVE_setfsent 1
#define __CRT_HAVE_setfsgid 1
#define __CRT_HAVE_setfsuid 1
#define __CRT_HAVE_setgid 1
#define __CRT_HAVE_setgrent 1
#define __CRT_HAVE_setgroups 1
#define __CRT_HAVE_sethostent 1
#define __CRT_HAVE_sethostid 1
#define __CRT_HAVE_sethostname 1
#define __CRT_HAVE_setipv4sourcefilter 1
#define __CRT_HAVE_setitimer 1
#define __CRT_HAVE_setjmp 1
#define __CRT_HAVE_setlinebuf 1
#define __CRT_HAVE_setlocale 1
#define __CRT_HAVE_setlogin 1
#define __CRT_HAVE_setlogmask 1
#define __CRT_HAVE_setmntent 1
#define __CRT_HAVE_setnetent 1
#define __CRT_HAVE_setnetgrent 1
#define __CRT_HAVE_setns 1
#define __CRT_HAVE_setpgid 1
#define __CRT_HAVE_setpgrp 1
#define __CRT_HAVE_setpriority 1
#define __CRT_HAVE_setprotoent 1
#define __CRT_HAVE_setpwent 1
#define __CRT_HAVE_setregid 1
#define __CRT_HAVE_setresgid 1
#define __CRT_HAVE_setresuid 1
#define __CRT_HAVE_setreuid 1
#define __CRT_HAVE_setrlimit 1
#define __CRT_HAVE_setrlimit64 1
#define __CRT_HAVE_setrpcent 1
#define __CRT_HAVE_setservent 1
#define __CRT_HAVE_setsgent 1
#define __CRT_HAVE_setsid 1
#define __CRT_HAVE_setsockopt 1
#define __CRT_HAVE_setsourcefilter 1
#define __CRT_HAVE_setspent 1
#define __CRT_HAVE_setstate 1
#define __CRT_HAVE_setstate_r 1
#define __CRT_HAVE_settimeofday 1
#define __CRT_HAVE_setttyent 1
#define __CRT_HAVE_setuid 1
#define __CRT_HAVE_setusershell 1
#define __CRT_HAVE_setutent 1
#define __CRT_HAVE_setutxent 1
#define __CRT_HAVE_setvbuf 1
#define __CRT_HAVE_setxattr 1
#define __CRT_HAVE_sgetsgent 1
#define __CRT_HAVE_sgetsgent_r 1
#define __CRT_HAVE_sgetspent 1
#define __CRT_HAVE_sgetspent_r 1
#define __CRT_HAVE_shmat 1
#define __CRT_HAVE_shmctl 1
#define __CRT_HAVE_shmdt 1
#define __CRT_HAVE_shmget 1
#define __CRT_HAVE_shutdown 1
#define __CRT_HAVE_sigaction 1
#define __CRT_HAVE_sigaddset 1
#define __CRT_HAVE_sigaltstack 1
#define __CRT_HAVE_sigandset 1
#define __CRT_HAVE_sigblock 1
#define __CRT_HAVE_sigdelset 1
#define __CRT_HAVE_sigemptyset 1
#define __CRT_HAVE_sigfillset 1
#define __CRT_HAVE_siggetmask 1
#define __CRT_HAVE_sighold 1
#define __CRT_HAVE_sigignore 1
#define __CRT_HAVE_siginterrupt 1
#define __CRT_HAVE_sigisemptyset 1
#define __CRT_HAVE_sigismember 1
#define __CRT_HAVE_siglongjmp 1
#define __CRT_HAVE_signal 1
#define __CRT_HAVE_signalfd 1
#define __CRT_HAVE_sigorset 1
#define __CRT_HAVE_sigpause 1
#define __CRT_HAVE_sigpending 1
#define __CRT_HAVE_sigprocmask 1
#define __CRT_HAVE_sigqueue 1
#define __CRT_HAVE_sigrelse 1
#define __CRT_HAVE_sigreturn 1
#define __CRT_HAVE_sigset 1
#define __CRT_HAVE_sigsetmask 1
#define __CRT_HAVE_sigstack 1
#define __CRT_HAVE_sigsuspend 1
#define __CRT_HAVE_sigtimedwait 1
#define __CRT_HAVE_sigvec 1
#define __CRT_HAVE_sigwait 1
#define __CRT_HAVE_sigwaitinfo 1
#define __CRT_HAVE_sleep 1
#define __CRT_HAVE_snprintf 1
#define __CRT_HAVE_sockatmark 1
#define __CRT_HAVE_socket 1
#define __CRT_HAVE_socketpair 1
#define __CRT_HAVE_splice 1
#define __CRT_HAVE_sprintf 1
#define __CRT_HAVE_sprofil 1
#define __CRT_HAVE_srand 1
#define __CRT_HAVE_srand48 1
#define __CRT_HAVE_srand48_r 1
#define __CRT_HAVE_srandom 1
#define __CRT_HAVE_srandom_r 1
#define __CRT_HAVE_sscanf 1
#define __CRT_HAVE_ssignal 1
#define __CRT_HAVE_sstk 1
#define __CRT_HAVE_statfs 1
#define __CRT_HAVE_statfs64 1
#define __CRT_HAVE_statvfs 1
#define __CRT_HAVE_statvfs64 1
#define __CRT_HAVE_stderr 1
#define __CRT_HAVE_stdin 1
#define __CRT_HAVE_stdout 1
#define __CRT_HAVE_step 1
#define __CRT_HAVE_stime 1
#define __CRT_HAVE_stpcpy 1
#define __CRT_HAVE_stpncpy 1
#define __CRT_HAVE_strcasecmp 1
#define __CRT_HAVE_strcasecmp_l 1
#define __CRT_HAVE_strcasestr 1
#define __CRT_HAVE_strcat 1
#define __CRT_HAVE_strchr 1
#define __CRT_HAVE_strchrnul 1
#define __CRT_HAVE_strcmp 1
#define __CRT_HAVE_strcoll 1
#define __CRT_HAVE_strcoll_l 1
#define __CRT_HAVE_strcpy 1
#define __CRT_HAVE_strcspn 1
#define __CRT_HAVE_strdup 1
#define __CRT_HAVE_strerror 1
#define __CRT_HAVE_strerror_l 1
#define __CRT_HAVE_strerror_r 1
#define __CRT_HAVE_strfmon 1
#define __CRT_HAVE_strfmon_l 1
#define __CRT_HAVE_strfry 1
#define __CRT_HAVE_strftime 1
#define __CRT_HAVE_strftime_l 1
#define __CRT_HAVE_strlen 1
#define __CRT_HAVE_strncasecmp 1
#define __CRT_HAVE_strncasecmp_l 1
#define __CRT_HAVE_strncat 1
#define __CRT_HAVE_strncmp 1
#define __CRT_HAVE_strncpy 1
#define __CRT_HAVE_strndup 1
#define __CRT_HAVE_strnlen 1
#define __CRT_HAVE_strpbrk 1
#define __CRT_HAVE_strptime 1
#define __CRT_HAVE_strptime_l 1
#define __CRT_HAVE_strrchr 1
#define __CRT_HAVE_strsep 1
#define __CRT_HAVE_strsignal 1
#define __CRT_HAVE_strspn 1
#define __CRT_HAVE_strstr 1
#define __CRT_HAVE_strtod 1
#define __CRT_HAVE_strtod_l 1
#define __CRT_HAVE_strtof 1
#define __CRT_HAVE_strtof_l 1
#define __CRT_HAVE_strtoimax 1
#define __CRT_HAVE_strtok 1
#define __CRT_HAVE_strtok_r 1
#define __CRT_HAVE_strtol 1
#define __CRT_HAVE_strtol_l 1
#define __CRT_HAVE_strtold 1
#define __CRT_HAVE_strtold_l 1
#define __CRT_HAVE_strtoll 1
#define __CRT_HAVE_strtoll_l 1
#define __CRT_HAVE_strtoq 1
#define __CRT_HAVE_strtoul 1
#define __CRT_HAVE_strtoul_l 1
#define __CRT_HAVE_strtoull 1
#define __CRT_HAVE_strtoull_l 1
#define __CRT_HAVE_strtoumax 1
#define __CRT_HAVE_strtouq 1
#define __CRT_HAVE_strverscmp 1
#define __CRT_HAVE_strxfrm 1
#define __CRT_HAVE_strxfrm_l 1
#define __CRT_HAVE_stty 1
#define __CRT_HAVE_svc_exit 1
#define __CRT_HAVE_svc_fdset 1
#define __CRT_HAVE_svc_getreq 1
#define __CRT_HAVE_svc_getreq_common 1
#define __CRT_HAVE_svc_getreq_poll 1
#define __CRT_HAVE_svc_getreqset 1
#define __CRT_HAVE_svc_max_pollfd 1
#define __CRT_HAVE_svc_pollfd 1
#define __CRT_HAVE_svc_register 1
#define __CRT_HAVE_svc_run 1
#define __CRT_HAVE_svc_sendreply 1
#define __CRT_HAVE_svc_unregister 1
#define __CRT_HAVE_svcauthdes_stats 1
#define __CRT_HAVE_svcerr_auth 1
#define __CRT_HAVE_svcerr_decode 1
#define __CRT_HAVE_svcerr_noproc 1
#define __CRT_HAVE_svcerr_noprog 1
#define __CRT_HAVE_svcerr_progvers 1
#define __CRT_HAVE_svcerr_systemerr 1
#define __CRT_HAVE_svcerr_weakauth 1
#define __CRT_HAVE_svcfd_create 1
#define __CRT_HAVE_svcraw_create 1
#define __CRT_HAVE_svctcp_create 1
#define __CRT_HAVE_svcudp_bufcreate 1
#define __CRT_HAVE_svcudp_create 1
#define __CRT_HAVE_svcudp_enablecache 1
#define __CRT_HAVE_svcunix_create 1
#define __CRT_HAVE_svcunixfd_create 1
#define __CRT_HAVE_swab 1
#define __CRT_HAVE_swapcontext 1
#define __CRT_HAVE_swapoff 1
#define __CRT_HAVE_swapon 1
#define __CRT_HAVE_swprintf 1
#define __CRT_HAVE_swscanf 1
#define __CRT_HAVE_symlink 1
#define __CRT_HAVE_symlinkat 1
#define __CRT_HAVE_sync 1
#define __CRT_HAVE_sync_file_range 1
#define __CRT_HAVE_syncfs 1
#define __CRT_HAVE_sys_errlist 1
#define __CRT_HAVE_sys_nerr 1
#define __CRT_HAVE_sys_sigabbrev 1
#define __CRT_HAVE_sys_siglist 1
#define __CRT_HAVE_syscall 1
#define __CRT_HAVE_sysconf 1
#define __CRT_HAVE_sysctl 1
#define __CRT_HAVE_sysinfo 1
#define __CRT_HAVE_syslog 1
#define __CRT_HAVE_system 1
#define __CRT_HAVE_sysv_signal 1
#define __CRT_HAVE_tcdrain 1
#define __CRT_HAVE_tcflow 1
#define __CRT_HAVE_tcflush 1
#define __CRT_HAVE_tcgetattr 1
#define __CRT_HAVE_tcgetpgrp 1
#define __CRT_HAVE_tcgetsid 1
#define __CRT_HAVE_tcsendbreak 1
#define __CRT_HAVE_tcsetattr 1
#define __CRT_HAVE_tcsetpgrp 1
#define __CRT_HAVE_tdelete 1
#define __CRT_HAVE_tdestroy 1
#define __CRT_HAVE_tee 1
#define __CRT_HAVE_telldir 1
#define __CRT_HAVE_tempnam 1
#define __CRT_HAVE_textdomain 1
#define __CRT_HAVE_tfind 1
#define __CRT_HAVE_time 1
#define __CRT_HAVE_timegm 1
#define __CRT_HAVE_timelocal 1
#define __CRT_HAVE_timerfd_create 1
#define __CRT_HAVE_timerfd_gettime 1
#define __CRT_HAVE_timerfd_settime 1
#define __CRT_HAVE_times 1
#define __CRT_HAVE_timespec_get 1
#define __CRT_HAVE_timezone 1
#define __CRT_HAVE_tmpfile 1
#define __CRT_HAVE_tmpfile64 1
#define __CRT_HAVE_tmpnam 1
#define __CRT_HAVE_tmpnam_r 1
#define __CRT_HAVE_toascii 1
#define __CRT_HAVE_tolower 1
#define __CRT_HAVE_tolower_l 1
#define __CRT_HAVE_toupper 1
#define __CRT_HAVE_toupper_l 1
#define __CRT_HAVE_towctrans 1
#define __CRT_HAVE_towctrans_l 1
#define __CRT_HAVE_towlower 1
#define __CRT_HAVE_towlower_l 1
#define __CRT_HAVE_towupper 1
#define __CRT_HAVE_towupper_l 1
#define __CRT_HAVE_tr_break 1
#define __CRT_HAVE_truncate 1
#define __CRT_HAVE_truncate64 1
#define __CRT_HAVE_tsearch 1
#define __CRT_HAVE_ttyname 1
#define __CRT_HAVE_ttyname_r 1
#define __CRT_HAVE_ttyslot 1
#define __CRT_HAVE_twalk 1
#define __CRT_HAVE_tzname 1
#define __CRT_HAVE_tzset 1
#define __CRT_HAVE_ualarm 1
#define __CRT_HAVE_ulckpwdf 1
#define __CRT_HAVE_ulimit 1
#define __CRT_HAVE_umask 1
#define __CRT_HAVE_umount 1
#define __CRT_HAVE_umount2 1
#define __CRT_HAVE_uname 1
#define __CRT_HAVE_ungetc 1
#define __CRT_HAVE_ungetwc 1
#define __CRT_HAVE_unlink 1
#define __CRT_HAVE_unlinkat 1
#define __CRT_HAVE_unlockpt 1
#define __CRT_HAVE_unsetenv 1
#define __CRT_HAVE_unshare 1
#define __CRT_HAVE_updwtmp 1
#define __CRT_HAVE_updwtmpx 1
#define __CRT_HAVE_uselib 1
#define __CRT_HAVE_uselocale 1
#define __CRT_HAVE_user2netname 1
#define __CRT_HAVE_usleep 1
#define __CRT_HAVE_ustat 1
#define __CRT_HAVE_utime 1
#define __CRT_HAVE_utimensat 1
#define __CRT_HAVE_utimes 1
#define __CRT_HAVE_utmpname 1
#define __CRT_HAVE_utmpxname 1
#define __CRT_HAVE_valloc 1
#define __CRT_HAVE_vasprintf 1
#define __CRT_HAVE_vdprintf 1
#define __CRT_HAVE_verr 1
#define __CRT_HAVE_verrx 1
#define __CRT_HAVE_versionsort 1
#define __CRT_HAVE_versionsort64 1
#define __CRT_HAVE_vfork 1
#define __CRT_HAVE_vfprintf 1
#define __CRT_HAVE_vfscanf 1
#define __CRT_HAVE_vfwprintf 1
#define __CRT_HAVE_vfwscanf 1
#define __CRT_HAVE_vhangup 1
#define __CRT_HAVE_vlimit 1
#define __CRT_HAVE_vm86 1
#define __CRT_HAVE_vmsplice 1
#define __CRT_HAVE_vprintf 1
#define __CRT_HAVE_vscanf 1
#define __CRT_HAVE_vsnprintf 1
#define __CRT_HAVE_vsprintf 1
#define __CRT_HAVE_vsscanf 1
#define __CRT_HAVE_vswprintf 1
#define __CRT_HAVE_vswscanf 1
#define __CRT_HAVE_vsyslog 1
#define __CRT_HAVE_vtimes 1
#define __CRT_HAVE_vwarn 1
#define __CRT_HAVE_vwarnx 1
#define __CRT_HAVE_vwprintf 1
#define __CRT_HAVE_vwscanf 1
#define __CRT_HAVE_wait 1
#define __CRT_HAVE_wait3 1
#define __CRT_HAVE_wait4 1
#define __CRT_HAVE_waitid 1
#define __CRT_HAVE_waitpid 1
#define __CRT_HAVE_warn 1
#define __CRT_HAVE_warnx 1
#define __CRT_HAVE_wcpcpy 1
#define __CRT_HAVE_wcpncpy 1
#define __CRT_HAVE_wcrtomb 1
#define __CRT_HAVE_wcscasecmp 1
#define __CRT_HAVE_wcscasecmp_l 1
#define __CRT_HAVE_wcscat 1
#define __CRT_HAVE_wcschr 1
#define __CRT_HAVE_wcschrnul 1
#define __CRT_HAVE_wcscmp 1
#define __CRT_HAVE_wcscoll 1
#define __CRT_HAVE_wcscoll_l 1
#define __CRT_HAVE_wcscpy 1
#define __CRT_HAVE_wcscspn 1
#define __CRT_HAVE_wcsdup 1
#define __CRT_HAVE_wcsftime 1
#define __CRT_HAVE_wcsftime_l 1
#define __CRT_HAVE_wcslen 1
#define __CRT_HAVE_wcsncasecmp 1
#define __CRT_HAVE_wcsncasecmp_l 1
#define __CRT_HAVE_wcsncat 1
#define __CRT_HAVE_wcsncmp 1
#define __CRT_HAVE_wcsncpy 1
#define __CRT_HAVE_wcsnlen 1
#define __CRT_HAVE_wcsnrtombs 1
#define __CRT_HAVE_wcspbrk 1
#define __CRT_HAVE_wcsrchr 1
#define __CRT_HAVE_wcsrtombs 1
#define __CRT_HAVE_wcsspn 1
#define __CRT_HAVE_wcsstr 1
#define __CRT_HAVE_wcstod 1
#define __CRT_HAVE_wcstod_l 1
#define __CRT_HAVE_wcstof 1
#define __CRT_HAVE_wcstof_l 1
#define __CRT_HAVE_wcstoimax 1
#define __CRT_HAVE_wcstok 1
#define __CRT_HAVE_wcstol 1
#define __CRT_HAVE_wcstol_l 1
#define __CRT_HAVE_wcstold 1
#define __CRT_HAVE_wcstold_l 1
#define __CRT_HAVE_wcstoll 1
#define __CRT_HAVE_wcstoll_l 1
#define __CRT_HAVE_wcstombs 1
#define __CRT_HAVE_wcstoq 1
#define __CRT_HAVE_wcstoul 1
#define __CRT_HAVE_wcstoul_l 1
#define __CRT_HAVE_wcstoull 1
#define __CRT_HAVE_wcstoull_l 1
#define __CRT_HAVE_wcstoumax 1
#define __CRT_HAVE_wcstouq 1
#define __CRT_HAVE_wcswcs 1
#define __CRT_HAVE_wcswidth 1
#define __CRT_HAVE_wcsxfrm 1
#define __CRT_HAVE_wcsxfrm_l 1
#define __CRT_HAVE_wctob 1
#define __CRT_HAVE_wctomb 1
#define __CRT_HAVE_wctrans 1
#define __CRT_HAVE_wctrans_l 1
#define __CRT_HAVE_wctype 1
#define __CRT_HAVE_wctype_l 1
#define __CRT_HAVE_wcwidth 1
#define __CRT_HAVE_wmemchr 1
#define __CRT_HAVE_wmemcmp 1
#define __CRT_HAVE_wmemcpy 1
#define __CRT_HAVE_wmemmove 1
#define __CRT_HAVE_wmempcpy 1
#define __CRT_HAVE_wmemset 1
#define __CRT_HAVE_wordexp 1
#define __CRT_HAVE_wordfree 1
#define __CRT_HAVE_wprintf 1
#define __CRT_HAVE_write 1
#define __CRT_HAVE_writev 1
#define __CRT_HAVE_wscanf 1
#define __CRT_HAVE_xdecrypt 1
#define __CRT_HAVE_xdr_accepted_reply 1
#define __CRT_HAVE_xdr_array 1
#define __CRT_HAVE_xdr_authdes_cred 1
#define __CRT_HAVE_xdr_authdes_verf 1
#define __CRT_HAVE_xdr_authunix_parms 1
#define __CRT_HAVE_xdr_bool 1
#define __CRT_HAVE_xdr_bytes 1
#define __CRT_HAVE_xdr_callhdr 1
#define __CRT_HAVE_xdr_callmsg 1
#define __CRT_HAVE_xdr_char 1
#define __CRT_HAVE_xdr_cryptkeyarg 1
#define __CRT_HAVE_xdr_cryptkeyarg2 1
#define __CRT_HAVE_xdr_cryptkeyres 1
#define __CRT_HAVE_xdr_des_block 1
#define __CRT_HAVE_xdr_double 1
#define __CRT_HAVE_xdr_enum 1
#define __CRT_HAVE_xdr_float 1
#define __CRT_HAVE_xdr_free 1
#define __CRT_HAVE_xdr_getcredres 1
#define __CRT_HAVE_xdr_hyper 1
#define __CRT_HAVE_xdr_int 1
#define __CRT_HAVE_xdr_int16_t 1
#define __CRT_HAVE_xdr_int32_t 1
#define __CRT_HAVE_xdr_int64_t 1
#define __CRT_HAVE_xdr_int8_t 1
#define __CRT_HAVE_xdr_key_netstarg 1
#define __CRT_HAVE_xdr_key_netstres 1
#define __CRT_HAVE_xdr_keybuf 1
#define __CRT_HAVE_xdr_keystatus 1
#define __CRT_HAVE_xdr_long 1
#define __CRT_HAVE_xdr_longlong_t 1
#define __CRT_HAVE_xdr_netnamestr 1
#define __CRT_HAVE_xdr_netobj 1
#define __CRT_HAVE_xdr_opaque 1
#define __CRT_HAVE_xdr_opaque_auth 1
#define __CRT_HAVE_xdr_pmap 1
#define __CRT_HAVE_xdr_pmaplist 1
#define __CRT_HAVE_xdr_pointer 1
#define __CRT_HAVE_xdr_quad_t 1
#define __CRT_HAVE_xdr_reference 1
#define __CRT_HAVE_xdr_rejected_reply 1
#define __CRT_HAVE_xdr_replymsg 1
#define __CRT_HAVE_xdr_rmtcall_args 1
#define __CRT_HAVE_xdr_rmtcallres 1
#define __CRT_HAVE_xdr_short 1
#define __CRT_HAVE_xdr_sizeof 1
#define __CRT_HAVE_xdr_string 1
#define __CRT_HAVE_xdr_u_char 1
#define __CRT_HAVE_xdr_u_hyper 1
#define __CRT_HAVE_xdr_u_int 1
#define __CRT_HAVE_xdr_u_long 1
#define __CRT_HAVE_xdr_u_longlong_t 1
#define __CRT_HAVE_xdr_u_quad_t 1
#define __CRT_HAVE_xdr_u_short 1
#define __CRT_HAVE_xdr_uint16_t 1
#define __CRT_HAVE_xdr_uint32_t 1
#define __CRT_HAVE_xdr_uint64_t 1
#define __CRT_HAVE_xdr_uint8_t 1
#define __CRT_HAVE_xdr_union 1
#define __CRT_HAVE_xdr_unixcred 1
#define __CRT_HAVE_xdr_vector 1
#define __CRT_HAVE_xdr_void 1
#define __CRT_HAVE_xdr_wrapstring 1
#define __CRT_HAVE_xdrmem_create 1
#define __CRT_HAVE_xdrrec_create 1
#define __CRT_HAVE_xdrrec_endofrecord 1
#define __CRT_HAVE_xdrrec_eof 1
#define __CRT_HAVE_xdrrec_skiprecord 1
#define __CRT_HAVE_xdrstdio_create 1
#define __CRT_HAVE_xencrypt 1
#define __CRT_HAVE_xprt_register 1
#define __CRT_HAVE_xprt_unregister 1
