/* HASH CRC-32:0x126cca94 */
/* Copyright (c) 2019 Griefer@Work                                            *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement in the product documentation would be  *
 *    appreciated but is not required.                                        *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#ifndef __NR3264COMPAT__sysctl
#define __NR3264COMPAT__sysctl                1
#define __NR3264COMPAT_accept4                1
#define __NR3264COMPAT_access                 1
#define __NR3264COMPAT_acct                   1
#define __NR3264COMPAT_add_key                1
#define __NR3264COMPAT_adjtimex               1
#define __NR3264COMPAT_afs_syscall            1
#define __NR3264COMPAT_alarm                  1
#define __NR3264COMPAT_bind                   1
#define __NR3264COMPAT_bpf                    1
#define __NR3264COMPAT_brk                    1
#define __NR3264COMPAT_capget                 1
#define __NR3264COMPAT_capset                 1
#define __NR3264COMPAT_chdir                  1
#define __NR3264COMPAT_chmod                  1
#define __NR3264COMPAT_chroot                 1
#define __NR3264COMPAT_clock_adjtime          1
#define __NR3264COMPAT_close                  1
#define __NR3264COMPAT_connect                1
#define __NR3264COMPAT_creat                  1
#define __NR3264COMPAT_create_module          1
#define __NR3264COMPAT_delete_module          1
#define __NR3264COMPAT_detach                 1
#define __NR3264COMPAT_dup                    1
#define __NR3264COMPAT_dup2                   1
#define __NR3264COMPAT_dup3                   1
#define __NR3264COMPAT_epoll_create           1
#define __NR3264COMPAT_epoll_create1          1
#define __NR3264COMPAT_epoll_ctl              1
#define __NR3264COMPAT_epoll_pwait            1
#define __NR3264COMPAT_epoll_wait             1
#define __NR3264COMPAT_eventfd                1
#define __NR3264COMPAT_eventfd2               1
#define __NR3264COMPAT_execve                 1
#define __NR3264COMPAT_execveat               1
#define __NR3264COMPAT_exit                   1
#define __NR3264COMPAT_exit_group             1
#define __NR3264COMPAT_faccessat              1
#define __NR3264COMPAT_fadvise64              1
#define __NR3264COMPAT_fallocate              1
#define __NR3264COMPAT_fanotify_init          1
#define __NR3264COMPAT_fanotify_mark          1
#define __NR3264COMPAT_fchdir                 1
#define __NR3264COMPAT_fchdirat               1
#define __NR3264COMPAT_fchmod                 1
#define __NR3264COMPAT_fchmodat               1
#define __NR3264COMPAT_fchownat               1
#define __NR3264COMPAT_fcntl                  1
#define __NR3264COMPAT_fdatasync              1
#define __NR3264COMPAT_fgetxattr              1
#define __NR3264COMPAT_finit_module           1
#define __NR3264COMPAT_flistxattr             1
#define __NR3264COMPAT_flock                  1
#define __NR3264COMPAT_fmkdirat               1
#define __NR3264COMPAT_fmknodat               1
#define __NR3264COMPAT_fork                   1
#define __NR3264COMPAT_freadlinkat            1
#define __NR3264COMPAT_frealpath4             1
#define __NR3264COMPAT_frealpathat            1
#define __NR3264COMPAT_fremovexattr           1
#define __NR3264COMPAT_frenameat              1
#define __NR3264COMPAT_fsetxattr              1
#define __NR3264COMPAT_fsmode                 1
#define __NR3264COMPAT_fstatfs                1
#define __NR3264COMPAT_fsymlinkat             1
#define __NR3264COMPAT_fsync                  1
#define __NR3264COMPAT_ftruncate              1
#define __NR3264COMPAT_get_kernel_syms        1
#define __NR3264COMPAT_get_mempolicy          1
#define __NR3264COMPAT_get_robust_list        1
#define __NR3264COMPAT_get_thread_area        1
#define __NR3264COMPAT_getcpu                 1
#define __NR3264COMPAT_getcwd                 1
#define __NR3264COMPAT_getdents               1
#define __NR3264COMPAT_getdents64             1
#define __NR3264COMPAT_getdrives              1
#define __NR3264COMPAT_getitimer              1
#define __NR3264COMPAT_getpeername            1
#define __NR3264COMPAT_getpgid                1
#define __NR3264COMPAT_getpgrp                1
#define __NR3264COMPAT_getpid                 1
#define __NR3264COMPAT_getpmsg                1
#define __NR3264COMPAT_getppid                1
#define __NR3264COMPAT_getpriority            1
#define __NR3264COMPAT_getrandom              1
#define __NR3264COMPAT_getrlimit              1
#define __NR3264COMPAT_getrusage              1
#define __NR3264COMPAT_getsid                 1
#define __NR3264COMPAT_getsockname            1
#define __NR3264COMPAT_getsockopt             1
#define __NR3264COMPAT_gettid                 1
#define __NR3264COMPAT_getxattr               1
#define __NR3264COMPAT_hop                    1
#define __NR3264COMPAT_hopf                   1
#define __NR3264COMPAT_init_module            1
#define __NR3264COMPAT_inotify_add_watch      1
#define __NR3264COMPAT_inotify_init           1
#define __NR3264COMPAT_inotify_init1          1
#define __NR3264COMPAT_inotify_rm_watch       1
#define __NR3264COMPAT_io_cancel              1
#define __NR3264COMPAT_io_destroy             1
#define __NR3264COMPAT_io_getevents           1
#define __NR3264COMPAT_io_setup               1
#define __NR3264COMPAT_io_submit              1
#define __NR3264COMPAT_ioctl                  1
#define __NR3264COMPAT_ioctlf                 1
#define __NR3264COMPAT_ioperm                 1
#define __NR3264COMPAT_iopl                   1
#define __NR3264COMPAT_ioprio_get             1
#define __NR3264COMPAT_ioprio_set             1
#define __NR3264COMPAT_kcmp                   1
#define __NR3264COMPAT_kexec_load             1
#define __NR3264COMPAT_keyctl                 1
#define __NR3264COMPAT_kfstat                 1
#define __NR3264COMPAT_kfstatat               1
#define __NR3264COMPAT_kill                   1
#define __NR3264COMPAT_klstat                 1
#define __NR3264COMPAT_kreaddir               1
#define __NR3264COMPAT_kreaddirf              1
#define __NR3264COMPAT_kstat                  1
#define __NR3264COMPAT_ksysctl                1
#define __NR3264COMPAT_lgetxattr              1
#define __NR3264COMPAT_link                   1
#define __NR3264COMPAT_linkat                 1
#define __NR3264COMPAT_linux_fstat64          1
#define __NR3264COMPAT_linux_lstat64          1
#define __NR3264COMPAT_linux_stat64           1
#define __NR3264COMPAT_listen                 1
#define __NR3264COMPAT_listxattr              1
#define __NR3264COMPAT_llistxattr             1
#define __NR3264COMPAT_lookup_dcookie         1
#define __NR3264COMPAT_lremovexattr           1
#define __NR3264COMPAT_lseek64                1
#define __NR3264COMPAT_lsetxattr              1
#define __NR3264COMPAT_madvise                1
#define __NR3264COMPAT_maplibrary             1
#define __NR3264COMPAT_mbind                  1
#define __NR3264COMPAT_membarrier             1
#define __NR3264COMPAT_memfd_create           1
#define __NR3264COMPAT_migrate_pages          1
#define __NR3264COMPAT_mincore                1
#define __NR3264COMPAT_mkdir                  1
#define __NR3264COMPAT_mkdirat                1
#define __NR3264COMPAT_mknod                  1
#define __NR3264COMPAT_mknodat                1
#define __NR3264COMPAT_mktty                  1
#define __NR3264COMPAT_mlock                  1
#define __NR3264COMPAT_mlock2                 1
#define __NR3264COMPAT_mlockall               1
#define __NR3264COMPAT_mmap                   1
#define __NR3264COMPAT_modify_ldt             1
#define __NR3264COMPAT_mount                  1
#define __NR3264COMPAT_move_pages             1
#define __NR3264COMPAT_mprotect               1
#define __NR3264COMPAT_mq_getsetattr          1
#define __NR3264COMPAT_mq_notify              1
#define __NR3264COMPAT_mq_open                1
#define __NR3264COMPAT_mq_unlink              1
#define __NR3264COMPAT_mremap                 1
#define __NR3264COMPAT_msync                  1
#define __NR3264COMPAT_munlock                1
#define __NR3264COMPAT_munlockall             1
#define __NR3264COMPAT_munmap                 1
#define __NR3264COMPAT_name_to_handle_at      1
#define __NR3264COMPAT_nfsservctl             1
#define __NR3264COMPAT_open                   1
#define __NR3264COMPAT_open_by_handle_at      1
#define __NR3264COMPAT_openat                 1
#define __NR3264COMPAT_openpty                1
#define __NR3264COMPAT_pause                  1
#define __NR3264COMPAT_perf_event_open        1
#define __NR3264COMPAT_personality            1
#define __NR3264COMPAT_pipe                   1
#define __NR3264COMPAT_pipe2                  1
#define __NR3264COMPAT_pivot_root             1
#define __NR3264COMPAT_poll                   1
#define __NR3264COMPAT_prctl                  1
#define __NR3264COMPAT_pread64                1
#define __NR3264COMPAT_pread64f               1
#define __NR3264COMPAT_prlimit64              1
#define __NR3264COMPAT_ptrace                 1
#define __NR3264COMPAT_putpmsg                1
#define __NR3264COMPAT_pwrite64               1
#define __NR3264COMPAT_pwrite64f              1
#define __NR3264COMPAT_query_module           1
#define __NR3264COMPAT_quotactl               1
#define __NR3264COMPAT_read                   1
#define __NR3264COMPAT_readahead              1
#define __NR3264COMPAT_readf                  1
#define __NR3264COMPAT_readlink               1
#define __NR3264COMPAT_readlinkat             1
#define __NR3264COMPAT_reboot                 1
#define __NR3264COMPAT_recvfrom               1
#define __NR3264COMPAT_recvmsg                1
#define __NR3264COMPAT_remap_file_pages       1
#define __NR3264COMPAT_removexattr            1
#define __NR3264COMPAT_rename                 1
#define __NR3264COMPAT_renameat               1
#define __NR3264COMPAT_renameat2              1
#define __NR3264COMPAT_request_key            1
#define __NR3264COMPAT_restart_syscall        1
#define __NR3264COMPAT_rmdir                  1
#define __NR3264COMPAT_rpc_service            1
#define __NR3264COMPAT_rt_sigaction           1
#define __NR3264COMPAT_rt_sigpending          1
#define __NR3264COMPAT_rt_sigprocmask         1
#define __NR3264COMPAT_rt_sigreturn           1
#define __NR3264COMPAT_rt_sigsuspend          1
#define __NR3264COMPAT_sched_get_priority_max 1
#define __NR3264COMPAT_sched_get_priority_min 1
#define __NR3264COMPAT_sched_getaffinity      1
#define __NR3264COMPAT_sched_getattr          1
#define __NR3264COMPAT_sched_getparam         1
#define __NR3264COMPAT_sched_getscheduler     1
#define __NR3264COMPAT_sched_setaffinity      1
#define __NR3264COMPAT_sched_setattr          1
#define __NR3264COMPAT_sched_setparam         1
#define __NR3264COMPAT_sched_setscheduler     1
#define __NR3264COMPAT_sched_yield            1
#define __NR3264COMPAT_seccomp                1
#define __NR3264COMPAT_sendfile               1
#define __NR3264COMPAT_sendmmsg               1
#define __NR3264COMPAT_sendmsg                1
#define __NR3264COMPAT_sendto                 1
#define __NR3264COMPAT_set_mempolicy          1
#define __NR3264COMPAT_set_robust_list        1
#define __NR3264COMPAT_set_thread_area        1
#define __NR3264COMPAT_set_tid_address        1
#define __NR3264COMPAT_setdomainname          1
#define __NR3264COMPAT_sethostname            1
#define __NR3264COMPAT_setitimer              1
#define __NR3264COMPAT_setns                  1
#define __NR3264COMPAT_setpgid                1
#define __NR3264COMPAT_setpriority            1
#define __NR3264COMPAT_setrlimit              1
#define __NR3264COMPAT_setsid                 1
#define __NR3264COMPAT_setsockopt             1
#define __NR3264COMPAT_setxattr               1
#define __NR3264COMPAT_shutdown               1
#define __NR3264COMPAT_sigaltstack            1
#define __NR3264COMPAT_signalfd               1
#define __NR3264COMPAT_signalfd4              1
#define __NR3264COMPAT_socket                 1
#define __NR3264COMPAT_socketpair             1
#define __NR3264COMPAT_splice                 1
#define __NR3264COMPAT_statfs                 1
#define __NR3264COMPAT_swapoff                1
#define __NR3264COMPAT_swapon                 1
#define __NR3264COMPAT_symlink                1
#define __NR3264COMPAT_symlinkat              1
#define __NR3264COMPAT_sync                   1
#define __NR3264COMPAT_sync_file_range        1
#define __NR3264COMPAT_syncfs                 1
#define __NR3264COMPAT_sysfs                  1
#define __NR3264COMPAT_sysinfo                1
#define __NR3264COMPAT_syslog                 1
#define __NR3264COMPAT_tee                    1
#define __NR3264COMPAT_tgkill                 1
#define __NR3264COMPAT_time                   1
#define __NR3264COMPAT_timer_create           1
#define __NR3264COMPAT_timer_delete           1
#define __NR3264COMPAT_timer_getoverrun       1
#define __NR3264COMPAT_timerfd_create         1
#define __NR3264COMPAT_times                  1
#define __NR3264COMPAT_tkill                  1
#define __NR3264COMPAT_truncate               1
#define __NR3264COMPAT_umask                  1
#define __NR3264COMPAT_umount2                1
#define __NR3264COMPAT_uname                  1
#define __NR3264COMPAT_unlink                 1
#define __NR3264COMPAT_unlinkat               1
#define __NR3264COMPAT_unshare                1
#define __NR3264COMPAT_uselib                 1
#define __NR3264COMPAT_userfaultfd            1
#define __NR3264COMPAT_ustat                  1
#define __NR3264COMPAT_utime                  1
#define __NR3264COMPAT_vfork                  1
#define __NR3264COMPAT_vhangup                1
#define __NR3264COMPAT_vserver                1
#define __NR3264COMPAT_wait4                  1
#define __NR3264COMPAT_write                  1
#define __NR3264COMPAT_writef                 1
#endif /* !__NR3264COMPAT__sysctl */
