/* HASH CRC-32:0x88035e66 */
/* Copyright (c) 2019 Griefer@Work                                            *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement in the product documentation would be  *
 *    appreciated but is not required.                                        *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#define __CRT_HAVE_sys__sysctl 1
#define __CRT_HAVE_sys_accept 1
#define __CRT_HAVE_sys_accept4 1
#define __CRT_HAVE_sys_access 1
#define __CRT_HAVE_sys_acct 1
#define __CRT_HAVE_sys_add_key 1
#define __CRT_HAVE_sys_adjtimex 1
#define __CRT_HAVE_sys_alarm 1
#define __CRT_HAVE_sys_bdflush 1
#define __CRT_HAVE_sys_bind 1
#define __CRT_HAVE_sys_bpf 1
#define __CRT_HAVE_sys_brk 1
#define __CRT_HAVE_sys_capget 1
#define __CRT_HAVE_sys_capset 1
#define __CRT_HAVE_sys_chdir 1
#define __CRT_HAVE_sys_chmod 1
#define __CRT_HAVE_sys_chown 1
#define __CRT_HAVE_sys_chroot 1
#define __CRT_HAVE_sys_clock_adjtime 1
#define __CRT_HAVE_sys_clock_getres 1
#define __CRT_HAVE_sys_clock_gettime 1
#define __CRT_HAVE_sys_clock_nanosleep 1
#define __CRT_HAVE_sys_clock_settime 1
#define __CRT_HAVE_sys_clone 1
#define __CRT_HAVE_sys_close 1
#define __CRT_HAVE_sys_connect 1
#define __CRT_HAVE_sys_creat 1
#define __CRT_HAVE_sys_delete_module 1
#define __CRT_HAVE_sys_dup 1
#define __CRT_HAVE_sys_dup2 1
#define __CRT_HAVE_sys_dup3 1
#define __CRT_HAVE_sys_epoll_create 1
#define __CRT_HAVE_sys_epoll_create1 1
#define __CRT_HAVE_sys_epoll_ctl 1
#define __CRT_HAVE_sys_epoll_pwait 1
#define __CRT_HAVE_sys_epoll_wait 1
#define __CRT_HAVE_sys_eventfd 1
#define __CRT_HAVE_sys_eventfd2 1
#define __CRT_HAVE_sys_execve 1
#define __CRT_HAVE_sys_execveat 1
#define __CRT_HAVE_sys_exit 1
#define __CRT_HAVE_sys_exit_group 1
#define __CRT_HAVE_sys_faccessat 1
#define __CRT_HAVE_sys_fadvise64 1
#define __CRT_HAVE_sys_fallocate 1
#define __CRT_HAVE_sys_fanotify_init 1
#define __CRT_HAVE_sys_fanotify_mark 1
#define __CRT_HAVE_sys_fchdir 1
#define __CRT_HAVE_sys_fchmod 1
#define __CRT_HAVE_sys_fchmodat 1
#define __CRT_HAVE_sys_fchown 1
#define __CRT_HAVE_sys_fchownat 1
#define __CRT_HAVE_sys_fcntl 1
#define __CRT_HAVE_sys_fdatasync 1
#define __CRT_HAVE_sys_fgetxattr 1
#define __CRT_HAVE_sys_finit_module 1
#define __CRT_HAVE_sys_flistxattr 1
#define __CRT_HAVE_sys_flock 1
#define __CRT_HAVE_sys_fork 1
#define __CRT_HAVE_sys_fremovexattr 1
#define __CRT_HAVE_sys_fsetxattr 1
#define __CRT_HAVE_sys_fstatfs 1
#define __CRT_HAVE_sys_fsync 1
#define __CRT_HAVE_sys_ftruncate 1
#define __CRT_HAVE_sys_futex 1
#define __CRT_HAVE_sys_futimesat 1
#define __CRT_HAVE_sys_get_mempolicy 1
#define __CRT_HAVE_sys_get_robust_list 1
#define __CRT_HAVE_sys_getcpu 1
#define __CRT_HAVE_sys_getcwd 1
#define __CRT_HAVE_sys_getdents 1
#define __CRT_HAVE_sys_getdents64 1
#define __CRT_HAVE_sys_getegid 1
#define __CRT_HAVE_sys_geteuid 1
#define __CRT_HAVE_sys_getgid 1
#define __CRT_HAVE_sys_getgroups 1
#define __CRT_HAVE_sys_getitimer 1
#define __CRT_HAVE_sys_getpeername 1
#define __CRT_HAVE_sys_getpgid 1
#define __CRT_HAVE_sys_getpgrp 1
#define __CRT_HAVE_sys_getpid 1
#define __CRT_HAVE_sys_getppid 1
#define __CRT_HAVE_sys_getpriority 1
#define __CRT_HAVE_sys_getrandom 1
#define __CRT_HAVE_sys_getresgid 1
#define __CRT_HAVE_sys_getresuid 1
#define __CRT_HAVE_sys_getrlimit 1
#define __CRT_HAVE_sys_getrusage 1
#define __CRT_HAVE_sys_getsid 1
#define __CRT_HAVE_sys_getsockname 1
#define __CRT_HAVE_sys_getsockopt 1
#define __CRT_HAVE_sys_gettid 1
#define __CRT_HAVE_sys_gettimeofday 1
#define __CRT_HAVE_sys_getuid 1
#define __CRT_HAVE_sys_getxattr 1
#define __CRT_HAVE_sys_init_module 1
#define __CRT_HAVE_sys_inotify_add_watch 1
#define __CRT_HAVE_sys_inotify_init 1
#define __CRT_HAVE_sys_inotify_init1 1
#define __CRT_HAVE_sys_inotify_rm_watch 1
#define __CRT_HAVE_sys_io_cancel 1
#define __CRT_HAVE_sys_io_destroy 1
#define __CRT_HAVE_sys_io_getevents 1
#define __CRT_HAVE_sys_io_setup 1
#define __CRT_HAVE_sys_io_submit 1
#define __CRT_HAVE_sys_ioctl 1
#define __CRT_HAVE_sys_ioprio_get 1
#define __CRT_HAVE_sys_ioprio_set 1
#define __CRT_HAVE_sys_kcmp 1
#define __CRT_HAVE_sys_kexec_load 1
#define __CRT_HAVE_sys_keyctl 1
#define __CRT_HAVE_sys_kill 1
#define __CRT_HAVE_sys_lchown 1
#define __CRT_HAVE_sys_lgetxattr 1
#define __CRT_HAVE_sys_link 1
#define __CRT_HAVE_sys_linkat 1
#define __CRT_HAVE_sys_linux_fstat32 1
#define __CRT_HAVE_sys_linux_lstat32 1
#define __CRT_HAVE_sys_linux_newfstatat 1
#define __CRT_HAVE_sys_linux_stat32 1
#define __CRT_HAVE_sys_listen 1
#define __CRT_HAVE_sys_listxattr 1
#define __CRT_HAVE_sys_llistxattr 1
#define __CRT_HAVE_sys_lookup_dcookie 1
#define __CRT_HAVE_sys_lremovexattr 1
#define __CRT_HAVE_sys_lseek 1
#define __CRT_HAVE_sys_lsetxattr 1
#define __CRT_HAVE_sys_madvise 1
#define __CRT_HAVE_sys_mbind 1
#define __CRT_HAVE_sys_membarrier 1
#define __CRT_HAVE_sys_memfd_create 1
#define __CRT_HAVE_sys_migrate_pages 1
#define __CRT_HAVE_sys_mincore 1
#define __CRT_HAVE_sys_mkdir 1
#define __CRT_HAVE_sys_mkdirat 1
#define __CRT_HAVE_sys_mknod 1
#define __CRT_HAVE_sys_mknodat 1
#define __CRT_HAVE_sys_mlock 1
#define __CRT_HAVE_sys_mlock2 1
#define __CRT_HAVE_sys_mlockall 1
#define __CRT_HAVE_sys_mmap 1
#define __CRT_HAVE_sys_mount 1
#define __CRT_HAVE_sys_move_pages 1
#define __CRT_HAVE_sys_mprotect 1
#define __CRT_HAVE_sys_mq_getsetattr 1
#define __CRT_HAVE_sys_mq_notify 1
#define __CRT_HAVE_sys_mq_open 1
#define __CRT_HAVE_sys_mq_timedreceive 1
#define __CRT_HAVE_sys_mq_timedsend 1
#define __CRT_HAVE_sys_mq_unlink 1
#define __CRT_HAVE_sys_mremap 1
#define __CRT_HAVE_sys_msgctl 1
#define __CRT_HAVE_sys_msgget 1
#define __CRT_HAVE_sys_msgrcv 1
#define __CRT_HAVE_sys_msgsnd 1
#define __CRT_HAVE_sys_msync 1
#define __CRT_HAVE_sys_munlock 1
#define __CRT_HAVE_sys_munlockall 1
#define __CRT_HAVE_sys_munmap 1
#define __CRT_HAVE_sys_name_to_handle_at 1
#define __CRT_HAVE_sys_nanosleep 1
#define __CRT_HAVE_sys_nfsservctl 1
#define __CRT_HAVE_sys_oldwait4 1
#define __CRT_HAVE_sys_open 1
#define __CRT_HAVE_sys_open_by_handle_at 1
#define __CRT_HAVE_sys_openat 1
#define __CRT_HAVE_sys_pause 1
#define __CRT_HAVE_sys_perf_event_open 1
#define __CRT_HAVE_sys_personality 1
#define __CRT_HAVE_sys_pipe 1
#define __CRT_HAVE_sys_pipe2 1
#define __CRT_HAVE_sys_pivot_root 1
#define __CRT_HAVE_sys_poll 1
#define __CRT_HAVE_sys_ppoll 1
#define __CRT_HAVE_sys_prctl 1
#define __CRT_HAVE_sys_pread64 1
#define __CRT_HAVE_sys_preadv 1
#define __CRT_HAVE_sys_prlimit64 1
#define __CRT_HAVE_sys_process_vm_readv 1
#define __CRT_HAVE_sys_process_vm_writev 1
#define __CRT_HAVE_sys_pselect6 1
#define __CRT_HAVE_sys_ptrace 1
#define __CRT_HAVE_sys_pwrite64 1
#define __CRT_HAVE_sys_pwritev 1
#define __CRT_HAVE_sys_quotactl 1
#define __CRT_HAVE_sys_read 1
#define __CRT_HAVE_sys_readahead 1
#define __CRT_HAVE_sys_readlink 1
#define __CRT_HAVE_sys_readlinkat 1
#define __CRT_HAVE_sys_readv 1
#define __CRT_HAVE_sys_reboot 1
#define __CRT_HAVE_sys_recv 1
#define __CRT_HAVE_sys_recvfrom 1
#define __CRT_HAVE_sys_recvmmsg 1
#define __CRT_HAVE_sys_recvmsg 1
#define __CRT_HAVE_sys_remap_file_pages 1
#define __CRT_HAVE_sys_removexattr 1
#define __CRT_HAVE_sys_rename 1
#define __CRT_HAVE_sys_renameat 1
#define __CRT_HAVE_sys_renameat2 1
#define __CRT_HAVE_sys_request_key 1
#define __CRT_HAVE_sys_restart_syscall 1
#define __CRT_HAVE_sys_rmdir 1
#define __CRT_HAVE_sys_rt_sigaction 1
#define __CRT_HAVE_sys_rt_sigpending 1
#define __CRT_HAVE_sys_rt_sigprocmask 1
#define __CRT_HAVE_sys_rt_sigqueueinfo 1
#define __CRT_HAVE_sys_rt_sigreturn 1
#define __CRT_HAVE_sys_rt_sigsuspend 1
#define __CRT_HAVE_sys_rt_sigtimedwait 1
#define __CRT_HAVE_sys_rt_tgsigqueueinfo 1
#define __CRT_HAVE_sys_sched_get_priority_max 1
#define __CRT_HAVE_sys_sched_get_priority_min 1
#define __CRT_HAVE_sys_sched_getaffinity 1
#define __CRT_HAVE_sys_sched_getattr 1
#define __CRT_HAVE_sys_sched_getparam 1
#define __CRT_HAVE_sys_sched_getscheduler 1
#define __CRT_HAVE_sys_sched_rr_get_interval 1
#define __CRT_HAVE_sys_sched_setaffinity 1
#define __CRT_HAVE_sys_sched_setattr 1
#define __CRT_HAVE_sys_sched_setparam 1
#define __CRT_HAVE_sys_sched_setscheduler 1
#define __CRT_HAVE_sys_sched_yield 1
#define __CRT_HAVE_sys_seccomp 1
#define __CRT_HAVE_sys_select 1
#define __CRT_HAVE_sys_semctl 1
#define __CRT_HAVE_sys_semget 1
#define __CRT_HAVE_sys_semop 1
#define __CRT_HAVE_sys_semtimedop 1
#define __CRT_HAVE_sys_send 1
#define __CRT_HAVE_sys_sendfile 1
#define __CRT_HAVE_sys_sendmmsg 1
#define __CRT_HAVE_sys_sendmsg 1
#define __CRT_HAVE_sys_sendto 1
#define __CRT_HAVE_sys_set_mempolicy 1
#define __CRT_HAVE_sys_set_robust_list 1
#define __CRT_HAVE_sys_set_tid_address 1
#define __CRT_HAVE_sys_setdomainname 1
#define __CRT_HAVE_sys_setfsgid 1
#define __CRT_HAVE_sys_setfsuid 1
#define __CRT_HAVE_sys_setgid 1
#define __CRT_HAVE_sys_setgroups 1
#define __CRT_HAVE_sys_sethostname 1
#define __CRT_HAVE_sys_setitimer 1
#define __CRT_HAVE_sys_setns 1
#define __CRT_HAVE_sys_setpgid 1
#define __CRT_HAVE_sys_setpriority 1
#define __CRT_HAVE_sys_setregid 1
#define __CRT_HAVE_sys_setresgid 1
#define __CRT_HAVE_sys_setresuid 1
#define __CRT_HAVE_sys_setreuid 1
#define __CRT_HAVE_sys_setrlimit 1
#define __CRT_HAVE_sys_setsid 1
#define __CRT_HAVE_sys_setsockopt 1
#define __CRT_HAVE_sys_settimeofday 1
#define __CRT_HAVE_sys_setuid 1
#define __CRT_HAVE_sys_setxattr 1
#define __CRT_HAVE_sys_shmat 1
#define __CRT_HAVE_sys_shmctl 1
#define __CRT_HAVE_sys_shmdt 1
#define __CRT_HAVE_sys_shmget 1
#define __CRT_HAVE_sys_shutdown 1
#define __CRT_HAVE_sys_sigaltstack 1
#define __CRT_HAVE_sys_signalfd 1
#define __CRT_HAVE_sys_signalfd4 1
#define __CRT_HAVE_sys_socket 1
#define __CRT_HAVE_sys_socketpair 1
#define __CRT_HAVE_sys_splice 1
#define __CRT_HAVE_sys_statfs 1
#define __CRT_HAVE_sys_swapoff 1
#define __CRT_HAVE_sys_swapon 1
#define __CRT_HAVE_sys_symlink 1
#define __CRT_HAVE_sys_symlinkat 1
#define __CRT_HAVE_sys_sync 1
#define __CRT_HAVE_sys_sync_file_range 1
#define __CRT_HAVE_sys_syncfs 1
#define __CRT_HAVE_sys_sysinfo 1
#define __CRT_HAVE_sys_syslog 1
#define __CRT_HAVE_sys_tee 1
#define __CRT_HAVE_sys_tgkill 1
#define __CRT_HAVE_sys_time 1
#define __CRT_HAVE_sys_timer_create 1
#define __CRT_HAVE_sys_timer_delete 1
#define __CRT_HAVE_sys_timer_getoverrun 1
#define __CRT_HAVE_sys_timer_gettime 1
#define __CRT_HAVE_sys_timer_settime 1
#define __CRT_HAVE_sys_timerfd_create 1
#define __CRT_HAVE_sys_timerfd_gettime 1
#define __CRT_HAVE_sys_timerfd_settime 1
#define __CRT_HAVE_sys_times 1
#define __CRT_HAVE_sys_tkill 1
#define __CRT_HAVE_sys_truncate 1
#define __CRT_HAVE_sys_umask 1
#define __CRT_HAVE_sys_umount 1
#define __CRT_HAVE_sys_umount2 1
#define __CRT_HAVE_sys_uname 1
#define __CRT_HAVE_sys_unlink 1
#define __CRT_HAVE_sys_unlinkat 1
#define __CRT_HAVE_sys_unshare 1
#define __CRT_HAVE_sys_uselib 1
#define __CRT_HAVE_sys_userfaultfd 1
#define __CRT_HAVE_sys_ustat 1
#define __CRT_HAVE_sys_utime 1
#define __CRT_HAVE_sys_utimensat 1
#define __CRT_HAVE_sys_utimes 1
#define __CRT_HAVE_sys_vfork 1
#define __CRT_HAVE_sys_vhangup 1
#define __CRT_HAVE_sys_vmsplice 1
#define __CRT_HAVE_sys_wait4 1
#define __CRT_HAVE_sys_waitid 1
#define __CRT_HAVE_sys_write 1
#define __CRT_HAVE_sys_writev 1
#define __CRT_HAVE_sys_X_sysctl 1
#define __CRT_HAVE_sys_Xaccept 1
#define __CRT_HAVE_sys_Xaccept4 1
#define __CRT_HAVE_sys_Xaccess 1
#define __CRT_HAVE_sys_Xacct 1
#define __CRT_HAVE_sys_Xadd_key 1
#define __CRT_HAVE_sys_Xadjtimex 1
#define __CRT_HAVE_sys_Xalarm 1
#define __CRT_HAVE_sys_Xbdflush 1
#define __CRT_HAVE_sys_Xbind 1
#define __CRT_HAVE_sys_Xbpf 1
#define __CRT_HAVE_sys_Xbrk 1
#define __CRT_HAVE_sys_Xcapget 1
#define __CRT_HAVE_sys_Xcapset 1
#define __CRT_HAVE_sys_Xchdir 1
#define __CRT_HAVE_sys_Xchmod 1
#define __CRT_HAVE_sys_Xchown 1
#define __CRT_HAVE_sys_Xchroot 1
#define __CRT_HAVE_sys_Xclock_adjtime 1
#define __CRT_HAVE_sys_Xclock_getres 1
#define __CRT_HAVE_sys_Xclock_gettime 1
#define __CRT_HAVE_sys_Xclock_nanosleep 1
#define __CRT_HAVE_sys_Xclock_settime 1
#define __CRT_HAVE_sys_Xclone 1
#define __CRT_HAVE_sys_Xclose 1
#define __CRT_HAVE_sys_Xconnect 1
#define __CRT_HAVE_sys_Xcreat 1
#define __CRT_HAVE_sys_Xdelete_module 1
#define __CRT_HAVE_sys_Xdup 1
#define __CRT_HAVE_sys_Xdup2 1
#define __CRT_HAVE_sys_Xdup3 1
#define __CRT_HAVE_sys_Xepoll_create 1
#define __CRT_HAVE_sys_Xepoll_create1 1
#define __CRT_HAVE_sys_Xepoll_ctl 1
#define __CRT_HAVE_sys_Xepoll_pwait 1
#define __CRT_HAVE_sys_Xepoll_wait 1
#define __CRT_HAVE_sys_Xeventfd 1
#define __CRT_HAVE_sys_Xeventfd2 1
#define __CRT_HAVE_sys_Xexecve 1
#define __CRT_HAVE_sys_Xexecveat 1
#define __CRT_HAVE_sys_Xexit 1
#define __CRT_HAVE_sys_Xexit_group 1
#define __CRT_HAVE_sys_Xfaccessat 1
#define __CRT_HAVE_sys_Xfadvise64 1
#define __CRT_HAVE_sys_Xfallocate 1
#define __CRT_HAVE_sys_Xfanotify_init 1
#define __CRT_HAVE_sys_Xfanotify_mark 1
#define __CRT_HAVE_sys_Xfchdir 1
#define __CRT_HAVE_sys_Xfchmod 1
#define __CRT_HAVE_sys_Xfchmodat 1
#define __CRT_HAVE_sys_Xfchown 1
#define __CRT_HAVE_sys_Xfchownat 1
#define __CRT_HAVE_sys_Xfcntl 1
#define __CRT_HAVE_sys_Xfdatasync 1
#define __CRT_HAVE_sys_Xfgetxattr 1
#define __CRT_HAVE_sys_Xfinit_module 1
#define __CRT_HAVE_sys_Xflistxattr 1
#define __CRT_HAVE_sys_Xflock 1
#define __CRT_HAVE_sys_Xfork 1
#define __CRT_HAVE_sys_Xfremovexattr 1
#define __CRT_HAVE_sys_Xfsetxattr 1
#define __CRT_HAVE_sys_Xfstatfs 1
#define __CRT_HAVE_sys_Xfsync 1
#define __CRT_HAVE_sys_Xftruncate 1
#define __CRT_HAVE_sys_Xfutex 1
#define __CRT_HAVE_sys_Xfutimesat 1
#define __CRT_HAVE_sys_Xget_mempolicy 1
#define __CRT_HAVE_sys_Xget_robust_list 1
#define __CRT_HAVE_sys_Xgetcpu 1
#define __CRT_HAVE_sys_Xgetcwd 1
#define __CRT_HAVE_sys_Xgetdents 1
#define __CRT_HAVE_sys_Xgetdents64 1
#define __CRT_HAVE_sys_Xgetegid 1
#define __CRT_HAVE_sys_Xgeteuid 1
#define __CRT_HAVE_sys_Xgetgid 1
#define __CRT_HAVE_sys_Xgetgroups 1
#define __CRT_HAVE_sys_Xgetitimer 1
#define __CRT_HAVE_sys_Xgetpeername 1
#define __CRT_HAVE_sys_Xgetpgid 1
#define __CRT_HAVE_sys_Xgetpgrp 1
#define __CRT_HAVE_sys_Xgetpid 1
#define __CRT_HAVE_sys_Xgetppid 1
#define __CRT_HAVE_sys_Xgetpriority 1
#define __CRT_HAVE_sys_Xgetrandom 1
#define __CRT_HAVE_sys_Xgetresgid 1
#define __CRT_HAVE_sys_Xgetresuid 1
#define __CRT_HAVE_sys_Xgetrlimit 1
#define __CRT_HAVE_sys_Xgetrusage 1
#define __CRT_HAVE_sys_Xgetsid 1
#define __CRT_HAVE_sys_Xgetsockname 1
#define __CRT_HAVE_sys_Xgetsockopt 1
#define __CRT_HAVE_sys_Xgettid 1
#define __CRT_HAVE_sys_Xgettimeofday 1
#define __CRT_HAVE_sys_Xgetuid 1
#define __CRT_HAVE_sys_Xgetxattr 1
#define __CRT_HAVE_sys_Xinit_module 1
#define __CRT_HAVE_sys_Xinotify_add_watch 1
#define __CRT_HAVE_sys_Xinotify_init 1
#define __CRT_HAVE_sys_Xinotify_init1 1
#define __CRT_HAVE_sys_Xinotify_rm_watch 1
#define __CRT_HAVE_sys_Xio_cancel 1
#define __CRT_HAVE_sys_Xio_destroy 1
#define __CRT_HAVE_sys_Xio_getevents 1
#define __CRT_HAVE_sys_Xio_setup 1
#define __CRT_HAVE_sys_Xio_submit 1
#define __CRT_HAVE_sys_Xioctl 1
#define __CRT_HAVE_sys_Xioprio_get 1
#define __CRT_HAVE_sys_Xioprio_set 1
#define __CRT_HAVE_sys_Xkcmp 1
#define __CRT_HAVE_sys_Xkexec_load 1
#define __CRT_HAVE_sys_Xkeyctl 1
#define __CRT_HAVE_sys_Xkill 1
#define __CRT_HAVE_sys_Xlchown 1
#define __CRT_HAVE_sys_Xlgetxattr 1
#define __CRT_HAVE_sys_Xlink 1
#define __CRT_HAVE_sys_Xlinkat 1
#define __CRT_HAVE_sys_Xlinux_fstat32 1
#define __CRT_HAVE_sys_Xlinux_lstat32 1
#define __CRT_HAVE_sys_Xlinux_newfstatat 1
#define __CRT_HAVE_sys_Xlinux_stat32 1
#define __CRT_HAVE_sys_Xlisten 1
#define __CRT_HAVE_sys_Xlistxattr 1
#define __CRT_HAVE_sys_Xllistxattr 1
#define __CRT_HAVE_sys_Xlookup_dcookie 1
#define __CRT_HAVE_sys_Xlremovexattr 1
#define __CRT_HAVE_sys_Xlseek 1
#define __CRT_HAVE_sys_Xlsetxattr 1
#define __CRT_HAVE_sys_Xmadvise 1
#define __CRT_HAVE_sys_Xmbind 1
#define __CRT_HAVE_sys_Xmembarrier 1
#define __CRT_HAVE_sys_Xmemfd_create 1
#define __CRT_HAVE_sys_Xmigrate_pages 1
#define __CRT_HAVE_sys_Xmincore 1
#define __CRT_HAVE_sys_Xmkdir 1
#define __CRT_HAVE_sys_Xmkdirat 1
#define __CRT_HAVE_sys_Xmknod 1
#define __CRT_HAVE_sys_Xmknodat 1
#define __CRT_HAVE_sys_Xmlock 1
#define __CRT_HAVE_sys_Xmlock2 1
#define __CRT_HAVE_sys_Xmlockall 1
#define __CRT_HAVE_sys_Xmmap 1
#define __CRT_HAVE_sys_Xmount 1
#define __CRT_HAVE_sys_Xmove_pages 1
#define __CRT_HAVE_sys_Xmprotect 1
#define __CRT_HAVE_sys_Xmq_getsetattr 1
#define __CRT_HAVE_sys_Xmq_notify 1
#define __CRT_HAVE_sys_Xmq_open 1
#define __CRT_HAVE_sys_Xmq_timedreceive 1
#define __CRT_HAVE_sys_Xmq_timedsend 1
#define __CRT_HAVE_sys_Xmq_unlink 1
#define __CRT_HAVE_sys_Xmremap 1
#define __CRT_HAVE_sys_Xmsgctl 1
#define __CRT_HAVE_sys_Xmsgget 1
#define __CRT_HAVE_sys_Xmsgrcv 1
#define __CRT_HAVE_sys_Xmsgsnd 1
#define __CRT_HAVE_sys_Xmsync 1
#define __CRT_HAVE_sys_Xmunlock 1
#define __CRT_HAVE_sys_Xmunlockall 1
#define __CRT_HAVE_sys_Xmunmap 1
#define __CRT_HAVE_sys_Xname_to_handle_at 1
#define __CRT_HAVE_sys_Xnanosleep 1
#define __CRT_HAVE_sys_Xnfsservctl 1
#define __CRT_HAVE_sys_Xoldwait4 1
#define __CRT_HAVE_sys_Xopen 1
#define __CRT_HAVE_sys_Xopen_by_handle_at 1
#define __CRT_HAVE_sys_Xopenat 1
#define __CRT_HAVE_sys_Xpause 1
#define __CRT_HAVE_sys_Xperf_event_open 1
#define __CRT_HAVE_sys_Xpersonality 1
#define __CRT_HAVE_sys_Xpipe 1
#define __CRT_HAVE_sys_Xpipe2 1
#define __CRT_HAVE_sys_Xpivot_root 1
#define __CRT_HAVE_sys_Xpoll 1
#define __CRT_HAVE_sys_Xppoll 1
#define __CRT_HAVE_sys_Xprctl 1
#define __CRT_HAVE_sys_Xpread64 1
#define __CRT_HAVE_sys_Xpreadv 1
#define __CRT_HAVE_sys_Xprlimit64 1
#define __CRT_HAVE_sys_Xprocess_vm_readv 1
#define __CRT_HAVE_sys_Xprocess_vm_writev 1
#define __CRT_HAVE_sys_Xpselect6 1
#define __CRT_HAVE_sys_Xptrace 1
#define __CRT_HAVE_sys_Xpwrite64 1
#define __CRT_HAVE_sys_Xpwritev 1
#define __CRT_HAVE_sys_Xquotactl 1
#define __CRT_HAVE_sys_Xread 1
#define __CRT_HAVE_sys_Xreadahead 1
#define __CRT_HAVE_sys_Xreadlink 1
#define __CRT_HAVE_sys_Xreadlinkat 1
#define __CRT_HAVE_sys_Xreadv 1
#define __CRT_HAVE_sys_Xreboot 1
#define __CRT_HAVE_sys_Xrecv 1
#define __CRT_HAVE_sys_Xrecvfrom 1
#define __CRT_HAVE_sys_Xrecvmmsg 1
#define __CRT_HAVE_sys_Xrecvmsg 1
#define __CRT_HAVE_sys_Xremap_file_pages 1
#define __CRT_HAVE_sys_Xremovexattr 1
#define __CRT_HAVE_sys_Xrename 1
#define __CRT_HAVE_sys_Xrenameat 1
#define __CRT_HAVE_sys_Xrenameat2 1
#define __CRT_HAVE_sys_Xrequest_key 1
#define __CRT_HAVE_sys_Xrestart_syscall 1
#define __CRT_HAVE_sys_Xrmdir 1
#define __CRT_HAVE_sys_Xrt_sigaction 1
#define __CRT_HAVE_sys_Xrt_sigpending 1
#define __CRT_HAVE_sys_Xrt_sigprocmask 1
#define __CRT_HAVE_sys_Xrt_sigqueueinfo 1
#define __CRT_HAVE_sys_Xrt_sigsuspend 1
#define __CRT_HAVE_sys_Xrt_sigtimedwait 1
#define __CRT_HAVE_sys_Xrt_tgsigqueueinfo 1
#define __CRT_HAVE_sys_Xsched_get_priority_max 1
#define __CRT_HAVE_sys_Xsched_get_priority_min 1
#define __CRT_HAVE_sys_Xsched_getaffinity 1
#define __CRT_HAVE_sys_Xsched_getattr 1
#define __CRT_HAVE_sys_Xsched_getparam 1
#define __CRT_HAVE_sys_Xsched_getscheduler 1
#define __CRT_HAVE_sys_Xsched_rr_get_interval 1
#define __CRT_HAVE_sys_Xsched_setaffinity 1
#define __CRT_HAVE_sys_Xsched_setattr 1
#define __CRT_HAVE_sys_Xsched_setparam 1
#define __CRT_HAVE_sys_Xsched_setscheduler 1
#define __CRT_HAVE_sys_Xsched_yield 1
#define __CRT_HAVE_sys_Xseccomp 1
#define __CRT_HAVE_sys_Xselect 1
#define __CRT_HAVE_sys_Xsemctl 1
#define __CRT_HAVE_sys_Xsemget 1
#define __CRT_HAVE_sys_Xsemop 1
#define __CRT_HAVE_sys_Xsemtimedop 1
#define __CRT_HAVE_sys_Xsend 1
#define __CRT_HAVE_sys_Xsendfile 1
#define __CRT_HAVE_sys_Xsendmmsg 1
#define __CRT_HAVE_sys_Xsendmsg 1
#define __CRT_HAVE_sys_Xsendto 1
#define __CRT_HAVE_sys_Xset_mempolicy 1
#define __CRT_HAVE_sys_Xset_robust_list 1
#define __CRT_HAVE_sys_Xset_tid_address 1
#define __CRT_HAVE_sys_Xsetdomainname 1
#define __CRT_HAVE_sys_Xsetfsgid 1
#define __CRT_HAVE_sys_Xsetfsuid 1
#define __CRT_HAVE_sys_Xsetgid 1
#define __CRT_HAVE_sys_Xsetgroups 1
#define __CRT_HAVE_sys_Xsethostname 1
#define __CRT_HAVE_sys_Xsetitimer 1
#define __CRT_HAVE_sys_Xsetns 1
#define __CRT_HAVE_sys_Xsetpgid 1
#define __CRT_HAVE_sys_Xsetpriority 1
#define __CRT_HAVE_sys_Xsetregid 1
#define __CRT_HAVE_sys_Xsetresgid 1
#define __CRT_HAVE_sys_Xsetresuid 1
#define __CRT_HAVE_sys_Xsetreuid 1
#define __CRT_HAVE_sys_Xsetrlimit 1
#define __CRT_HAVE_sys_Xsetsid 1
#define __CRT_HAVE_sys_Xsetsockopt 1
#define __CRT_HAVE_sys_Xsettimeofday 1
#define __CRT_HAVE_sys_Xsetuid 1
#define __CRT_HAVE_sys_Xsetxattr 1
#define __CRT_HAVE_sys_Xshmat 1
#define __CRT_HAVE_sys_Xshmctl 1
#define __CRT_HAVE_sys_Xshmdt 1
#define __CRT_HAVE_sys_Xshmget 1
#define __CRT_HAVE_sys_Xshutdown 1
#define __CRT_HAVE_sys_Xsigaltstack 1
#define __CRT_HAVE_sys_Xsignalfd 1
#define __CRT_HAVE_sys_Xsignalfd4 1
#define __CRT_HAVE_sys_Xsocket 1
#define __CRT_HAVE_sys_Xsocketpair 1
#define __CRT_HAVE_sys_Xsplice 1
#define __CRT_HAVE_sys_Xstatfs 1
#define __CRT_HAVE_sys_Xswapoff 1
#define __CRT_HAVE_sys_Xswapon 1
#define __CRT_HAVE_sys_Xsymlink 1
#define __CRT_HAVE_sys_Xsymlinkat 1
#define __CRT_HAVE_sys_Xsync 1
#define __CRT_HAVE_sys_Xsync_file_range 1
#define __CRT_HAVE_sys_Xsyncfs 1
#define __CRT_HAVE_sys_Xsysinfo 1
#define __CRT_HAVE_sys_Xsyslog 1
#define __CRT_HAVE_sys_Xtee 1
#define __CRT_HAVE_sys_Xtgkill 1
#define __CRT_HAVE_sys_Xtime 1
#define __CRT_HAVE_sys_Xtimer_create 1
#define __CRT_HAVE_sys_Xtimer_delete 1
#define __CRT_HAVE_sys_Xtimer_getoverrun 1
#define __CRT_HAVE_sys_Xtimer_gettime 1
#define __CRT_HAVE_sys_Xtimer_settime 1
#define __CRT_HAVE_sys_Xtimerfd_create 1
#define __CRT_HAVE_sys_Xtimerfd_gettime 1
#define __CRT_HAVE_sys_Xtimerfd_settime 1
#define __CRT_HAVE_sys_Xtimes 1
#define __CRT_HAVE_sys_Xtkill 1
#define __CRT_HAVE_sys_Xtruncate 1
#define __CRT_HAVE_sys_Xumask 1
#define __CRT_HAVE_sys_Xumount 1
#define __CRT_HAVE_sys_Xumount2 1
#define __CRT_HAVE_sys_Xuname 1
#define __CRT_HAVE_sys_Xunlink 1
#define __CRT_HAVE_sys_Xunlinkat 1
#define __CRT_HAVE_sys_Xunshare 1
#define __CRT_HAVE_sys_Xuselib 1
#define __CRT_HAVE_sys_Xuserfaultfd 1
#define __CRT_HAVE_sys_Xustat 1
#define __CRT_HAVE_sys_Xutime 1
#define __CRT_HAVE_sys_Xutimensat 1
#define __CRT_HAVE_sys_Xutimes 1
#define __CRT_HAVE_sys_Xvfork 1
#define __CRT_HAVE_sys_Xvhangup 1
#define __CRT_HAVE_sys_Xvmsplice 1
#define __CRT_HAVE_sys_Xwait4 1
#define __CRT_HAVE_sys_Xwaitid 1
#define __CRT_HAVE_sys_Xwrite 1
#define __CRT_HAVE_sys_Xwritev 1
