/* HASH CRC-32:0xd87b968c */
/* Copyright (c) 2019 Griefer@Work                                            *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement in the product documentation would be  *
 *    appreciated but is not required.                                        *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#define __CRT_STUB_FPathConf 1
#define __CRT_STUB_PathConf 1
#define __CRT_STUB___control87_2 1
#define __CRT_STUB___doserrno 1
#define __CRT_STUB___fpclassify 1
#define __CRT_STUB___fpecode 1
#define __CRT_STUB___h_errno_location 1
#define __CRT_STUB___issignaling 1
#define __CRT_STUB___locale_ctype_ptr 1
#define __CRT_STUB___locale_ctype_ptr_l 1
#define __CRT_STUB___p___wargv 1
#define __CRT_STUB___p___winitenv 1
#define __CRT_STUB___p__wenviron 1
#define __CRT_STUB___p__wpgmptr 1
#define __CRT_STUB___pthread_register_cancel 1
#define __CRT_STUB___pthread_register_cancel_defer 1
#define __CRT_STUB___pthread_unregister_cancel 1
#define __CRT_STUB___pthread_unregister_cancel_restore 1
#define __CRT_STUB___pthread_unwind_next 1
#define __CRT_STUB___signbit 1
#define __CRT_STUB___wcserror 1
#define __CRT_STUB___wcserror_s 1
#define __CRT_STUB__aligned_free 1
#define __CRT_STUB__aligned_malloc 1
#define __CRT_STUB__aligned_offset_malloc 1
#define __CRT_STUB__aligned_offset_realloc 1
#define __CRT_STUB__aligned_offset_recalloc 1
#define __CRT_STUB__aligned_realloc 1
#define __CRT_STUB__aligned_recalloc 1
#define __CRT_STUB__beep 1
#define __CRT_STUB__beginthread 1
#define __CRT_STUB__beginthreadex 1
#define __CRT_STUB__c_exit 1
#define __CRT_STUB__cexit 1
#define __CRT_STUB__clearfp 1
#define __CRT_STUB__control87 1
#define __CRT_STUB__controlfp 1
#define __CRT_STUB__controlfp_s 1
#define __CRT_STUB__dupenv_s 1
#define __CRT_STUB__endthread 1
#define __CRT_STUB__endthreadex 1
#define __CRT_STUB__findclose 1
#define __CRT_STUB__findfirst32 1
#define __CRT_STUB__findfirst32i64 1
#define __CRT_STUB__findfirst64i32 1
#define __CRT_STUB__findnext32 1
#define __CRT_STUB__findnext32i64 1
#define __CRT_STUB__findnext64 1
#define __CRT_STUB__fpclass 1
#define __CRT_STUB__fullpath 1
#define __CRT_STUB__get_doserrno 1
#define __CRT_STUB__get_output_format 1
#define __CRT_STUB__get_printf_count_output 1
#define __CRT_STUB__getdiskfree 1
#define __CRT_STUB__getmaxstdio 1
#define __CRT_STUB__isctype 1
#define __CRT_STUB__isctype_l 1
#define __CRT_STUB__mktemp_s 1
#define __CRT_STUB__recalloc 1
#define __CRT_STUB__rmtmp 1
#define __CRT_STUB__searchenv_s 1
#define __CRT_STUB__set_controlfp 1
#define __CRT_STUB__set_doserrno 1
#define __CRT_STUB__set_error_mode 1
#define __CRT_STUB__set_output_format 1
#define __CRT_STUB__set_printf_count_output 1
#define __CRT_STUB__seterrormode 1
#define __CRT_STUB__setmaxstdio 1
#define __CRT_STUB__statusfp 1
#define __CRT_STUB__statusfp2 1
#define __CRT_STUB__wcserror 1
#define __CRT_STUB__wcserror_s 1
#define __CRT_STUB__wperror 1
#define __CRT_STUB_a64l 1
#define __CRT_STUB_acos 1
#define __CRT_STUB_acosh 1
#define __CRT_STUB_addmntent 1
#define __CRT_STUB_adjtimex 1
#define __CRT_STUB_adjtimex64 1
#define __CRT_STUB_asin 1
#define __CRT_STUB_asinh 1
#define __CRT_STUB_at_quick_exit 1
#define __CRT_STUB_atan 1
#define __CRT_STUB_atan2 1
#define __CRT_STUB_atanh 1
#define __CRT_STUB_atexit 1
#define __CRT_STUB_backtrace 1
#define __CRT_STUB_backtrace_symbols 1
#define __CRT_STUB_backtrace_symbols_fd 1
#define __CRT_STUB_bindresvport 1
#define __CRT_STUB_bindresvport6 1
#define __CRT_STUB_cbrt 1
#define __CRT_STUB_clock 1
#define __CRT_STUB_clock_getcpuclockid 1
#define __CRT_STUB_closelog 1
#define __CRT_STUB_confstr 1
#define __CRT_STUB_cos 1
#define __CRT_STUB_cosh 1
#define __CRT_STUB_crypt 1
#define __CRT_STUB_crypt_r 1
#define __CRT_STUB_daemon 1
#define __CRT_STUB_drand48 1
#define __CRT_STUB_drand48_r 1
#define __CRT_STUB_drem 1
#define __CRT_STUB_duplocale 1
#define __CRT_STUB_encrypt 1
#define __CRT_STUB_encrypt_r 1
#define __CRT_STUB_endaliasent 1
#define __CRT_STUB_endgrent 1
#define __CRT_STUB_endhostent 1
#define __CRT_STUB_endmntent 1
#define __CRT_STUB_endnetent 1
#define __CRT_STUB_endnetgrent 1
#define __CRT_STUB_endprotoent 1
#define __CRT_STUB_endpwent 1
#define __CRT_STUB_endrpcent 1
#define __CRT_STUB_endservent 1
#define __CRT_STUB_endspent 1
#define __CRT_STUB_endttyent 1
#define __CRT_STUB_endusershell 1
#define __CRT_STUB_endutent 1
#define __CRT_STUB_endutxent 1
#define __CRT_STUB_erand48 1
#define __CRT_STUB_erand48_r 1
#define __CRT_STUB_erf 1
#define __CRT_STUB_erfc 1
#define __CRT_STUB_ether_aton 1
#define __CRT_STUB_ether_aton_r 1
#define __CRT_STUB_ether_hostton 1
#define __CRT_STUB_ether_line 1
#define __CRT_STUB_ether_ntoa 1
#define __CRT_STUB_ether_ntoa_r 1
#define __CRT_STUB_ether_ntohost 1
#define __CRT_STUB_exp 1
#define __CRT_STUB_exp10 1
#define __CRT_STUB_exp2 1
#define __CRT_STUB_expm1 1
#define __CRT_STUB_fattach 1
#define __CRT_STUB_fdetach 1
#define __CRT_STUB_fgetgrent 1
#define __CRT_STUB_fgetgrent_r 1
#define __CRT_STUB_fgetpwent 1
#define __CRT_STUB_fgetpwent_r 1
#define __CRT_STUB_fgetspent 1
#define __CRT_STUB_fgetspent_r 1
#define __CRT_STUB_fgetwc 1
#define __CRT_STUB_fgetwc_unlocked 1
#define __CRT_STUB_fmemopen 1
#define __CRT_STUB_fmod 1
#define __CRT_STUB_fopencookie 1
#define __CRT_STUB_fpathconf 1
#define __CRT_STUB_fpreset 1
#define __CRT_STUB_fputwc 1
#define __CRT_STUB_fputwc_unlocked 1
#define __CRT_STUB_freeaddrinfo 1
#define __CRT_STUB_freeifaddrs 1
#define __CRT_STUB_freelocale 1
#define __CRT_STUB_frexp 1
#define __CRT_STUB_ftok 1
#define __CRT_STUB_fwscanf_unlocked 1
#define __CRT_STUB_gai_cancel 1
#define __CRT_STUB_gai_error 1
#define __CRT_STUB_gai_strerror 1
#define __CRT_STUB_gai_suspend 1
#define __CRT_STUB_gai_suspend64 1
#define __CRT_STUB_getaddrinfo 1
#define __CRT_STUB_getaddrinfo_a 1
#define __CRT_STUB_getaliasbyname 1
#define __CRT_STUB_getaliasbyname_r 1
#define __CRT_STUB_getaliasent 1
#define __CRT_STUB_getaliasent_r 1
#define __CRT_STUB_getcontext 1
#define __CRT_STUB_getdate 1
#define __CRT_STUB_getdate_r 1
#define __CRT_STUB_getenv_s 1
#define __CRT_STUB_getgrent 1
#define __CRT_STUB_getgrent_r 1
#define __CRT_STUB_getgrgid 1
#define __CRT_STUB_getgrgid_r 1
#define __CRT_STUB_getgrnam 1
#define __CRT_STUB_getgrnam_r 1
#define __CRT_STUB_getgrouplist 1
#define __CRT_STUB_gethostbyaddr 1
#define __CRT_STUB_gethostbyaddr_r 1
#define __CRT_STUB_gethostbyname 1
#define __CRT_STUB_gethostbyname2 1
#define __CRT_STUB_gethostbyname2_r 1
#define __CRT_STUB_gethostbyname_r 1
#define __CRT_STUB_gethostent 1
#define __CRT_STUB_gethostent_r 1
#define __CRT_STUB_gethostid 1
#define __CRT_STUB_getifaddrs 1
#define __CRT_STUB_getipv4sourcefilter 1
#define __CRT_STUB_getloadavg 1
#define __CRT_STUB_getlogin 1
#define __CRT_STUB_getlogin_r 1
#define __CRT_STUB_getmntent 1
#define __CRT_STUB_getmntent_r 1
#define __CRT_STUB_getmsg 1
#define __CRT_STUB_getnameinfo 1
#define __CRT_STUB_getnetbyaddr 1
#define __CRT_STUB_getnetbyaddr_r 1
#define __CRT_STUB_getnetbyname 1
#define __CRT_STUB_getnetbyname_r 1
#define __CRT_STUB_getnetent 1
#define __CRT_STUB_getnetent_r 1
#define __CRT_STUB_getnetgrent 1
#define __CRT_STUB_getnetgrent_r 1
#define __CRT_STUB_getpass 1
#define __CRT_STUB_getpmsg 1
#define __CRT_STUB_getprotobyname 1
#define __CRT_STUB_getprotobyname_r 1
#define __CRT_STUB_getprotobynumber 1
#define __CRT_STUB_getprotobynumber_r 1
#define __CRT_STUB_getprotoent 1
#define __CRT_STUB_getprotoent_r 1
#define __CRT_STUB_getpt 1
#define __CRT_STUB_getpw 1
#define __CRT_STUB_getpwent 1
#define __CRT_STUB_getpwent_r 1
#define __CRT_STUB_getpwnam 1
#define __CRT_STUB_getpwnam_r 1
#define __CRT_STUB_getpwuid 1
#define __CRT_STUB_getpwuid_r 1
#define __CRT_STUB_getrlimit64 1
#define __CRT_STUB_getrpcbyname 1
#define __CRT_STUB_getrpcbyname_r 1
#define __CRT_STUB_getrpcbynumber 1
#define __CRT_STUB_getrpcbynumber_r 1
#define __CRT_STUB_getrpcent 1
#define __CRT_STUB_getrpcent_r 1
#define __CRT_STUB_getservbyname 1
#define __CRT_STUB_getservbyname_r 1
#define __CRT_STUB_getservbyport 1
#define __CRT_STUB_getservbyport_r 1
#define __CRT_STUB_getservent 1
#define __CRT_STUB_getservent_r 1
#define __CRT_STUB_getsourcefilter 1
#define __CRT_STUB_getspent 1
#define __CRT_STUB_getspent_r 1
#define __CRT_STUB_getspnam 1
#define __CRT_STUB_getspnam_r 1
#define __CRT_STUB_getttyent 1
#define __CRT_STUB_getttynam 1
#define __CRT_STUB_getusershell 1
#define __CRT_STUB_getutent 1
#define __CRT_STUB_getutent_r 1
#define __CRT_STUB_getutid 1
#define __CRT_STUB_getutid_r 1
#define __CRT_STUB_getutline 1
#define __CRT_STUB_getutline_r 1
#define __CRT_STUB_getutmp 1
#define __CRT_STUB_getutmpx 1
#define __CRT_STUB_getutxent 1
#define __CRT_STUB_getutxid 1
#define __CRT_STUB_getutxline 1
#define __CRT_STUB_grantpt 1
#define __CRT_STUB_gtty 1
#define __CRT_STUB_herror 1
#define __CRT_STUB_hstrerror 1
#define __CRT_STUB_hypot 1
#define __CRT_STUB_if_freenameindex 1
#define __CRT_STUB_if_indextoname 1
#define __CRT_STUB_if_nameindex 1
#define __CRT_STUB_if_nametoindex 1
#define __CRT_STUB_ilogb 1
#define __CRT_STUB_inet6_opt_append 1
#define __CRT_STUB_inet6_opt_find 1
#define __CRT_STUB_inet6_opt_finish 1
#define __CRT_STUB_inet6_opt_get_val 1
#define __CRT_STUB_inet6_opt_init 1
#define __CRT_STUB_inet6_opt_next 1
#define __CRT_STUB_inet6_opt_set_val 1
#define __CRT_STUB_inet6_option_alloc 1
#define __CRT_STUB_inet6_option_append 1
#define __CRT_STUB_inet6_option_find 1
#define __CRT_STUB_inet6_option_init 1
#define __CRT_STUB_inet6_option_next 1
#define __CRT_STUB_inet6_option_space 1
#define __CRT_STUB_inet6_rth_add 1
#define __CRT_STUB_inet6_rth_getaddr 1
#define __CRT_STUB_inet6_rth_init 1
#define __CRT_STUB_inet6_rth_reverse 1
#define __CRT_STUB_inet6_rth_segments 1
#define __CRT_STUB_inet6_rth_space 1
#define __CRT_STUB_inet_addr 1
#define __CRT_STUB_inet_aton 1
#define __CRT_STUB_inet_lnaof 1
#define __CRT_STUB_inet_net_ntop 1
#define __CRT_STUB_inet_net_pton 1
#define __CRT_STUB_inet_neta 1
#define __CRT_STUB_inet_netof 1
#define __CRT_STUB_inet_network 1
#define __CRT_STUB_inet_nsap_addr 1
#define __CRT_STUB_inet_nsap_ntoa 1
#define __CRT_STUB_inet_ntoa 1
#define __CRT_STUB_inet_ntop 1
#define __CRT_STUB_inet_pton 1
#define __CRT_STUB_initgroups 1
#define __CRT_STUB_initstate 1
#define __CRT_STUB_initstate_r 1
#define __CRT_STUB_innetgr 1
#define __CRT_STUB_iruserok 1
#define __CRT_STUB_iruserok_af 1
#define __CRT_STUB_isastream 1
#define __CRT_STUB_j0 1
#define __CRT_STUB_j1 1
#define __CRT_STUB_jn 1
#define __CRT_STUB_jrand48 1
#define __CRT_STUB_jrand48_r 1
#define __CRT_STUB_klogctl 1
#define __CRT_STUB_l64a 1
#define __CRT_STUB_lckpwdf 1
#define __CRT_STUB_lcong48 1
#define __CRT_STUB_lcong48_r 1
#define __CRT_STUB_ldexp 1
#define __CRT_STUB_lgamma 1
#define __CRT_STUB_lgamma_r 1
#define __CRT_STUB_llrint 1
#define __CRT_STUB_localeconv 1
#define __CRT_STUB_lockf64 1
#define __CRT_STUB_log 1
#define __CRT_STUB_log10 1
#define __CRT_STUB_log1p 1
#define __CRT_STUB_log2 1
#define __CRT_STUB_logb 1
#define __CRT_STUB_login 1
#define __CRT_STUB_login_tty 1
#define __CRT_STUB_logout 1
#define __CRT_STUB_logwtmp 1
#define __CRT_STUB_lrand48 1
#define __CRT_STUB_lrand48_r 1
#define __CRT_STUB_lrint 1
#define __CRT_STUB_makecontext 1
#define __CRT_STUB_mbsnrtowcs 1
#define __CRT_STUB_mkdtemp 1
#define __CRT_STUB_mkostemp 1
#define __CRT_STUB_mkostemp64 1
#define __CRT_STUB_mkostemps 1
#define __CRT_STUB_mkostemps64 1
#define __CRT_STUB_mkstemp 1
#define __CRT_STUB_mkstemps 1
#define __CRT_STUB_mkstemps64 1
#define __CRT_STUB_mktemp 1
#define __CRT_STUB_modf 1
#define __CRT_STUB_mrand48 1
#define __CRT_STUB_mrand48_r 1
#define __CRT_STUB_msgctl 1
#define __CRT_STUB_msgget 1
#define __CRT_STUB_msgrcv 1
#define __CRT_STUB_msgsnd 1
#define __CRT_STUB_nearbyint 1
#define __CRT_STUB_newlocale 1
#define __CRT_STUB_nextafter 1
#define __CRT_STUB_nexttoward 1
#define __CRT_STUB_nrand48 1
#define __CRT_STUB_nrand48_r 1
#define __CRT_STUB_ntp_adjtime 1
#define __CRT_STUB_ntp_adjtime64 1
#define __CRT_STUB_ntp_gettime 1
#define __CRT_STUB_ntp_gettime64 1
#define __CRT_STUB_obstack_vprintf 1
#define __CRT_STUB_on_exit 1
#define __CRT_STUB_onexit 1
#define __CRT_STUB_open_memstream 1
#define __CRT_STUB_open_wmemstream 1
#define __CRT_STUB_openlog 1
#define __CRT_STUB_pathconf 1
#define __CRT_STUB_pclose 1
#define __CRT_STUB_popen 1
#define __CRT_STUB_posix_fadvise64 1
#define __CRT_STUB_posix_fallocate64 1
#define __CRT_STUB_posix_madvise 1
#define __CRT_STUB_posix_openpt 1
#define __CRT_STUB_posix_spawn 1
#define __CRT_STUB_posix_spawn_file_actions_addclose 1
#define __CRT_STUB_posix_spawn_file_actions_adddup2 1
#define __CRT_STUB_posix_spawn_file_actions_addopen 1
#define __CRT_STUB_posix_spawn_file_actions_destroy 1
#define __CRT_STUB_posix_spawn_file_actions_init 1
#define __CRT_STUB_posix_spawnattr_destroy 1
#define __CRT_STUB_posix_spawnattr_getflags 1
#define __CRT_STUB_posix_spawnattr_getpgroup 1
#define __CRT_STUB_posix_spawnattr_getschedparam 1
#define __CRT_STUB_posix_spawnattr_getschedpolicy 1
#define __CRT_STUB_posix_spawnattr_getsigdefault 1
#define __CRT_STUB_posix_spawnattr_getsigmask 1
#define __CRT_STUB_posix_spawnattr_init 1
#define __CRT_STUB_posix_spawnattr_setflags 1
#define __CRT_STUB_posix_spawnattr_setpgroup 1
#define __CRT_STUB_posix_spawnattr_setschedparam 1
#define __CRT_STUB_posix_spawnattr_setschedpolicy 1
#define __CRT_STUB_posix_spawnattr_setsigdefault 1
#define __CRT_STUB_posix_spawnattr_setsigmask 1
#define __CRT_STUB_posix_spawnp 1
#define __CRT_STUB_pow 1
#define __CRT_STUB_pow10 1
#define __CRT_STUB_preadv 1
#define __CRT_STUB_preadv64 1
#define __CRT_STUB_prlimit 1
#define __CRT_STUB_prlimit64 1
#define __CRT_STUB_process_vm_readv 1
#define __CRT_STUB_process_vm_writev 1
#define __CRT_STUB_psiginfo 1
#define __CRT_STUB_psignal 1
#define __CRT_STUB_pthread_atfork 1
#define __CRT_STUB_pthread_barrier_destroy 1
#define __CRT_STUB_pthread_barrier_init 1
#define __CRT_STUB_pthread_barrier_wait 1
#define __CRT_STUB_pthread_barrierattr_destroy 1
#define __CRT_STUB_pthread_barrierattr_getpshared 1
#define __CRT_STUB_pthread_barrierattr_init 1
#define __CRT_STUB_pthread_barrierattr_setpshared 1
#define __CRT_STUB_pthread_cond_broadcast 1
#define __CRT_STUB_pthread_cond_destroy 1
#define __CRT_STUB_pthread_cond_init 1
#define __CRT_STUB_pthread_cond_signal 1
#define __CRT_STUB_pthread_cond_timedwait 1
#define __CRT_STUB_pthread_cond_wait 1
#define __CRT_STUB_pthread_condattr_destroy 1
#define __CRT_STUB_pthread_condattr_getclock 1
#define __CRT_STUB_pthread_condattr_getpshared 1
#define __CRT_STUB_pthread_condattr_init 1
#define __CRT_STUB_pthread_condattr_setclock 1
#define __CRT_STUB_pthread_condattr_setpshared 1
#define __CRT_STUB_pthread_getcpuclockid 1
#define __CRT_STUB_pthread_getspecific 1
#define __CRT_STUB_pthread_key_create 1
#define __CRT_STUB_pthread_key_delete 1
#define __CRT_STUB_pthread_mutex_consistent 1
#define __CRT_STUB_pthread_mutex_consistent_np 1
#define __CRT_STUB_pthread_mutex_destroy 1
#define __CRT_STUB_pthread_mutex_getprioceiling 1
#define __CRT_STUB_pthread_mutex_init 1
#define __CRT_STUB_pthread_mutex_lock 1
#define __CRT_STUB_pthread_mutex_setprioceiling 1
#define __CRT_STUB_pthread_mutex_timedlock 1
#define __CRT_STUB_pthread_mutex_trylock 1
#define __CRT_STUB_pthread_mutex_unlock 1
#define __CRT_STUB_pthread_mutexattr_destroy 1
#define __CRT_STUB_pthread_mutexattr_getprioceiling 1
#define __CRT_STUB_pthread_mutexattr_getprotocol 1
#define __CRT_STUB_pthread_mutexattr_getpshared 1
#define __CRT_STUB_pthread_mutexattr_getrobust 1
#define __CRT_STUB_pthread_mutexattr_getrobust_np 1
#define __CRT_STUB_pthread_mutexattr_gettype 1
#define __CRT_STUB_pthread_mutexattr_init 1
#define __CRT_STUB_pthread_mutexattr_setprioceiling 1
#define __CRT_STUB_pthread_mutexattr_setprotocol 1
#define __CRT_STUB_pthread_mutexattr_setpshared 1
#define __CRT_STUB_pthread_mutexattr_setrobust 1
#define __CRT_STUB_pthread_mutexattr_setrobust_np 1
#define __CRT_STUB_pthread_mutexattr_settype 1
#define __CRT_STUB_pthread_once 1
#define __CRT_STUB_pthread_rwlock_destroy 1
#define __CRT_STUB_pthread_rwlock_init 1
#define __CRT_STUB_pthread_rwlock_rdlock 1
#define __CRT_STUB_pthread_rwlock_timedrdlock 1
#define __CRT_STUB_pthread_rwlock_timedwrlock 1
#define __CRT_STUB_pthread_rwlock_tryrdlock 1
#define __CRT_STUB_pthread_rwlock_trywrlock 1
#define __CRT_STUB_pthread_rwlock_unlock 1
#define __CRT_STUB_pthread_rwlock_wrlock 1
#define __CRT_STUB_pthread_rwlockattr_destroy 1
#define __CRT_STUB_pthread_rwlockattr_getkind_np 1
#define __CRT_STUB_pthread_rwlockattr_getpshared 1
#define __CRT_STUB_pthread_rwlockattr_init 1
#define __CRT_STUB_pthread_rwlockattr_setkind_np 1
#define __CRT_STUB_pthread_rwlockattr_setpshared 1
#define __CRT_STUB_pthread_setcancelstate 1
#define __CRT_STUB_pthread_setcanceltype 1
#define __CRT_STUB_pthread_setspecific 1
#define __CRT_STUB_pthread_spin_destroy 1
#define __CRT_STUB_pthread_spin_init 1
#define __CRT_STUB_pthread_spin_lock 1
#define __CRT_STUB_pthread_spin_trylock 1
#define __CRT_STUB_pthread_spin_unlock 1
#define __CRT_STUB_ptsname 1
#define __CRT_STUB_ptsname_r 1
#define __CRT_STUB_putgrent 1
#define __CRT_STUB_putmsg 1
#define __CRT_STUB_putpmsg 1
#define __CRT_STUB_putpwent 1
#define __CRT_STUB_putspent 1
#define __CRT_STUB_pututline 1
#define __CRT_STUB_pututxline 1
#define __CRT_STUB_pwritev 1
#define __CRT_STUB_pwritev64 1
#define __CRT_STUB_random_r 1
#define __CRT_STUB_rcmd 1
#define __CRT_STUB_rcmd_af 1
#define __CRT_STUB_re_match_2 1
#define __CRT_STUB_re_set_registers 1
#define __CRT_STUB_readdir64_r 1
#define __CRT_STUB_readdir_r 1
#define __CRT_STUB_readv 1
#define __CRT_STUB_regcomp 1
#define __CRT_STUB_regerror 1
#define __CRT_STUB_regexec 1
#define __CRT_STUB_remainder 1
#define __CRT_STUB_remquo 1
#define __CRT_STUB_revoke 1
#define __CRT_STUB_rexec 1
#define __CRT_STUB_rexec_af 1
#define __CRT_STUB_rint 1
#define __CRT_STUB_rpmatch 1
#define __CRT_STUB_rresvport 1
#define __CRT_STUB_rresvport_af 1
#define __CRT_STUB_ruserok 1
#define __CRT_STUB_ruserok_af 1
#define __CRT_STUB_scalb 1
#define __CRT_STUB_scalbln 1
#define __CRT_STUB_scalbn 1
#define __CRT_STUB_scandir 1
#define __CRT_STUB_scandirat 1
#define __CRT_STUB_sched_getcpu 1
#define __CRT_STUB_seed48 1
#define __CRT_STUB_seed48_r 1
#define __CRT_STUB_sem_close 1
#define __CRT_STUB_sem_open 1
#define __CRT_STUB_sem_unlink 1
#define __CRT_STUB_semctl 1
#define __CRT_STUB_semget 1
#define __CRT_STUB_semop 1
#define __CRT_STUB_semtimedop 1
#define __CRT_STUB_setaliasent 1
#define __CRT_STUB_setcontext 1
#define __CRT_STUB_setgrent 1
#define __CRT_STUB_setgroups 1
#define __CRT_STUB_sethostent 1
#define __CRT_STUB_sethostid 1
#define __CRT_STUB_setipv4sourcefilter 1
#define __CRT_STUB_setkey 1
#define __CRT_STUB_setkey_r 1
#define __CRT_STUB_setlocale 1
#define __CRT_STUB_setlogin 1
#define __CRT_STUB_setlogmask 1
#define __CRT_STUB_setmntent 1
#define __CRT_STUB_setnetent 1
#define __CRT_STUB_setnetgrent 1
#define __CRT_STUB_setprotoent 1
#define __CRT_STUB_setpwent 1
#define __CRT_STUB_setrlimit64 1
#define __CRT_STUB_setrpcent 1
#define __CRT_STUB_setservent 1
#define __CRT_STUB_setsourcefilter 1
#define __CRT_STUB_setspent 1
#define __CRT_STUB_setstate 1
#define __CRT_STUB_setstate_r 1
#define __CRT_STUB_setttyent 1
#define __CRT_STUB_setusershell 1
#define __CRT_STUB_setutent 1
#define __CRT_STUB_setutxent 1
#define __CRT_STUB_sgetspent 1
#define __CRT_STUB_sgetspent_r 1
#define __CRT_STUB_shm_open 1
#define __CRT_STUB_shm_unlink 1
#define __CRT_STUB_shmat 1
#define __CRT_STUB_shmctl 1
#define __CRT_STUB_shmdt 1
#define __CRT_STUB_shmget 1
#define __CRT_STUB_significand 1
#define __CRT_STUB_sigreturn 1
#define __CRT_STUB_sin 1
#define __CRT_STUB_sincos 1
#define __CRT_STUB_sinh 1
#define __CRT_STUB_spawnl 1
#define __CRT_STUB_spawnle 1
#define __CRT_STUB_spawnlp 1
#define __CRT_STUB_spawnlpe 1
#define __CRT_STUB_spawnv 1
#define __CRT_STUB_spawnve 1
#define __CRT_STUB_spawnvp 1
#define __CRT_STUB_spawnvpe 1
#define __CRT_STUB_sqrt 1
#define __CRT_STUB_srand48 1
#define __CRT_STUB_srand48_r 1
#define __CRT_STUB_srandom_r 1
#define __CRT_STUB_stty 1
#define __CRT_STUB_swapcontext 1
#define __CRT_STUB_tan 1
#define __CRT_STUB_tanh 1
#define __CRT_STUB_tcsetsid 1
#define __CRT_STUB_tempnam 1
#define __CRT_STUB_tgamma 1
#define __CRT_STUB_timespec_get 1
#define __CRT_STUB_tmpfile 1
#define __CRT_STUB_tmpnam 1
#define __CRT_STUB_tmpnam_r 1
#define __CRT_STUB_ttyslot 1
#define __CRT_STUB_tzset 1
#define __CRT_STUB_ualarm 1
#define __CRT_STUB_ulckpwdf 1
#define __CRT_STUB_ungetwc 1
#define __CRT_STUB_ungetwc_unlocked 1
#define __CRT_STUB_unlockpt 1
#define __CRT_STUB_updwtmp 1
#define __CRT_STUB_updwtmpx 1
#define __CRT_STUB_uselocale 1
#define __CRT_STUB_utmpname 1
#define __CRT_STUB_utmpxname 1
#define __CRT_STUB_vfwscanf 1
#define __CRT_STUB_vhangup 1
#define __CRT_STUB_vwscanf_unlocked 1
#define __CRT_STUB_wcsnrtombs 1
#define __CRT_STUB_wcswidth 1
#define __CRT_STUB_wcwidth 1
#define __CRT_STUB_wfreadlinkat 1
#define __CRT_STUB_wgetlogin 1
#define __CRT_STUB_wgetlogin_r 1
#define __CRT_STUB_writev 1
#define __CRT_STUB_wscanf_unlocked 1
#define __CRT_STUB_wttyname 1
#define __CRT_STUB_wttyname_r 1
#define __CRT_STUB_y0 1
#define __CRT_STUB_y1 1
#define __CRT_STUB_yn 1
