/* HASH CRC-32:0x8331519 */
/* Copyright (c) 2019-2025 Griefer@Work                                       *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement (see the following) in the product     *
 *    documentation is required:                                              *
 *    Portions Copyright (c) 2019-2025 Griefer@Work                           *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */

#define __CRT_HAVE__Unwind_Resume
#define __CRT_HAVE__ZSt9terminatev
#define __CRT_HAVE___acheck
#define __CRT_HAVE___acheckf
#define __CRT_HAVE___afail
#define __CRT_HAVE___afailf
#define __CRT_HAVE___ctype_C_flags
#define __CRT_HAVE___ctype_C_tolower
#define __CRT_HAVE___ctype_C_toupper
#define __CRT_HAVE___cxa_begin_catch
#define __CRT_HAVE___cxa_end_catch
#define __CRT_HAVE___cxa_rethrow
#define __CRT_HAVE___gcc_personality_v0
#define __CRT_HAVE___gxx_personality_v0
#define __CRT_HAVE___stack_chk_fail
#define __CRT_HAVE___stack_chk_guard
#define __CRT_HAVE___ubsan_handle_builtin_unreachable
#define __CRT_HAVE__except_badusage_no_nesting
#define __CRT_HAVE__except_check_no_nesting
#define __CRT_HAVE__itoa_digits
#define __CRT_HAVE_abort
#define __CRT_HAVE_bcmp
#define __CRT_HAVE_bcmpc
#define __CRT_HAVE_bcmpl
#define __CRT_HAVE_bcmpq
#define __CRT_HAVE_bcmpw
#define __CRT_HAVE_bitcpy
#define __CRT_HAVE_bzero
#define __CRT_HAVE_bzeroc
#define __CRT_HAVE_bzerol
#define __CRT_HAVE_bzeroq
#define __CRT_HAVE_bzerow
#define __CRT_HAVE_cfmakesane
#define __CRT_HAVE_except_active
#define __CRT_HAVE_except_as_errno
#define __CRT_HAVE_except_as_signal
#define __CRT_HAVE_except_class
#define __CRT_HAVE_except_code
#define __CRT_HAVE_except_data
#define __CRT_HAVE_except_info
#define __CRT_HAVE_except_name
#define __CRT_HAVE_except_nesting_begin
#define __CRT_HAVE_except_nesting_end
#define __CRT_HAVE_except_print_short_description
#define __CRT_HAVE_except_priority
#define __CRT_HAVE_except_register_state
#define __CRT_HAVE_except_rethrow
#define __CRT_HAVE_except_subclass
#define __CRT_HAVE_except_throw
#define __CRT_HAVE_except_throw_current
#define __CRT_HAVE_except_thrown
#define __CRT_HAVE_except_unwind
#define __CRT_HAVE_format_escape
#define __CRT_HAVE_format_hexdump
#define __CRT_HAVE_format_length
#define __CRT_HAVE_format_printf
#define __CRT_HAVE_format_repeat
#define __CRT_HAVE_format_scanf
#define __CRT_HAVE_format_snprintf_printer
#define __CRT_HAVE_format_sprintf_printer
#define __CRT_HAVE_format_vprintf
#define __CRT_HAVE_format_vscanf
#define __CRT_HAVE_format_width
#define __CRT_HAVE_lockop_reap_atomic_lock
#define __CRT_HAVE_lockop_reap_atomic_rwlock
#define __CRT_HAVE_lockop_reap_ex
#define __CRT_HAVE_lockop_reap_shared_lock
#define __CRT_HAVE_lockop_reap_shared_rwlock
#define __CRT_HAVE_memcasecmp
#define __CRT_HAVE_memchr
#define __CRT_HAVE_memchrl
#define __CRT_HAVE_memchrq
#define __CRT_HAVE_memchrw
#define __CRT_HAVE_memcmp
#define __CRT_HAVE_memcmpc
#define __CRT_HAVE_memcmpl
#define __CRT_HAVE_memcmpq
#define __CRT_HAVE_memcmpw
#define __CRT_HAVE_memcpy
#include <kos/bits/nopf.h>
#ifndef __arch_memcpy_nopf
#define __CRT_HAVE_memcpy_nopf
#endif /* !__arch_memcpy_nopf */
#define __CRT_HAVE_memcpyl
#define __CRT_HAVE_memcpyq
#define __CRT_HAVE_memcpyw
#define __CRT_HAVE_memend
#define __CRT_HAVE_memendl
#define __CRT_HAVE_memendq
#define __CRT_HAVE_memendw
#ifndef __arch_nopf_memeq
#define __CRT_HAVE_memeq_nopf
#endif /* !__arch_nopf_memeq */
#define __CRT_HAVE_memlen
#define __CRT_HAVE_memlenl
#define __CRT_HAVE_memlenq
#define __CRT_HAVE_memlenw
#define __CRT_HAVE_memmove
#define __CRT_HAVE_memmovedown
#define __CRT_HAVE_memmovedownl
#define __CRT_HAVE_memmovedownq
#define __CRT_HAVE_memmovedownw
#define __CRT_HAVE_memmovel
#define __CRT_HAVE_memmoveq
#define __CRT_HAVE_memmoveup
#define __CRT_HAVE_memmoveupl
#define __CRT_HAVE_memmoveupq
#define __CRT_HAVE_memmoveupw
#define __CRT_HAVE_memmovew
#define __CRT_HAVE_mempatl
#define __CRT_HAVE_mempatq
#define __CRT_HAVE_mempatw
#define __CRT_HAVE_mempcpy
#define __CRT_HAVE_mempcpyl
#define __CRT_HAVE_mempcpyq
#define __CRT_HAVE_mempcpyw
#define __CRT_HAVE_mempmove
#define __CRT_HAVE_mempmovedown
#define __CRT_HAVE_mempmovedownl
#define __CRT_HAVE_mempmovedownq
#define __CRT_HAVE_mempmovedownw
#define __CRT_HAVE_mempmovel
#define __CRT_HAVE_mempmoveq
#define __CRT_HAVE_mempmoveup
#define __CRT_HAVE_mempmoveupl
#define __CRT_HAVE_mempmoveupq
#define __CRT_HAVE_mempmoveupw
#define __CRT_HAVE_mempmovew
#define __CRT_HAVE_mempset
#define __CRT_HAVE_mempsetl
#define __CRT_HAVE_mempsetq
#define __CRT_HAVE_mempsetw
#define __CRT_HAVE_memrchr
#define __CRT_HAVE_memrchrl
#define __CRT_HAVE_memrchrq
#define __CRT_HAVE_memrchrw
#define __CRT_HAVE_memrend
#define __CRT_HAVE_memrendl
#define __CRT_HAVE_memrendq
#define __CRT_HAVE_memrendw
#define __CRT_HAVE_memrlen
#define __CRT_HAVE_memrlenl
#define __CRT_HAVE_memrlenq
#define __CRT_HAVE_memrlenw
#define __CRT_HAVE_memset
#ifndef __arch_memset_nopf
#define __CRT_HAVE_memset_nopf
#endif /* !__arch_memset_nopf */
#define __CRT_HAVE_memsetl
#define __CRT_HAVE_memsetq
#define __CRT_HAVE_memsetw
#define __CRT_HAVE_oblockop_reap_atomic_lock
#define __CRT_HAVE_oblockop_reap_atomic_lock_LO
#define __CRT_HAVE_oblockop_reap_atomic_lock_OL
#define __CRT_HAVE_oblockop_reap_atomic_rwlock
#define __CRT_HAVE_oblockop_reap_atomic_rwlock_LO
#define __CRT_HAVE_oblockop_reap_atomic_rwlock_OL
#define __CRT_HAVE_oblockop_reap_ex
#define __CRT_HAVE_oblockop_reap_shared_lock
#define __CRT_HAVE_oblockop_reap_shared_rwlock
#define __CRT_HAVE_qsort
#define __CRT_HAVE_qsort_r
#define __CRT_HAVE_rawmemchr
#define __CRT_HAVE_rawmemchrl
#define __CRT_HAVE_rawmemchrq
#define __CRT_HAVE_rawmemchrw
#define __CRT_HAVE_rawmemlen
#define __CRT_HAVE_rawmemlenl
#define __CRT_HAVE_rawmemlenq
#define __CRT_HAVE_rawmemlenw
#define __CRT_HAVE_rawmemrchr
#define __CRT_HAVE_rawmemrchrl
#define __CRT_HAVE_rawmemrchrq
#define __CRT_HAVE_rawmemrchrw
#define __CRT_HAVE_rawmemrlen
#define __CRT_HAVE_rawmemrlenl
#define __CRT_HAVE_rawmemrlenq
#define __CRT_HAVE_rawmemrlenw
#ifndef __arch_readb_nopf
#define __CRT_HAVE_readb_nopf
#endif /* !__arch_readb_nopf */
#ifndef __arch_readl_nopf
#define __CRT_HAVE_readl_nopf
#endif /* !__arch_readl_nopf */
#ifndef __arch_readq_nopf
#define __CRT_HAVE_readq_nopf
#endif /* !__arch_readq_nopf */
#ifndef __arch_readw_nopf
#define __CRT_HAVE_readw_nopf
#endif /* !__arch_readw_nopf */
#define __CRT_HAVE_shared_lock_acquire
#define __CRT_HAVE_shared_lock_acquire_nx
#define __CRT_HAVE_shared_lock_acquire_with_timeout
#define __CRT_HAVE_shared_lock_acquire_with_timeout_nx
#define __CRT_HAVE_shared_lock_waitfor
#define __CRT_HAVE_shared_lock_waitfor_nx
#define __CRT_HAVE_shared_lock_waitfor_with_timeout
#define __CRT_HAVE_shared_lock_waitfor_with_timeout_nx
#define __CRT_HAVE_shared_rwlock_downgrade
#define __CRT_HAVE_shared_rwlock_end
#define __CRT_HAVE_shared_rwlock_endread
#define __CRT_HAVE_shared_rwlock_endwrite
#define __CRT_HAVE_shared_rwlock_read
#define __CRT_HAVE_shared_rwlock_read_nx
#define __CRT_HAVE_shared_rwlock_read_with_timeout
#define __CRT_HAVE_shared_rwlock_read_with_timeout_nx
#define __CRT_HAVE_shared_rwlock_tryread
#define __CRT_HAVE_shared_rwlock_trywrite
#define __CRT_HAVE_shared_rwlock_upgrade
#define __CRT_HAVE_shared_rwlock_waitread
#define __CRT_HAVE_shared_rwlock_waitread_nx
#define __CRT_HAVE_shared_rwlock_waitread_with_timeout
#define __CRT_HAVE_shared_rwlock_waitread_with_timeout_nx
#define __CRT_HAVE_shared_rwlock_waitwrite
#define __CRT_HAVE_shared_rwlock_waitwrite_nx
#define __CRT_HAVE_shared_rwlock_waitwrite_with_timeout
#define __CRT_HAVE_shared_rwlock_waitwrite_with_timeout_nx
#define __CRT_HAVE_shared_rwlock_write
#define __CRT_HAVE_shared_rwlock_write_nx
#define __CRT_HAVE_shared_rwlock_write_with_timeout
#define __CRT_HAVE_shared_rwlock_write_with_timeout_nx
#define __CRT_HAVE_sigabbrev_np
#define __CRT_HAVE_sigaddset
#define __CRT_HAVE_sigandset
#define __CRT_HAVE_sigcodedesc_np
#define __CRT_HAVE_sigcodename_np
#define __CRT_HAVE_sigdelset
#define __CRT_HAVE_sigdescr_np
#define __CRT_HAVE_sigemptyset
#define __CRT_HAVE_sigfillset
#define __CRT_HAVE_sigisemptyset
#define __CRT_HAVE_sigismember
#define __CRT_HAVE_signandset
#define __CRT_HAVE_sigorset
#define __CRT_HAVE_snprintf
#define __CRT_HAVE_sprintf
#define __CRT_HAVE_sscanf
#define __CRT_HAVE_stpcpy
#define __CRT_HAVE_strcasecmp
#define __CRT_HAVE_strcasestr
#define __CRT_HAVE_strcat
#define __CRT_HAVE_strchr
#define __CRT_HAVE_strchrnul
#define __CRT_HAVE_strcmp
#define __CRT_HAVE_strcmpz
#define __CRT_HAVE_strcpy
#define __CRT_HAVE_strend
#define __CRT_HAVE_strerrordesc_np
#define __CRT_HAVE_strerrorname_np
#define __CRT_HAVE_strlcat
#define __CRT_HAVE_strlcpy
#define __CRT_HAVE_strlen
#define __CRT_HAVE_strlstrip
#define __CRT_HAVE_strncasecmp
#define __CRT_HAVE_strncmp
#define __CRT_HAVE_strnend
#define __CRT_HAVE_strnlen
#define __CRT_HAVE_strrchr
#define __CRT_HAVE_strrstrip
#define __CRT_HAVE_strstartcmp
#define __CRT_HAVE_strstartcmpz
#define __CRT_HAVE_strstr
#define __CRT_HAVE_strstrip
#define __CRT_HAVE_strto32
#define __CRT_HAVE_strto32_r
#define __CRT_HAVE_strto64
#define __CRT_HAVE_strto64_r
#define __CRT_HAVE_strtou32
#define __CRT_HAVE_strtou32_r
#define __CRT_HAVE_strtou64
#define __CRT_HAVE_strtou64_r
#define __CRT_HAVE_unicode_16to32
#define __CRT_HAVE_unicode_16to8
#define __CRT_HAVE_unicode_32to16
#define __CRT_HAVE_unicode_32to8
#define __CRT_HAVE_unicode_8to16
#define __CRT_HAVE_unicode_8to32
#define __CRT_HAVE_unicode_readutf16
#define __CRT_HAVE_unicode_readutf16_n
#define __CRT_HAVE_unicode_readutf16_rev
#define __CRT_HAVE_unicode_readutf16_rev_n
#define __CRT_HAVE_unicode_readutf16_swap
#define __CRT_HAVE_unicode_readutf16_swap_n
#define __CRT_HAVE_unicode_readutf16_swap_rev
#define __CRT_HAVE_unicode_readutf16_swap_rev_n
#define __CRT_HAVE_unicode_readutf8
#define __CRT_HAVE_unicode_readutf8_n
#define __CRT_HAVE_unicode_readutf8_rev
#define __CRT_HAVE_unicode_readutf8_rev_n
#define __CRT_HAVE_unicode_utf8seqlen
#define __CRT_HAVE_unicode_writeutf16
#define __CRT_HAVE_unicode_writeutf16_chk
#define __CRT_HAVE_unicode_writeutf8
#define __CRT_HAVE_uuid_fromstr
#define __CRT_HAVE_vsnprintf
#define __CRT_HAVE_vsprintf
#define __CRT_HAVE_vsscanf
#ifndef __arch_writeb_nopf
#define __CRT_HAVE_writeb_nopf
#endif /* !__arch_writeb_nopf */
#ifndef __arch_writel_nopf
#define __CRT_HAVE_writel_nopf
#endif /* !__arch_writel_nopf */
#ifndef __arch_writeq_nopf
#define __CRT_HAVE_writeq_nopf
#endif /* !__arch_writeq_nopf */
#ifndef __arch_writew_nopf
#define __CRT_HAVE_writew_nopf
#endif /* !__arch_writew_nopf */
