#ifndef KOS_BUILD_CONFIG_TOOLCHAIN_HOST
#define KOS_BUILD_CONFIG_TOOLCHAIN_BINUTILS_URL     "https://ftp.gnu.org/gnu/binutils/binutils-2.38.tar.gz"
#define KOS_BUILD_CONFIG_TOOLCHAIN_BINUTILS_VERSION "2.38"
#define KOS_BUILD_CONFIG_TOOLCHAIN_BINUTILS_VERSION_0 2
#define KOS_BUILD_CONFIG_TOOLCHAIN_BINUTILS_VERSION_1 38
#define KOS_BUILD_CONFIG_TOOLCHAIN_GCC_URL     "https://ftp.gnu.org/gnu/gcc/gcc-12.1.0/gcc-12.1.0.tar.gz"
#define KOS_BUILD_CONFIG_TOOLCHAIN_GCC_VERSION "12.1.0"
#define KOS_BUILD_CONFIG_TOOLCHAIN_GCC_VERSION_0 12
#define KOS_BUILD_CONFIG_TOOLCHAIN_GCC_VERSION_1 1
#define KOS_BUILD_CONFIG_TOOLCHAIN_GCC_VERSION_2 0
#define KOS_BUILD_CONFIG_TOOLCHAIN_HOST       "x86_64-pc-cygwin"
#define KOS_BUILD_CONFIG_TOOLCHAIN_HOST_ROOT  "/cygdrive/e/c/kls/kos"
#define KOS_BUILD_CONFIG_TOOLCHAIN_BUILD      "x86_64-kos"
#define KOS_BUILD_CONFIG_TOOLCHAIN_BUILD_ARCH "x86_64"
#define KOS_BUILD_CONFIG_TOOLCHAIN_BUILD_CPU  "x86_64"
#define KOS_BUILD_CONFIG_TOOLCHAIN_DATE_INFO  (1654450586,(2022,6,5,17,36,26,347227900),(2022,06,05,17,36,26,347227900))
#endif /* !KOS_BUILD_CONFIG_TOOLCHAIN_HOST */
