/* HASH CRC-32:0xa8be0c8c */
/* Copyright (c) 2019-2020 Griefer@Work                                       *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement (see the following) in the product     *
 *    documentation is required:                                              *
 *    Portions Copyright (c) 2019-2020 Griefer@Work                           *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#ifndef __ARCH_WANT_SYSCALL__LLSEEK
#define __ARCH_WANT_SYSCALL__LLSEEK                      1
#define __ARCH_WANT_SYSCALL__NEWSELECT                   1
#define __ARCH_WANT_SYSCALL__SYSCTL                      1
#define __ARCH_WANT_SYSCALL_ACCEPT4                      1
#define __ARCH_WANT_SYSCALL_ACCESS                       1
#define __ARCH_WANT_SYSCALL_ACCT                         1
#define __ARCH_WANT_SYSCALL_ADD_KEY                      1
#define __ARCH_WANT_SYSCALL_ADJTIMEX                     1
#define __ARCH_WANT_SYSCALL_AFS_SYSCALL                  1
#define __ARCH_WANT_SYSCALL_ALARM                        1
#define __ARCH_WANT_SYSCALL_BDFLUSH                      1
#define __ARCH_WANT_SYSCALL_BIND                         1
#define __ARCH_WANT_SYSCALL_BPF                          1
#define __ARCH_WANT_SYSCALL_BREAK                        1
#define __ARCH_WANT_SYSCALL_BRK                          1
#define __ARCH_WANT_SYSCALL_CAPGET                       1
#define __ARCH_WANT_SYSCALL_CAPSET                       1
#define __ARCH_WANT_SYSCALL_CHDIR                        1
#define __ARCH_WANT_SYSCALL_CHMOD                        1
#define __ARCH_WANT_SYSCALL_CHOWN                        1
#define __ARCH_WANT_SYSCALL_CHOWN32                      1
#define __ARCH_WANT_SYSCALL_CHROOT                       1
#define __ARCH_WANT_SYSCALL_CLOCK_ADJTIME                1
#define __ARCH_WANT_SYSCALL_CLOCK_ADJTIME64              1
#define __ARCH_WANT_SYSCALL_CLOCK_GETRES                 1
#define __ARCH_WANT_SYSCALL_CLOCK_GETRES_TIME64          1
#define __ARCH_WANT_SYSCALL_CLOCK_GETTIME                1
#define __ARCH_WANT_SYSCALL_CLOCK_GETTIME64              1
#define __ARCH_WANT_SYSCALL_CLOCK_NANOSLEEP              1
#define __ARCH_WANT_SYSCALL_CLOCK_NANOSLEEP_TIME64       1
#define __ARCH_WANT_SYSCALL_CLOCK_SETTIME                1
#define __ARCH_WANT_SYSCALL_CLOCK_SETTIME64              1
#define __ARCH_WANT_SYSCALL_CLONE                        1
#define __ARCH_WANT_SYSCALL_CLOSE                        1
#define __ARCH_WANT_SYSCALL_CONNECT                      1
#define __ARCH_WANT_SYSCALL_COREDUMP                     1
#define __ARCH_WANT_SYSCALL_CREAT                        1
#define __ARCH_WANT_SYSCALL_CREATE_MODULE                1
#define __ARCH_WANT_SYSCALL_DEBUGTRAP                    1
#define __ARCH_WANT_SYSCALL_DELETE_MODULE                1
#define __ARCH_WANT_SYSCALL_DETACH                       1
#define __ARCH_WANT_SYSCALL_DUP                          1
#define __ARCH_WANT_SYSCALL_DUP2                         1
#define __ARCH_WANT_SYSCALL_DUP3                         1
#define __ARCH_WANT_SYSCALL_EPOLL_CREATE                 1
#define __ARCH_WANT_SYSCALL_EPOLL_CREATE1                1
#define __ARCH_WANT_SYSCALL_EPOLL_CTL                    1
#define __ARCH_WANT_SYSCALL_EPOLL_PWAIT                  1
#define __ARCH_WANT_SYSCALL_EPOLL_WAIT                   1
#define __ARCH_WANT_SYSCALL_EVENTFD                      1
#define __ARCH_WANT_SYSCALL_EVENTFD2                     1
#define __ARCH_WANT_SYSCALL_EXECVE                       1
#define __ARCH_WANT_SYSCALL_EXECVEAT                     1
#define __ARCH_WANT_SYSCALL_EXIT                         1
#define __ARCH_WANT_SYSCALL_EXIT_GROUP                   1
#define __ARCH_WANT_SYSCALL_FACCESSAT                    1
#define __ARCH_WANT_SYSCALL_FADVISE64                    1
#define __ARCH_WANT_SYSCALL_FADVISE64_64                 1
#define __ARCH_WANT_SYSCALL_FALLOCATE                    1
#define __ARCH_WANT_SYSCALL_FALLOCATE64                  1
#define __ARCH_WANT_SYSCALL_FANOTIFY_INIT                1
#define __ARCH_WANT_SYSCALL_FANOTIFY_MARK                1
#define __ARCH_WANT_SYSCALL_FCHDIR                       1
#define __ARCH_WANT_SYSCALL_FCHDIRAT                     1
#define __ARCH_WANT_SYSCALL_FCHMOD                       1
#define __ARCH_WANT_SYSCALL_FCHMODAT                     1
#define __ARCH_WANT_SYSCALL_FCHOWN                       1
#define __ARCH_WANT_SYSCALL_FCHOWN32                     1
#define __ARCH_WANT_SYSCALL_FCHOWNAT                     1
#define __ARCH_WANT_SYSCALL_FCNTL                        1
#define __ARCH_WANT_SYSCALL_FCNTL64                      1
#define __ARCH_WANT_SYSCALL_FDATASYNC                    1
#define __ARCH_WANT_SYSCALL_FGETXATTR                    1
#define __ARCH_WANT_SYSCALL_FINIT_MODULE                 1
#define __ARCH_WANT_SYSCALL_FLISTXATTR                   1
#define __ARCH_WANT_SYSCALL_FLOCK                        1
#define __ARCH_WANT_SYSCALL_FMKDIRAT                     1
#define __ARCH_WANT_SYSCALL_FMKNODAT                     1
#define __ARCH_WANT_SYSCALL_FORK                         1
#define __ARCH_WANT_SYSCALL_FREADLINKAT                  1
#define __ARCH_WANT_SYSCALL_FREALPATH4                   1
#define __ARCH_WANT_SYSCALL_FREALPATHAT                  1
#define __ARCH_WANT_SYSCALL_FREMOVEXATTR                 1
#define __ARCH_WANT_SYSCALL_FRENAMEAT                    1
#define __ARCH_WANT_SYSCALL_FSETXATTR                    1
#define __ARCH_WANT_SYSCALL_FSMODE                       1
#define __ARCH_WANT_SYSCALL_FSTAT                        1
#define __ARCH_WANT_SYSCALL_FSTAT64                      1
#define __ARCH_WANT_SYSCALL_FSTATAT64                    1
#define __ARCH_WANT_SYSCALL_FSTATFS                      1
#define __ARCH_WANT_SYSCALL_FSTATFS64                    1
#define __ARCH_WANT_SYSCALL_FSYMLINKAT                   1
#define __ARCH_WANT_SYSCALL_FSYNC                        1
#define __ARCH_WANT_SYSCALL_FTIME                        1
#define __ARCH_WANT_SYSCALL_FTIME64                      1
#define __ARCH_WANT_SYSCALL_FTRUNCATE                    1
#define __ARCH_WANT_SYSCALL_FTRUNCATE64                  1
#define __ARCH_WANT_SYSCALL_FUTEX                        1
#define __ARCH_WANT_SYSCALL_FUTIMESAT                    1
#define __ARCH_WANT_SYSCALL_FUTIMESAT64                  1
#define __ARCH_WANT_SYSCALL_GET_EXCEPTION_HANDLER        1
#define __ARCH_WANT_SYSCALL_GET_KERNEL_SYMS              1
#define __ARCH_WANT_SYSCALL_GET_MEMPOLICY                1
#define __ARCH_WANT_SYSCALL_GET_ROBUST_LIST              1
#define __ARCH_WANT_SYSCALL_GET_THREAD_AREA              1
#define __ARCH_WANT_SYSCALL_GETCPU                       1
#define __ARCH_WANT_SYSCALL_GETCWD                       1
#define __ARCH_WANT_SYSCALL_GETDENTS                     1
#define __ARCH_WANT_SYSCALL_GETDENTS64                   1
#define __ARCH_WANT_SYSCALL_GETDRIVES                    1
#define __ARCH_WANT_SYSCALL_GETEGID                      1
#define __ARCH_WANT_SYSCALL_GETEGID32                    1
#define __ARCH_WANT_SYSCALL_GETEUID                      1
#define __ARCH_WANT_SYSCALL_GETEUID32                    1
#define __ARCH_WANT_SYSCALL_GETGID                       1
#define __ARCH_WANT_SYSCALL_GETGID32                     1
#define __ARCH_WANT_SYSCALL_GETGROUPS                    1
#define __ARCH_WANT_SYSCALL_GETGROUPS32                  1
#define __ARCH_WANT_SYSCALL_GETITIMER                    1
#define __ARCH_WANT_SYSCALL_GETITIMER64                  1
#define __ARCH_WANT_SYSCALL_GETPEERNAME                  1
#define __ARCH_WANT_SYSCALL_GETPGID                      1
#define __ARCH_WANT_SYSCALL_GETPGRP                      1
#define __ARCH_WANT_SYSCALL_GETPID                       1
#define __ARCH_WANT_SYSCALL_GETPMSG                      1
#define __ARCH_WANT_SYSCALL_GETPPID                      1
#define __ARCH_WANT_SYSCALL_GETPRIORITY                  1
#define __ARCH_WANT_SYSCALL_GETRANDOM                    1
#define __ARCH_WANT_SYSCALL_GETRESGID                    1
#define __ARCH_WANT_SYSCALL_GETRESGID32                  1
#define __ARCH_WANT_SYSCALL_GETRESUID                    1
#define __ARCH_WANT_SYSCALL_GETRESUID32                  1
#define __ARCH_WANT_SYSCALL_GETRLIMIT                    1
#define __ARCH_WANT_SYSCALL_GETRUSAGE                    1
#define __ARCH_WANT_SYSCALL_GETRUSAGE64                  1
#define __ARCH_WANT_SYSCALL_GETSID                       1
#define __ARCH_WANT_SYSCALL_GETSOCKNAME                  1
#define __ARCH_WANT_SYSCALL_GETSOCKOPT                   1
#define __ARCH_WANT_SYSCALL_GETTID                       1
#define __ARCH_WANT_SYSCALL_GETTIMEOFDAY                 1
#define __ARCH_WANT_SYSCALL_GETTIMEOFDAY64               1
#define __ARCH_WANT_SYSCALL_GETUID                       1
#define __ARCH_WANT_SYSCALL_GETUID32                     1
#define __ARCH_WANT_SYSCALL_GETXATTR                     1
#define __ARCH_WANT_SYSCALL_GTTY                         1
#define __ARCH_WANT_SYSCALL_HOP                          1
#define __ARCH_WANT_SYSCALL_HOPF                         1
#define __ARCH_WANT_SYSCALL_IDLE                         1
#define __ARCH_WANT_SYSCALL_INIT_MODULE                  1
#define __ARCH_WANT_SYSCALL_INOTIFY_ADD_WATCH            1
#define __ARCH_WANT_SYSCALL_INOTIFY_INIT                 1
#define __ARCH_WANT_SYSCALL_INOTIFY_INIT1                1
#define __ARCH_WANT_SYSCALL_INOTIFY_RM_WATCH             1
#define __ARCH_WANT_SYSCALL_IO_CANCEL                    1
#define __ARCH_WANT_SYSCALL_IO_DESTROY                   1
#define __ARCH_WANT_SYSCALL_IO_GETEVENTS                 1
#define __ARCH_WANT_SYSCALL_IO_SETUP                     1
#define __ARCH_WANT_SYSCALL_IO_SUBMIT                    1
#define __ARCH_WANT_SYSCALL_IOCTL                        1
#define __ARCH_WANT_SYSCALL_IOCTLF                       1
#define __ARCH_WANT_SYSCALL_IOPERM                       1
#define __ARCH_WANT_SYSCALL_IOPL                         1
#define __ARCH_WANT_SYSCALL_IOPRIO_GET                   1
#define __ARCH_WANT_SYSCALL_IOPRIO_SET                   1
#define __ARCH_WANT_SYSCALL_IPC                          1
#define __ARCH_WANT_SYSCALL_KCMP                         1
#define __ARCH_WANT_SYSCALL_KEXEC_LOAD                   1
#define __ARCH_WANT_SYSCALL_KEYCTL                       1
#define __ARCH_WANT_SYSCALL_KFSTAT                       1
#define __ARCH_WANT_SYSCALL_KFSTATAT                     1
#define __ARCH_WANT_SYSCALL_KILL                         1
#define __ARCH_WANT_SYSCALL_KLSTAT                       1
#define __ARCH_WANT_SYSCALL_KREADDIR                     1
#define __ARCH_WANT_SYSCALL_KREADDIRF                    1
#define __ARCH_WANT_SYSCALL_KSTAT                        1
#define __ARCH_WANT_SYSCALL_KSYSCTL                      1
#define __ARCH_WANT_SYSCALL_LCHOWN                       1
#define __ARCH_WANT_SYSCALL_LCHOWN32                     1
#define __ARCH_WANT_SYSCALL_LFUTEX                       1
#define __ARCH_WANT_SYSCALL_LFUTEXEXPR                   1
#define __ARCH_WANT_SYSCALL_LFUTEXLOCKEXPR               1
#define __ARCH_WANT_SYSCALL_LGETXATTR                    1
#define __ARCH_WANT_SYSCALL_LINK                         1
#define __ARCH_WANT_SYSCALL_LINKAT                       1
#define __ARCH_WANT_SYSCALL_LISTEN                       1
#define __ARCH_WANT_SYSCALL_LISTXATTR                    1
#define __ARCH_WANT_SYSCALL_LLISTXATTR                   1
#define __ARCH_WANT_SYSCALL_LOCK                         1
#define __ARCH_WANT_SYSCALL_LOOKUP_DCOOKIE               1
#define __ARCH_WANT_SYSCALL_LREMOVEXATTR                 1
#define __ARCH_WANT_SYSCALL_LSEEK                        1
#define __ARCH_WANT_SYSCALL_LSEEK64                      1
#define __ARCH_WANT_SYSCALL_LSETXATTR                    1
#define __ARCH_WANT_SYSCALL_LSTAT                        1
#define __ARCH_WANT_SYSCALL_LSTAT64                      1
#define __ARCH_WANT_SYSCALL_MADVISE                      1
#define __ARCH_WANT_SYSCALL_MAPLIBRARY                   1
#define __ARCH_WANT_SYSCALL_MBIND                        1
#define __ARCH_WANT_SYSCALL_MEMBARRIER                   1
#define __ARCH_WANT_SYSCALL_MEMFD_CREATE                 1
#define __ARCH_WANT_SYSCALL_MIGRATE_PAGES                1
#define __ARCH_WANT_SYSCALL_MINCORE                      1
#define __ARCH_WANT_SYSCALL_MKDIR                        1
#define __ARCH_WANT_SYSCALL_MKDIRAT                      1
#define __ARCH_WANT_SYSCALL_MKNOD                        1
#define __ARCH_WANT_SYSCALL_MKNODAT                      1
#define __ARCH_WANT_SYSCALL_MKTTY                        1
#define __ARCH_WANT_SYSCALL_MLOCK                        1
#define __ARCH_WANT_SYSCALL_MLOCK2                       1
#define __ARCH_WANT_SYSCALL_MLOCKALL                     1
#define __ARCH_WANT_SYSCALL_MMAP                         1
#define __ARCH_WANT_SYSCALL_MMAP2                        1
#define __ARCH_WANT_SYSCALL_MODIFY_LDT                   1
#define __ARCH_WANT_SYSCALL_MOUNT                        1
#define __ARCH_WANT_SYSCALL_MOVE_PAGES                   1
#define __ARCH_WANT_SYSCALL_MPROTECT                     1
#define __ARCH_WANT_SYSCALL_MPX                          1
#define __ARCH_WANT_SYSCALL_MQ_GETSETATTR                1
#define __ARCH_WANT_SYSCALL_MQ_NOTIFY                    1
#define __ARCH_WANT_SYSCALL_MQ_OPEN                      1
#define __ARCH_WANT_SYSCALL_MQ_TIMEDRECEIVE              1
#define __ARCH_WANT_SYSCALL_MQ_TIMEDRECEIVE_TIME64       1
#define __ARCH_WANT_SYSCALL_MQ_TIMEDSEND                 1
#define __ARCH_WANT_SYSCALL_MQ_TIMEDSEND_TIME64          1
#define __ARCH_WANT_SYSCALL_MQ_UNLINK                    1
#define __ARCH_WANT_SYSCALL_MREMAP                       1
#define __ARCH_WANT_SYSCALL_MSYNC                        1
#define __ARCH_WANT_SYSCALL_MUNLOCK                      1
#define __ARCH_WANT_SYSCALL_MUNLOCKALL                   1
#define __ARCH_WANT_SYSCALL_MUNMAP                       1
#define __ARCH_WANT_SYSCALL_NAME_TO_HANDLE_AT            1
#define __ARCH_WANT_SYSCALL_NANOSLEEP                    1
#define __ARCH_WANT_SYSCALL_NANOSLEEP64                  1
#define __ARCH_WANT_SYSCALL_NFSSERVCTL                   1
#define __ARCH_WANT_SYSCALL_NICE                         1
#define __ARCH_WANT_SYSCALL_OLDFSTAT                     1
#define __ARCH_WANT_SYSCALL_OLDLSTAT                     1
#define __ARCH_WANT_SYSCALL_OLDOLDUNAME                  1
#define __ARCH_WANT_SYSCALL_OLDSTAT                      1
#define __ARCH_WANT_SYSCALL_OLDUNAME                     1
#define __ARCH_WANT_SYSCALL_OPEN                         1
#define __ARCH_WANT_SYSCALL_OPEN_BY_HANDLE_AT            1
#define __ARCH_WANT_SYSCALL_OPENAT                       1
#define __ARCH_WANT_SYSCALL_OPENPTY                      1
#define __ARCH_WANT_SYSCALL_PAUSE                        1
#define __ARCH_WANT_SYSCALL_PERF_EVENT_OPEN              1
#define __ARCH_WANT_SYSCALL_PERSONALITY                  1
#define __ARCH_WANT_SYSCALL_PIPE                         1
#define __ARCH_WANT_SYSCALL_PIPE2                        1
#define __ARCH_WANT_SYSCALL_PIVOT_ROOT                   1
#define __ARCH_WANT_SYSCALL_POLL                         1
#define __ARCH_WANT_SYSCALL_PPOLL                        1
#define __ARCH_WANT_SYSCALL_PPOLL_TIME64                 1
#define __ARCH_WANT_SYSCALL_PRCTL                        1
#define __ARCH_WANT_SYSCALL_PREAD64                      1
#define __ARCH_WANT_SYSCALL_PREAD64F                     1
#define __ARCH_WANT_SYSCALL_PREADV                       1
#define __ARCH_WANT_SYSCALL_PREADVF                      1
#define __ARCH_WANT_SYSCALL_PRLIMIT64                    1
#define __ARCH_WANT_SYSCALL_PROCESS_VM_READV             1
#define __ARCH_WANT_SYSCALL_PROCESS_VM_WRITEV            1
#define __ARCH_WANT_SYSCALL_PROF                         1
#define __ARCH_WANT_SYSCALL_PROFIL                       1
#define __ARCH_WANT_SYSCALL_PSELECT6                     1
#define __ARCH_WANT_SYSCALL_PSELECT6_TIME64              1
#define __ARCH_WANT_SYSCALL_PTRACE                       1
#define __ARCH_WANT_SYSCALL_PUTPMSG                      1
#define __ARCH_WANT_SYSCALL_PWRITE64                     1
#define __ARCH_WANT_SYSCALL_PWRITE64F                    1
#define __ARCH_WANT_SYSCALL_PWRITEV                      1
#define __ARCH_WANT_SYSCALL_PWRITEVF                     1
#define __ARCH_WANT_SYSCALL_QUERY_MODULE                 1
#define __ARCH_WANT_SYSCALL_QUOTACTL                     1
#define __ARCH_WANT_SYSCALL_RAISEAT                      1
#define __ARCH_WANT_SYSCALL_READ                         1
#define __ARCH_WANT_SYSCALL_READAHEAD                    1
#define __ARCH_WANT_SYSCALL_READDIR                      1
#define __ARCH_WANT_SYSCALL_READF                        1
#define __ARCH_WANT_SYSCALL_READLINK                     1
#define __ARCH_WANT_SYSCALL_READLINKAT                   1
#define __ARCH_WANT_SYSCALL_READV                        1
#define __ARCH_WANT_SYSCALL_READVF                       1
#define __ARCH_WANT_SYSCALL_REBOOT                       1
#define __ARCH_WANT_SYSCALL_RECVFROM                     1
#define __ARCH_WANT_SYSCALL_RECVMMSG                     1
#define __ARCH_WANT_SYSCALL_RECVMMSG_TIME64              1
#define __ARCH_WANT_SYSCALL_RECVMSG                      1
#define __ARCH_WANT_SYSCALL_REMAP_FILE_PAGES             1
#define __ARCH_WANT_SYSCALL_REMOVEXATTR                  1
#define __ARCH_WANT_SYSCALL_RENAME                       1
#define __ARCH_WANT_SYSCALL_RENAMEAT                     1
#define __ARCH_WANT_SYSCALL_RENAMEAT2                    1
#define __ARCH_WANT_SYSCALL_REQUEST_KEY                  1
#define __ARCH_WANT_SYSCALL_RESTART_SYSCALL              1
#define __ARCH_WANT_SYSCALL_RMDIR                        1
#define __ARCH_WANT_SYSCALL_RPC_SCHEDULE                 1
#define __ARCH_WANT_SYSCALL_RPC_SERVICE                  1
#define __ARCH_WANT_SYSCALL_RT_SIGACTION                 1
#define __ARCH_WANT_SYSCALL_RT_SIGPENDING                1
#define __ARCH_WANT_SYSCALL_RT_SIGPROCMASK               1
#define __ARCH_WANT_SYSCALL_RT_SIGQUEUEINFO              1
#define __ARCH_WANT_SYSCALL_RT_SIGRETURN                 1
#define __ARCH_WANT_SYSCALL_RT_SIGSUSPEND                1
#define __ARCH_WANT_SYSCALL_RT_SIGTIMEDWAIT              1
#define __ARCH_WANT_SYSCALL_RT_SIGTIMEDWAIT_TIME64       1
#define __ARCH_WANT_SYSCALL_RT_TGSIGQUEUEINFO            1
#define __ARCH_WANT_SYSCALL_RTM_ABORT                    1
#define __ARCH_WANT_SYSCALL_RTM_BEGIN                    1
#define __ARCH_WANT_SYSCALL_RTM_END                      1
#define __ARCH_WANT_SYSCALL_RTM_TEST                     1
#define __ARCH_WANT_SYSCALL_SCHED_GET_PRIORITY_MAX       1
#define __ARCH_WANT_SYSCALL_SCHED_GET_PRIORITY_MIN       1
#define __ARCH_WANT_SYSCALL_SCHED_GETAFFINITY            1
#define __ARCH_WANT_SYSCALL_SCHED_GETATTR                1
#define __ARCH_WANT_SYSCALL_SCHED_GETPARAM               1
#define __ARCH_WANT_SYSCALL_SCHED_GETSCHEDULER           1
#define __ARCH_WANT_SYSCALL_SCHED_RR_GET_INTERVAL        1
#define __ARCH_WANT_SYSCALL_SCHED_RR_GET_INTERVAL_TIME64 1
#define __ARCH_WANT_SYSCALL_SCHED_SETAFFINITY            1
#define __ARCH_WANT_SYSCALL_SCHED_SETATTR                1
#define __ARCH_WANT_SYSCALL_SCHED_SETPARAM               1
#define __ARCH_WANT_SYSCALL_SCHED_SETSCHEDULER           1
#define __ARCH_WANT_SYSCALL_SCHED_YIELD                  1
#define __ARCH_WANT_SYSCALL_SECCOMP                      1
#define __ARCH_WANT_SYSCALL_SELECT                       1
#define __ARCH_WANT_SYSCALL_SELECT64                     1
#define __ARCH_WANT_SYSCALL_SENDFILE                     1
#define __ARCH_WANT_SYSCALL_SENDFILE64                   1
#define __ARCH_WANT_SYSCALL_SENDMMSG                     1
#define __ARCH_WANT_SYSCALL_SENDMSG                      1
#define __ARCH_WANT_SYSCALL_SENDTO                       1
#define __ARCH_WANT_SYSCALL_SET_EXCEPTION_HANDLER        1
#define __ARCH_WANT_SYSCALL_SET_MEMPOLICY                1
#define __ARCH_WANT_SYSCALL_SET_ROBUST_LIST              1
#define __ARCH_WANT_SYSCALL_SET_THREAD_AREA              1
#define __ARCH_WANT_SYSCALL_SET_TID_ADDRESS              1
#define __ARCH_WANT_SYSCALL_SETDOMAINNAME                1
#define __ARCH_WANT_SYSCALL_SETFSGID                     1
#define __ARCH_WANT_SYSCALL_SETFSGID32                   1
#define __ARCH_WANT_SYSCALL_SETFSUID                     1
#define __ARCH_WANT_SYSCALL_SETFSUID32                   1
#define __ARCH_WANT_SYSCALL_SETGID                       1
#define __ARCH_WANT_SYSCALL_SETGID32                     1
#define __ARCH_WANT_SYSCALL_SETGROUPS                    1
#define __ARCH_WANT_SYSCALL_SETGROUPS32                  1
#define __ARCH_WANT_SYSCALL_SETHOSTNAME                  1
#define __ARCH_WANT_SYSCALL_SETITIMER                    1
#define __ARCH_WANT_SYSCALL_SETITIMER64                  1
#define __ARCH_WANT_SYSCALL_SETNS                        1
#define __ARCH_WANT_SYSCALL_SETPGID                      1
#define __ARCH_WANT_SYSCALL_SETPRIORITY                  1
#define __ARCH_WANT_SYSCALL_SETREGID                     1
#define __ARCH_WANT_SYSCALL_SETREGID32                   1
#define __ARCH_WANT_SYSCALL_SETRESGID                    1
#define __ARCH_WANT_SYSCALL_SETRESGID32                  1
#define __ARCH_WANT_SYSCALL_SETRESUID                    1
#define __ARCH_WANT_SYSCALL_SETRESUID32                  1
#define __ARCH_WANT_SYSCALL_SETREUID                     1
#define __ARCH_WANT_SYSCALL_SETREUID32                   1
#define __ARCH_WANT_SYSCALL_SETRLIMIT                    1
#define __ARCH_WANT_SYSCALL_SETSID                       1
#define __ARCH_WANT_SYSCALL_SETSOCKOPT                   1
#define __ARCH_WANT_SYSCALL_SETTIMEOFDAY                 1
#define __ARCH_WANT_SYSCALL_SETTIMEOFDAY64               1
#define __ARCH_WANT_SYSCALL_SETUID                       1
#define __ARCH_WANT_SYSCALL_SETUID32                     1
#define __ARCH_WANT_SYSCALL_SETXATTR                     1
#define __ARCH_WANT_SYSCALL_SGETMASK                     1
#define __ARCH_WANT_SYSCALL_SHUTDOWN                     1
#define __ARCH_WANT_SYSCALL_SIGACTION                    1
#define __ARCH_WANT_SYSCALL_SIGALTSTACK                  1
#define __ARCH_WANT_SYSCALL_SIGNAL                       1
#define __ARCH_WANT_SYSCALL_SIGNALFD                     1
#define __ARCH_WANT_SYSCALL_SIGNALFD4                    1
#define __ARCH_WANT_SYSCALL_SIGPENDING                   1
#define __ARCH_WANT_SYSCALL_SIGPROCMASK                  1
#define __ARCH_WANT_SYSCALL_SIGRETURN                    1
#define __ARCH_WANT_SYSCALL_SIGSUSPEND                   1
#define __ARCH_WANT_SYSCALL_SOCKET                       1
#define __ARCH_WANT_SYSCALL_SOCKETCALL                   1
#define __ARCH_WANT_SYSCALL_SOCKETPAIR                   1
#define __ARCH_WANT_SYSCALL_SPLICE                       1
#define __ARCH_WANT_SYSCALL_SSETMASK                     1
#define __ARCH_WANT_SYSCALL_STAT                         1
#define __ARCH_WANT_SYSCALL_STAT64                       1
#define __ARCH_WANT_SYSCALL_STATFS                       1
#define __ARCH_WANT_SYSCALL_STATFS64                     1
#define __ARCH_WANT_SYSCALL_STIME                        1
#define __ARCH_WANT_SYSCALL_STIME64                      1
#define __ARCH_WANT_SYSCALL_STTY                         1
#define __ARCH_WANT_SYSCALL_SWAPOFF                      1
#define __ARCH_WANT_SYSCALL_SWAPON                       1
#define __ARCH_WANT_SYSCALL_SYMLINK                      1
#define __ARCH_WANT_SYSCALL_SYMLINKAT                    1
#define __ARCH_WANT_SYSCALL_SYNC                         1
#define __ARCH_WANT_SYSCALL_SYNC_FILE_RANGE              1
#define __ARCH_WANT_SYSCALL_SYNCFS                       1
#define __ARCH_WANT_SYSCALL_SYSFS                        1
#define __ARCH_WANT_SYSCALL_SYSINFO                      1
#define __ARCH_WANT_SYSCALL_SYSLOG                       1
#define __ARCH_WANT_SYSCALL_TEE                          1
#define __ARCH_WANT_SYSCALL_TGKILL                       1
#define __ARCH_WANT_SYSCALL_TIME                         1
#define __ARCH_WANT_SYSCALL_TIME64                       1
#define __ARCH_WANT_SYSCALL_TIMER_CREATE                 1
#define __ARCH_WANT_SYSCALL_TIMER_DELETE                 1
#define __ARCH_WANT_SYSCALL_TIMER_GETOVERRUN             1
#define __ARCH_WANT_SYSCALL_TIMER_GETTIME                1
#define __ARCH_WANT_SYSCALL_TIMER_GETTIME64              1
#define __ARCH_WANT_SYSCALL_TIMER_SETTIME                1
#define __ARCH_WANT_SYSCALL_TIMER_SETTIME64              1
#define __ARCH_WANT_SYSCALL_TIMERFD_CREATE               1
#define __ARCH_WANT_SYSCALL_TIMERFD_GETTIME              1
#define __ARCH_WANT_SYSCALL_TIMERFD_GETTIME64            1
#define __ARCH_WANT_SYSCALL_TIMERFD_SETTIME              1
#define __ARCH_WANT_SYSCALL_TIMERFD_SETTIME64            1
#define __ARCH_WANT_SYSCALL_TIMES                        1
#define __ARCH_WANT_SYSCALL_TKILL                        1
#define __ARCH_WANT_SYSCALL_TRUNCATE                     1
#define __ARCH_WANT_SYSCALL_TRUNCATE64                   1
#define __ARCH_WANT_SYSCALL_UGETRLIMIT                   1
#define __ARCH_WANT_SYSCALL_ULIMIT                       1
#define __ARCH_WANT_SYSCALL_UMASK                        1
#define __ARCH_WANT_SYSCALL_UMOUNT                       1
#define __ARCH_WANT_SYSCALL_UMOUNT2                      1
#define __ARCH_WANT_SYSCALL_UNAME                        1
#define __ARCH_WANT_SYSCALL_UNLINK                       1
#define __ARCH_WANT_SYSCALL_UNLINKAT                     1
#define __ARCH_WANT_SYSCALL_UNSHARE                      1
#define __ARCH_WANT_SYSCALL_USELIB                       1
#define __ARCH_WANT_SYSCALL_USERFAULTFD                  1
#define __ARCH_WANT_SYSCALL_USERVIOFD                    1
#define __ARCH_WANT_SYSCALL_USTAT                        1
#define __ARCH_WANT_SYSCALL_UTIME                        1
#define __ARCH_WANT_SYSCALL_UTIME64                      1
#define __ARCH_WANT_SYSCALL_UTIMENSAT                    1
#define __ARCH_WANT_SYSCALL_UTIMENSAT_TIME64             1
#define __ARCH_WANT_SYSCALL_UTIMES                       1
#define __ARCH_WANT_SYSCALL_UTIMES64                     1
#define __ARCH_WANT_SYSCALL_VFORK                        1
#define __ARCH_WANT_SYSCALL_VHANGUP                      1
#define __ARCH_WANT_SYSCALL_VM86                         1
#define __ARCH_WANT_SYSCALL_VM86OLD                      1
#define __ARCH_WANT_SYSCALL_VMSPLICE                     1
#define __ARCH_WANT_SYSCALL_VSERVER                      1
#define __ARCH_WANT_SYSCALL_WAIT4                        1
#define __ARCH_WANT_SYSCALL_WAIT4_64                     1
#define __ARCH_WANT_SYSCALL_WAITID                       1
#define __ARCH_WANT_SYSCALL_WAITID64                     1
#define __ARCH_WANT_SYSCALL_WAITPID                      1
#define __ARCH_WANT_SYSCALL_WRITE                        1
#define __ARCH_WANT_SYSCALL_WRITEF                       1
#define __ARCH_WANT_SYSCALL_WRITEV                       1
#define __ARCH_WANT_SYSCALL_WRITEVF                      1
#endif /* !__ARCH_WANT_SYSCALL__LLSEEK */
