/* HASH CRC-32:0x360cc40 */
/* Copyright (c) 2019-2021 Griefer@Work                                       *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement (see the following) in the product     *
 *    documentation is required:                                              *
 *    Portions Copyright (c) 2019-2021 Griefer@Work                           *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#define __stub__CrtDbgReport
#define __stub_$Q_CrtDbgReportW$A$AYAHHPBGH00ZZ
#define __stub__CrtDbgReportW
#define __stub__CrtGetAllocHook
#define __stub__CrtGetDumpClient
#define __stub__CrtGetReportHook
#define __stub__CrtSetAllocHook
#define __stub__CrtSetBreakAlloc
#define __stub__CrtSetDebugFillThreshold
#define __stub__CrtSetDumpClient
#define __stub__CrtSetReportFile
#define __stub__CrtSetReportHook
#define __stub__CrtSetReportHook2
#define __stub__CrtSetReportHookW2
#define __stub__CrtSetReportMode
#define __stub___control87_2
#define __stub___fpecode
#define __stub___h_errno_location
#define __stub___locale_ctype_ptr
#define __stub___locale_ctype_ptr_l
#define __stub___p___wargv
#define __stub___p___winitenv
#define __stub___p__crtAssertBusy
#define __stub___p__crtBreakAlloc
#define __stub___p__crtDbgFlag
#define __stub___p__fmode
#define __stub___p__wenviron
#define __stub___p__wpgmptr
#define __stub___pthread_register_cancel
#define __stub___pthread_register_cancel_defer
#define __stub___pthread_unregister_cancel
#define __stub___pthread_unregister_cancel_restore
#define __stub___pthread_unwind_next
#define __stub___wcserror
#define __stub___wcserror_s
#define __stub__beep
#define __stub__clearfp
#define __stub__control87
#define __stub__controlfp
#define __stub__controlfp_s
#define __stub__dupenv_s
#define __stub__fpclass
#define __stub__get_fmode
#define __stub__get_invalid_parameter_handler
#define __stub__get_output_format
#define __stub__get_printf_count_output
#define __stub__get_purecall_handler
#define __stub__getdiskfree
#define __stub__getmaxstdio
#define __stub__isctype
#define __stub__isctype_l
#define __stub__mktemp_s
#define __stub__rmtmp
#define __stub__searchenv_s
#define __stub__set_abort_behavior
#define __stub__set_controlfp
#define __stub__set_error_mode
#define __stub__set_fmode
#define __stub__set_invalid_parameter_handler
#define __stub__set_output_format
#define __stub__set_printf_count_output
#define __stub__set_purecall_handler
#define __stub__seterrormode
#define __stub__setmaxstdio
#define __stub__statusfp
#define __stub__statusfp2
#define __stub__wcserror
#define __stub__wcserror_s
#define __stub__wdupenv_s
#define __stub__wfdopen
#define __stub__wfopen_s
#define __stub__wfreopen_s
#define __stub__wfsopen
#define __stub__wfullpath
#define __stub__wgetenv
#define __stub__wgetenv_s
#define __stub__wputenv
#define __stub__wputenv_s
#define __stub__wsearchenv_s
#define __stub__wtempnam
#define __stub__wtmpnam_s
#define __stub_a64l
#define __stub___acos
#define __stub_acos
#define __stub___acosh
#define __stub_acosh
#define __stub___adjtimex
#define __stub_adjtimex
#define __stub___adjtimex64
#define __stub_adjtimex64
#define __stub___asin
#define __stub_asin
#define __stub___asinh
#define __stub_asinh
#define __stub___atanh
#define __stub_atanh
#define __stub_bindresvport
#define __stub_bindresvport6
#define __stub_clock
#define __stub_clock_adjtime
#define __stub_clock_adjtime64
#define __stub___clock_getcpuclockid
#define __stub_clock_getcpuclockid
#define __stub_closelog
#define __stub___cos
#define __stub_cos
#define __stub___cosh
#define __stub_cosh
#define __stub_crypt
#define __stub_crypt_r
#define __stub_devname_r
#define __stub_drand48
#define __stub_drand48_r
#define __stub___duplocale
#define __stub_duplocale
#define __stub_encrypt
#define __stub_encrypt_r
#define __stub_endaliasent
#define __stub_endgrent
#define __stub_endhostent
#define __stub_endnetent
#define __stub_endnetgrent
#define __stub_endprotoent
#define __stub_endrpcent
#define __stub_endservent
#define __stub_endspent
#define __stub_endttyent
#define __stub_endusershell
#define __stub_endutent
#define __stub_endutxent
#define __stub_erand48
#define __stub_erand48_r
#define __stub___erf
#define __stub_erf
#define __stub___erfc
#define __stub_erfc
#define __stub_ether_hostton
#define __stub_ether_ntohost
#define __stub___exp10
#define __stub_exp10
#define __stub___exp2
#define __stub_exp2
#define __stub_fattach
#define __stub_fdetach
#define __stub_fgetgrent
#define __stub_fgetgrent_r
#define __stub_fgetln
#define __stub_fgetspent
#define __stub_fgetspent_r
#define __stub_fmtcheck
#ifdef __LIBCCALL_IS_LIBDCALL
#define __stub__fpreset
#endif /* __LIBCCALL_IS_LIBDCALL */
#define __stub_fpreset
#define __stub_freeaddrinfo
#define __stub_freeifaddrs
#define __stub___freelocale
#define __stub_freelocale
#define __stub_ftok
#define __stub_fts64_children
#define __stub_fts64_close
#define __stub_fts64_open
#define __stub_fts64_read
#define __stub_fts64_set
#define __stub_fts_children
#define __stub_fts_close
#define __stub_fts_open
#define __stub_fts_read
#define __stub_fts_set
#define __stub_ftw
#define __stub_ftw64
#define __stub_gai_cancel
#define __stub_gai_error
#define __stub_gai_strerror
#define __stub_gai_suspend
#define __stub_gai_suspend64
#define __stub_get_nprocs
#define __stub_get_nprocs_conf
#define __stub_getaddrinfo
#define __stub_getaddrinfo_a
#define __stub_getaliasbyname
#define __stub_getaliasbyname_r
#define __stub_getaliasent
#define __stub_getaliasent_r
#define __stub_getdate
#define __stub_getenv_s
#define __stub_getgrent
#define __stub_getgrent_r
#define __stub_getgrgid
#define __stub_getgrgid_r
#define __stub_getgrnam
#define __stub_getgrnam_r
#define __stub_getgrouplist
#define __stub_gethostbyaddr
#define __stub_gethostbyaddr_r
#define __stub_gethostbyname
#define __stub_gethostbyname2
#define __stub_gethostbyname2_r
#define __stub_gethostbyname_r
#define __stub_gethostent
#define __stub_gethostent_r
#define __stub_getifaddrs
#define __stub_getipv4sourcefilter
#define __stub_getloadavg
#define __stub_getmsg
#define __stub_getnameinfo
#define __stub_getnetbyaddr
#define __stub_getnetbyaddr_r
#define __stub_getnetbyname
#define __stub_getnetbyname_r
#define __stub_getnetent
#define __stub_getnetent_r
#define __stub_getnetgrent
#define __stub_getnetgrent_r
#define __stub_getpass
#define __stub_getpmsg
#define __stub_getprotobyname
#define __stub_getprotobyname_r
#define __stub_getprotobynumber
#define __stub_getprotobynumber_r
#define __stub_getprotoent
#define __stub_getprotoent_r
#define __stub_getpt
#define __stub_getrlimit64
#define __stub_getrpcbyname
#define __stub_getrpcbyname_r
#define __stub_getrpcbynumber
#define __stub_getrpcbynumber_r
#define __stub_getrpcent
#define __stub_getrpcent_r
#define __stub_getrusage64
#define __stub_getservbyname
#define __stub_getservbyname_r
#define __stub_getservbyport
#define __stub_getservbyport_r
#define __stub_getservent
#define __stub_getservent_r
#define __stub_getsourcefilter
#define __stub_getspent
#define __stub_getspent_r
#define __stub_getspnam
#define __stub_getspnam_r
#define __stub_getttyent
#define __stub_getttynam
#define __stub_getusershell
#define __stub_getutent
#define __stub_getutent_r
#define __stub_getutid
#define __stub_getutid_r
#define __stub_getutline
#define __stub_getutline_r
#define __stub_getutmp
#define __stub_getutmpx
#define __stub_getutxent
#define __stub_getutxid
#define __stub_getutxline
#define __stub_globfree
#define __stub_globfree64
#define __stub_grantpt
#define __stub_gtty
#define __stub_herror
#define __stub_hstrerror
#define __stub___hypot
#define __stub_hypot
#define __stub_if_freenameindex
#define __stub_if_indextoname
#define __stub_if_nameindex
#define __stub_if_nametoindex
#define __stub_inet6_opt_append
#define __stub_inet6_opt_find
#define __stub_inet6_opt_finish
#define __stub_inet6_opt_get_val
#define __stub_inet6_opt_init
#define __stub_inet6_opt_next
#define __stub_inet6_opt_set_val
#define __stub_inet6_option_alloc
#define __stub_inet6_option_append
#define __stub_inet6_option_find
#define __stub_inet6_option_init
#define __stub_inet6_option_next
#define __stub_inet6_option_space
#define __stub_inet6_rth_add
#define __stub_inet6_rth_getaddr
#define __stub_inet6_rth_init
#define __stub_inet6_rth_reverse
#define __stub_inet6_rth_segments
#define __stub_inet6_rth_space
#define __stub_inet_net_ntop
#define __stub_inet_net_pton
#define __stub_inet_nsap_addr
#define __stub_inet_nsap_ntoa
#define __stub_inet_ntop
#define __stub_inet_pton
#define __stub_initgroups
#define __stub_initstate
#define __stub_initstate_r
#define __stub_innetgr
#define __stub_iruserok
#define __stub_iruserok_af
#define __stub_isastream
#define __stub___j0
#define __stub_j0
#define __stub___j1
#define __stub_j1
#define __stub___jn
#define __stub_jn
#define __stub_jrand48
#define __stub_jrand48_r
#define __stub_klogctl
#define __stub_l64a
#define __stub_lckpwdf
#define __stub_lcong48
#define __stub_lcong48_r
#define __stub_gamma
#define __stub___lgamma
#define __stub___gamma
#define __stub_lgamma
#define __stub___lgamma_r
#define __stub_lgamma_r
#define __stub_lockf64
#define __stub___log
#define __stub_log
#define __stub___log10
#define __stub_log10
#define __stub___log1p
#define __stub_log1p
#define __stub___log2
#define __stub_log2
#define __stub___logb
#ifdef __LIBCCALL_IS_LIBDCALL
#define __stub__logb
#endif /* __LIBCCALL_IS_LIBDCALL */
#define __stub_logb
#define __stub_login
#define __stub_logout
#define __stub_logwtmp
#define __stub_lrand48
#define __stub_lrand48_r
#define __stub_mbsnrtowcs
#define __stub_mrand48
#define __stub_mrand48_r
#define __stub_msgctl
#define __stub_msgget
#define __stub_msgrcv
#define __stub_msgsnd
#define __stub___newlocale
#define __stub_newlocale
#define __stub_nftw
#define __stub_nftw64
#define __stub_nrand48
#define __stub_nrand48_r
#define __stub_ntp_adjtime
#define __stub_ntp_adjtime64
#define __stub_ntp_gettimex
#define __stub_ntp_gettimex64
#define __stub_obstack_vprintf
#define __stub_open_wmemstream
#define __stub_opendev
#define __stub_openlog
#ifdef __LIBCCALL_IS_LIBDCALL
#define __stub__popen
#endif /* __LIBCCALL_IS_LIBDCALL */
#define __stub__IO_popen
#define __stub_popen
#define __stub_posix_fadvise64
#define __stub_posix_fallocate64
#define __stub_posix_openpt
#define __stub_pthread_atfork
#define __stub_pthread_barrier_destroy
#define __stub_pthread_barrier_init
#define __stub_pthread_barrier_wait
#define __stub_pthread_getcpuclockid
#define __stub_pthread_mutex_consistent_np
#define __stub_pthread_mutex_consistent
#define __stub_pthread_mutex_getprioceiling
#define __stub_pthread_mutex_setprioceiling
#define __stub_pthread_rwlock_destroy
#define __stub_pthread_rwlock_init
#define __stub_pthread_rwlock_rdlock
#define __stub_pthread_rwlock_reltimedrdlock64_np
#define __stub_pthread_rwlock_reltimedrdlock_np
#define __stub_pthread_rwlock_reltimedwrlock64_np
#define __stub_pthread_rwlock_reltimedwrlock_np
#define __stub_pthread_rwlock_timedrdlock
#define __stub_pthread_rwlock_timedrdlock64
#define __stub_pthread_rwlock_timedwrlock
#define __stub_pthread_rwlock_timedwrlock64
#define __stub_pthread_rwlock_tryrdlock
#define __stub_pthread_rwlock_trywrlock
#define __stub_pthread_rwlock_unlock
#define __stub_pthread_rwlock_wrlock
#define __stub_pthread_setcancelstate
#define __stub_pthread_setcanceltype
#define __stub_ptsname_r
#define __stub_putgrent
#define __stub_putmsg
#define __stub_putpmsg
#define __stub_putspent
#define __stub_pututline
#define __stub_pututxline
#define __stub_random_r
#define __stub_rcmd
#define __stub_rcmd_af
#define __stub_re_match_2
#define __stub_re_search_2
#define __stub_re_set_registers
#define __stub_regcomp
#define __stub_regerror
#define __stub_regexec
#define __stub___remquo
#define __stub_remquo
#define __stub_revoke
#define __stub_rexec
#define __stub_rexec_af
#define __stub_rresvport
#define __stub_rresvport_af
#define __stub_ruserok
#define __stub_ruserok_af
#define __stub_seed48
#define __stub_seed48_r
#define __stub_semctl
#define __stub_semget
#define __stub_semop
#define __stub_semtimedop
#define __stub_setaliasent
#define __stub_setgrent
#define __stub_sethostent
#define __stub_setipv4sourcefilter
#define __stub_setkey
#define __stub_setkey_r
#define __stub_setlogin
#define __stub_setlogmask
#define __stub_setnetent
#define __stub_setnetgrent
#define __stub_setproctitle
#define __stub_setprotoent
#define __stub_setrlimit64
#define __stub_setrpcent
#define __stub_setservent
#define __stub_setsourcefilter
#define __stub_setspent
#define __stub_setstate
#define __stub_setstate_r
#define __stub_setttyent
#define __stub_setusershell
#define __stub_setutent
#define __stub_setutxent
#define __stub_sgetspent
#define __stub_sgetspent_r
#define __stub_shmat
#define __stub_shmctl
#define __stub_shmdt
#define __stub_shmget
#define __stub_sigreturn
#define __stub___sin
#define __stub_sin
#define __stub___sincos
#define __stub_sincos
#define __stub___sinh
#define __stub_sinh
#define __stub_srand48
#define __stub_srand48_r
#define __stub_srandom_r
#define __stub_strfmon
#define __stub___strfmon_l
#define __stub_strfmon_l
#define __stub_stty
#define __stub___tan
#define __stub_tan
#define __stub___tanh
#define __stub_tanh
#ifdef __LIBCCALL_IS_LIBDCALL
#define __stub__tempnam
#endif /* __LIBCCALL_IS_LIBDCALL */
#define __stub_tempnam
#define __stub___tgamma
#define __stub_tgamma
#define __stub_timespec_get
#define __stub_tmpfile
#define __stub_tmpnam
#define __stub_ttyslot
#define __stub_tzset
#define __stub_ulckpwdf
#define __stub_updwtmp
#define __stub_updwtmpx
#define __stub___uselocale
#define __stub_uselocale
#define __stub_utmpname
#define __stub_utmpxname
#define __stub_vfwscanf
#define __stub_vfwscanf_unlocked
#define __stub_vhangup
#define __stub_wcsnrtombs
#define __stub_wfreadlinkat
#define __stub_wttyname
#define __stub_wttyname_r
#define __stub___y0
#define __stub_y0
#define __stub___y1
#define __stub_y1
#define __stub___yn
#define __stub_yn
#define __stub_DOS$__p___wargv
#define __stub_DOS$__p___winitenv
#define __stub_DOS$__p__wenviron
#define __stub_DOS$__p__wpgmptr
#define __stub_DOS$__wcserror
#define __stub_DOS$__wcserror_s
#define __stub_DOS$_wcserror
#define __stub_DOS$_wcserror_s
#define __stub_DOS$_wdupenv_s
#define __stub_DOS$_wfdopen
#define __stub_DOS$_wfopen_s
#define __stub_DOS$_wfreopen_s
#define __stub_DOS$_wfsopen
#define __stub_DOS$_wfullpath
#define __stub_DOS$_wgetenv
#define __stub_DOS$_wgetenv_s
#define __stub_DOS$_wputenv
#define __stub_DOS$_wputenv_s
#define __stub_DOS$_wsearchenv_s
#define __stub_DOS$_wtempnam
#define __stub_DOS$_wtmpnam_s
#define __stub_DOS$mbsnrtowcs
#define __stub_DOS$open_wmemstream
#ifndef __LIBCCALL_IS_LIBDCALL
#define __stub_DOS$semctl
#define __stub_DOS$setproctitle
#define __stub_DOS$strfmon
#define __stub_DOS$__strfmon_l
#define __stub_DOS$strfmon_l
#endif /* !__LIBCCALL_IS_LIBDCALL */
#define __stub_DOS$vfwscanf
#define __stub_DOS$vfwscanf_unlocked
#define __stub_DOS$wcsnrtombs
#define __stub_DOS$wfreadlinkat
#define __stub_DOS$wttyname
#define __stub_DOS$wttyname_r
