/* HASH CRC-32:0xf145d086 */
/* Copyright (c) 2019 Griefer@Work                                            *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement in the product documentation would be  *
 *    appreciated but is not required.                                        *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#define __stub_FPathConf 1
#define __stub_PathConf 1
#define __stub___control87_2 1
#define __stub___doserrno 1
#define __stub___fpclassify 1
#define __stub___fpecode 1
#define __stub___h_errno_location 1
#define __stub___issignaling 1
#define __stub___locale_ctype_ptr 1
#define __stub___locale_ctype_ptr_l 1
#define __stub___p___wargv 1
#define __stub___p___winitenv 1
#define __stub___p__wenviron 1
#define __stub___p__wpgmptr 1
#define __stub___pthread_register_cancel 1
#define __stub___pthread_register_cancel_defer 1
#define __stub___pthread_unregister_cancel 1
#define __stub___pthread_unregister_cancel_restore 1
#define __stub___pthread_unwind_next 1
#define __stub___signbit 1
#define __stub___wcserror 1
#define __stub___wcserror_s 1
#define __stub__aligned_free 1
#define __stub__aligned_malloc 1
#define __stub__aligned_offset_malloc 1
#define __stub__aligned_offset_realloc 1
#define __stub__aligned_offset_recalloc 1
#define __stub__aligned_realloc 1
#define __stub__aligned_recalloc 1
#define __stub__beep 1
#define __stub__beginthread 1
#define __stub__beginthreadex 1
#define __stub__c_exit 1
#define __stub__cexit 1
#define __stub__clearfp 1
#define __stub__control87 1
#define __stub__controlfp 1
#define __stub__controlfp_s 1
#define __stub__dupenv_s 1
#define __stub__endthread 1
#define __stub__endthreadex 1
#define __stub__findclose 1
#define __stub__findfirst32 1
#define __stub__findfirst32i64 1
#define __stub__findfirst64i32 1
#define __stub__findnext32 1
#define __stub__findnext32i64 1
#define __stub__findnext64 1
#define __stub__fpclass 1
#define __stub__fullpath 1
#define __stub__get_doserrno 1
#define __stub__get_output_format 1
#define __stub__get_printf_count_output 1
#define __stub__getdiskfree 1
#define __stub__getmaxstdio 1
#define __stub__isctype 1
#define __stub__isctype_l 1
#define __stub__mktemp_s 1
#define __stub__recalloc 1
#define __stub__rmtmp 1
#define __stub__searchenv_s 1
#define __stub__set_controlfp 1
#define __stub__set_doserrno 1
#define __stub__set_error_mode 1
#define __stub__set_output_format 1
#define __stub__set_printf_count_output 1
#define __stub__seterrormode 1
#define __stub__setmaxstdio 1
#define __stub__statusfp 1
#define __stub__statusfp2 1
#define __stub__wcserror 1
#define __stub__wcserror_s 1
#define __stub__wperror 1
#define __stub_a64l 1
#define __stub_acos 1
#define __stub_acosh 1
#define __stub_addmntent 1
#define __stub_adjtimex 1
#define __stub_adjtimex64 1
#define __stub_asin 1
#define __stub_asinh 1
#define __stub_at_quick_exit 1
#define __stub_atan 1
#define __stub_atan2 1
#define __stub_atanh 1
#define __stub_atexit 1
#define __stub_backtrace 1
#define __stub_backtrace_symbols 1
#define __stub_backtrace_symbols_fd 1
#define __stub_bindresvport 1
#define __stub_bindresvport6 1
#define __stub_cbrt 1
#define __stub_clearenv 1
#define __stub_clock 1
#define __stub_clock_getcpuclockid 1
#define __stub_closelog 1
#define __stub_confstr 1
#define __stub_cos 1
#define __stub_cosh 1
#define __stub_crypt 1
#define __stub_crypt_r 1
#define __stub_daemon 1
#define __stub_drand48 1
#define __stub_drand48_r 1
#define __stub_drem 1
#define __stub_duplocale 1
#define __stub_encrypt 1
#define __stub_encrypt_r 1
#define __stub_endaliasent 1
#define __stub_endgrent 1
#define __stub_endhostent 1
#define __stub_endmntent 1
#define __stub_endnetent 1
#define __stub_endnetgrent 1
#define __stub_endprotoent 1
#define __stub_endpwent 1
#define __stub_endrpcent 1
#define __stub_endservent 1
#define __stub_endspent 1
#define __stub_endttyent 1
#define __stub_endusershell 1
#define __stub_endutent 1
#define __stub_endutxent 1
#define __stub_erand48 1
#define __stub_erand48_r 1
#define __stub_erf 1
#define __stub_erfc 1
#define __stub_ether_aton 1
#define __stub_ether_aton_r 1
#define __stub_ether_hostton 1
#define __stub_ether_line 1
#define __stub_ether_ntoa 1
#define __stub_ether_ntoa_r 1
#define __stub_ether_ntohost 1
#define __stub_exp 1
#define __stub_exp10 1
#define __stub_exp2 1
#define __stub_expm1 1
#define __stub_fattach 1
#define __stub_fdetach 1
#define __stub_fgetgrent 1
#define __stub_fgetgrent_r 1
#define __stub_fgetpwent 1
#define __stub_fgetpwent_r 1
#define __stub_fgetspent 1
#define __stub_fgetspent_r 1
#define __stub_fgetwc 1
#define __stub_fgetwc_unlocked 1
#define __stub_fmemopen 1
#define __stub_fmod 1
#define __stub_fopencookie 1
#define __stub_fpathconf 1
#define __stub_fpreset 1
#define __stub_fputwc 1
#define __stub_fputwc_unlocked 1
#define __stub_freeaddrinfo 1
#define __stub_freeifaddrs 1
#define __stub_freelocale 1
#define __stub_frexp 1
#define __stub_ftok 1
#define __stub_fwscanf_unlocked 1
#define __stub_gai_cancel 1
#define __stub_gai_error 1
#define __stub_gai_strerror 1
#define __stub_gai_suspend 1
#define __stub_gai_suspend64 1
#define __stub_getaddrinfo 1
#define __stub_getaddrinfo_a 1
#define __stub_getaliasbyname 1
#define __stub_getaliasbyname_r 1
#define __stub_getaliasent 1
#define __stub_getaliasent_r 1
#define __stub_getcontext 1
#define __stub_getdate 1
#define __stub_getdate_r 1
#define __stub_getenv_s 1
#define __stub_getgrent 1
#define __stub_getgrent_r 1
#define __stub_getgrgid 1
#define __stub_getgrgid_r 1
#define __stub_getgrnam 1
#define __stub_getgrnam_r 1
#define __stub_getgrouplist 1
#define __stub_gethostbyaddr 1
#define __stub_gethostbyaddr_r 1
#define __stub_gethostbyname 1
#define __stub_gethostbyname2 1
#define __stub_gethostbyname2_r 1
#define __stub_gethostbyname_r 1
#define __stub_gethostent 1
#define __stub_gethostent_r 1
#define __stub_gethostid 1
#define __stub_getifaddrs 1
#define __stub_getipv4sourcefilter 1
#define __stub_getloadavg 1
#define __stub_getlogin 1
#define __stub_getlogin_r 1
#define __stub_getmntent 1
#define __stub_getmntent_r 1
#define __stub_getmsg 1
#define __stub_getnameinfo 1
#define __stub_getnetbyaddr 1
#define __stub_getnetbyaddr_r 1
#define __stub_getnetbyname 1
#define __stub_getnetbyname_r 1
#define __stub_getnetent 1
#define __stub_getnetent_r 1
#define __stub_getnetgrent 1
#define __stub_getnetgrent_r 1
#define __stub_getpass 1
#define __stub_getpmsg 1
#define __stub_getprotobyname 1
#define __stub_getprotobyname_r 1
#define __stub_getprotobynumber 1
#define __stub_getprotobynumber_r 1
#define __stub_getprotoent 1
#define __stub_getprotoent_r 1
#define __stub_getpt 1
#define __stub_getpw 1
#define __stub_getpwent 1
#define __stub_getpwent_r 1
#define __stub_getpwnam 1
#define __stub_getpwnam_r 1
#define __stub_getpwuid 1
#define __stub_getpwuid_r 1
#define __stub_getrlimit64 1
#define __stub_getrpcbyname 1
#define __stub_getrpcbyname_r 1
#define __stub_getrpcbynumber 1
#define __stub_getrpcbynumber_r 1
#define __stub_getrpcent 1
#define __stub_getrpcent_r 1
#define __stub_getservbyname 1
#define __stub_getservbyname_r 1
#define __stub_getservbyport 1
#define __stub_getservbyport_r 1
#define __stub_getservent 1
#define __stub_getservent_r 1
#define __stub_getsourcefilter 1
#define __stub_getspent 1
#define __stub_getspent_r 1
#define __stub_getspnam 1
#define __stub_getspnam_r 1
#define __stub_getttyent 1
#define __stub_getttynam 1
#define __stub_getusershell 1
#define __stub_getutent 1
#define __stub_getutent_r 1
#define __stub_getutid 1
#define __stub_getutid_r 1
#define __stub_getutline 1
#define __stub_getutline_r 1
#define __stub_getutmp 1
#define __stub_getutmpx 1
#define __stub_getutxent 1
#define __stub_getutxid 1
#define __stub_getutxline 1
#define __stub_grantpt 1
#define __stub_gtty 1
#define __stub_herror 1
#define __stub_hstrerror 1
#define __stub_hypot 1
#define __stub_if_freenameindex 1
#define __stub_if_indextoname 1
#define __stub_if_nameindex 1
#define __stub_if_nametoindex 1
#define __stub_ilogb 1
#define __stub_inet6_opt_append 1
#define __stub_inet6_opt_find 1
#define __stub_inet6_opt_finish 1
#define __stub_inet6_opt_get_val 1
#define __stub_inet6_opt_init 1
#define __stub_inet6_opt_next 1
#define __stub_inet6_opt_set_val 1
#define __stub_inet6_option_alloc 1
#define __stub_inet6_option_append 1
#define __stub_inet6_option_find 1
#define __stub_inet6_option_init 1
#define __stub_inet6_option_next 1
#define __stub_inet6_option_space 1
#define __stub_inet6_rth_add 1
#define __stub_inet6_rth_getaddr 1
#define __stub_inet6_rth_init 1
#define __stub_inet6_rth_reverse 1
#define __stub_inet6_rth_segments 1
#define __stub_inet6_rth_space 1
#define __stub_inet_addr 1
#define __stub_inet_aton 1
#define __stub_inet_lnaof 1
#define __stub_inet_net_ntop 1
#define __stub_inet_net_pton 1
#define __stub_inet_neta 1
#define __stub_inet_netof 1
#define __stub_inet_network 1
#define __stub_inet_nsap_addr 1
#define __stub_inet_nsap_ntoa 1
#define __stub_inet_ntoa 1
#define __stub_inet_ntop 1
#define __stub_inet_pton 1
#define __stub_initgroups 1
#define __stub_initstate 1
#define __stub_initstate_r 1
#define __stub_innetgr 1
#define __stub_iruserok 1
#define __stub_iruserok_af 1
#define __stub_isastream 1
#define __stub_j0 1
#define __stub_j1 1
#define __stub_jn 1
#define __stub_jrand48 1
#define __stub_jrand48_r 1
#define __stub_klogctl 1
#define __stub_l64a 1
#define __stub_lckpwdf 1
#define __stub_lcong48 1
#define __stub_lcong48_r 1
#define __stub_ldexp 1
#define __stub_lgamma 1
#define __stub_lgamma_r 1
#define __stub_llrint 1
#define __stub_localeconv 1
#define __stub_lockf64 1
#define __stub_log 1
#define __stub_log10 1
#define __stub_log1p 1
#define __stub_log2 1
#define __stub_logb 1
#define __stub_login 1
#define __stub_login_tty 1
#define __stub_logout 1
#define __stub_logwtmp 1
#define __stub_lrand48 1
#define __stub_lrand48_r 1
#define __stub_lrint 1
#define __stub_makecontext 1
#define __stub_mbsnrtowcs 1
#define __stub_mkdtemp 1
#define __stub_mkostemp 1
#define __stub_mkostemp64 1
#define __stub_mkostemps 1
#define __stub_mkostemps64 1
#define __stub_mkstemp 1
#define __stub_mkstemps 1
#define __stub_mkstemps64 1
#define __stub_mktemp 1
#define __stub_modf 1
#define __stub_mrand48 1
#define __stub_mrand48_r 1
#define __stub_msgctl 1
#define __stub_msgget 1
#define __stub_msgrcv 1
#define __stub_msgsnd 1
#define __stub_nearbyint 1
#define __stub_newlocale 1
#define __stub_nextafter 1
#define __stub_nexttoward 1
#define __stub_nrand48 1
#define __stub_nrand48_r 1
#define __stub_ntp_adjtime 1
#define __stub_ntp_adjtime64 1
#define __stub_ntp_gettime 1
#define __stub_ntp_gettime64 1
#define __stub_obstack_vprintf 1
#define __stub_on_exit 1
#define __stub_onexit 1
#define __stub_open_memstream 1
#define __stub_open_wmemstream 1
#define __stub_openlog 1
#define __stub_pathconf 1
#define __stub_pclose 1
#define __stub_popen 1
#define __stub_posix_fadvise64 1
#define __stub_posix_fallocate64 1
#define __stub_posix_madvise 1
#define __stub_posix_openpt 1
#define __stub_posix_spawn 1
#define __stub_posix_spawn_file_actions_addclose 1
#define __stub_posix_spawn_file_actions_adddup2 1
#define __stub_posix_spawn_file_actions_addopen 1
#define __stub_posix_spawn_file_actions_destroy 1
#define __stub_posix_spawn_file_actions_init 1
#define __stub_posix_spawnattr_destroy 1
#define __stub_posix_spawnattr_getflags 1
#define __stub_posix_spawnattr_getpgroup 1
#define __stub_posix_spawnattr_getschedparam 1
#define __stub_posix_spawnattr_getschedpolicy 1
#define __stub_posix_spawnattr_getsigdefault 1
#define __stub_posix_spawnattr_getsigmask 1
#define __stub_posix_spawnattr_init 1
#define __stub_posix_spawnattr_setflags 1
#define __stub_posix_spawnattr_setpgroup 1
#define __stub_posix_spawnattr_setschedparam 1
#define __stub_posix_spawnattr_setschedpolicy 1
#define __stub_posix_spawnattr_setsigdefault 1
#define __stub_posix_spawnattr_setsigmask 1
#define __stub_posix_spawnp 1
#define __stub_pow 1
#define __stub_pow10 1
#define __stub_preadv 1
#define __stub_preadv64 1
#define __stub_prlimit 1
#define __stub_prlimit64 1
#define __stub_process_vm_readv 1
#define __stub_process_vm_writev 1
#define __stub_psiginfo 1
#define __stub_psignal 1
#define __stub_pthread_atfork 1
#define __stub_pthread_attr_destroy 1
#define __stub_pthread_attr_getaffinity_np 1
#define __stub_pthread_attr_getdetachstate 1
#define __stub_pthread_attr_getguardsize 1
#define __stub_pthread_attr_getinheritsched 1
#define __stub_pthread_attr_getschedparam 1
#define __stub_pthread_attr_getschedpolicy 1
#define __stub_pthread_attr_getscope 1
#define __stub_pthread_attr_getstack 1
#define __stub_pthread_attr_getstackaddr 1
#define __stub_pthread_attr_getstacksize 1
#define __stub_pthread_attr_init 1
#define __stub_pthread_attr_setaffinity_np 1
#define __stub_pthread_attr_setdetachstate 1
#define __stub_pthread_attr_setguardsize 1
#define __stub_pthread_attr_setinheritsched 1
#define __stub_pthread_attr_setschedparam 1
#define __stub_pthread_attr_setschedpolicy 1
#define __stub_pthread_attr_setscope 1
#define __stub_pthread_attr_setstack 1
#define __stub_pthread_attr_setstackaddr 1
#define __stub_pthread_attr_setstacksize 1
#define __stub_pthread_barrier_destroy 1
#define __stub_pthread_barrier_init 1
#define __stub_pthread_barrier_wait 1
#define __stub_pthread_barrierattr_destroy 1
#define __stub_pthread_barrierattr_getpshared 1
#define __stub_pthread_barrierattr_init 1
#define __stub_pthread_barrierattr_setpshared 1
#define __stub_pthread_cancel 1
#define __stub_pthread_cond_broadcast 1
#define __stub_pthread_cond_destroy 1
#define __stub_pthread_cond_init 1
#define __stub_pthread_cond_signal 1
#define __stub_pthread_cond_timedwait 1
#define __stub_pthread_cond_wait 1
#define __stub_pthread_condattr_destroy 1
#define __stub_pthread_condattr_getclock 1
#define __stub_pthread_condattr_getpshared 1
#define __stub_pthread_condattr_init 1
#define __stub_pthread_condattr_setclock 1
#define __stub_pthread_condattr_setpshared 1
#define __stub_pthread_create 1
#define __stub_pthread_detach 1
#define __stub_pthread_exit 1
#define __stub_pthread_getaffinity_np 1
#define __stub_pthread_getattr_default_np 1
#define __stub_pthread_getattr_np 1
#define __stub_pthread_getconcurrency 1
#define __stub_pthread_getcpuclockid 1
#define __stub_pthread_getname_np 1
#define __stub_pthread_getschedparam 1
#define __stub_pthread_getspecific 1
#define __stub_pthread_join 1
#define __stub_pthread_key_create 1
#define __stub_pthread_key_delete 1
#define __stub_pthread_kill 1
#define __stub_pthread_mutex_consistent 1
#define __stub_pthread_mutex_consistent_np 1
#define __stub_pthread_mutex_destroy 1
#define __stub_pthread_mutex_getprioceiling 1
#define __stub_pthread_mutex_init 1
#define __stub_pthread_mutex_lock 1
#define __stub_pthread_mutex_setprioceiling 1
#define __stub_pthread_mutex_timedlock 1
#define __stub_pthread_mutex_trylock 1
#define __stub_pthread_mutex_unlock 1
#define __stub_pthread_mutexattr_destroy 1
#define __stub_pthread_mutexattr_getprioceiling 1
#define __stub_pthread_mutexattr_getprotocol 1
#define __stub_pthread_mutexattr_getpshared 1
#define __stub_pthread_mutexattr_getrobust 1
#define __stub_pthread_mutexattr_getrobust_np 1
#define __stub_pthread_mutexattr_gettype 1
#define __stub_pthread_mutexattr_init 1
#define __stub_pthread_mutexattr_setprioceiling 1
#define __stub_pthread_mutexattr_setprotocol 1
#define __stub_pthread_mutexattr_setpshared 1
#define __stub_pthread_mutexattr_setrobust 1
#define __stub_pthread_mutexattr_setrobust_np 1
#define __stub_pthread_mutexattr_settype 1
#define __stub_pthread_once 1
#define __stub_pthread_rwlock_destroy 1
#define __stub_pthread_rwlock_init 1
#define __stub_pthread_rwlock_rdlock 1
#define __stub_pthread_rwlock_timedrdlock 1
#define __stub_pthread_rwlock_timedwrlock 1
#define __stub_pthread_rwlock_tryrdlock 1
#define __stub_pthread_rwlock_trywrlock 1
#define __stub_pthread_rwlock_unlock 1
#define __stub_pthread_rwlock_wrlock 1
#define __stub_pthread_rwlockattr_destroy 1
#define __stub_pthread_rwlockattr_getkind_np 1
#define __stub_pthread_rwlockattr_getpshared 1
#define __stub_pthread_rwlockattr_init 1
#define __stub_pthread_rwlockattr_setkind_np 1
#define __stub_pthread_rwlockattr_setpshared 1
#define __stub_pthread_self 1
#define __stub_pthread_setaffinity_np 1
#define __stub_pthread_setattr_default_np 1
#define __stub_pthread_setcancelstate 1
#define __stub_pthread_setcanceltype 1
#define __stub_pthread_setconcurrency 1
#define __stub_pthread_setname_np 1
#define __stub_pthread_setschedparam 1
#define __stub_pthread_setschedprio 1
#define __stub_pthread_setspecific 1
#define __stub_pthread_sigmask 1
#define __stub_pthread_sigqueue 1
#define __stub_pthread_spin_destroy 1
#define __stub_pthread_spin_init 1
#define __stub_pthread_spin_lock 1
#define __stub_pthread_spin_trylock 1
#define __stub_pthread_spin_unlock 1
#define __stub_pthread_testcancel 1
#define __stub_pthread_timedjoin_np 1
#define __stub_pthread_tryjoin_np 1
#define __stub_pthread_yield 1
#define __stub_ptsname 1
#define __stub_ptsname_r 1
#define __stub_putenv 1
#define __stub_putgrent 1
#define __stub_putmsg 1
#define __stub_putpmsg 1
#define __stub_putpwent 1
#define __stub_putspent 1
#define __stub_pututline 1
#define __stub_pututxline 1
#define __stub_pwritev 1
#define __stub_pwritev64 1
#define __stub_random_r 1
#define __stub_rcmd 1
#define __stub_rcmd_af 1
#define __stub_re_match_2 1
#define __stub_re_set_registers 1
#define __stub_readdir64_r 1
#define __stub_readdir_r 1
#define __stub_readv 1
#define __stub_regcomp 1
#define __stub_regerror 1
#define __stub_regexec 1
#define __stub_remainder 1
#define __stub_remquo 1
#define __stub_revoke 1
#define __stub_rexec 1
#define __stub_rexec_af 1
#define __stub_rint 1
#define __stub_rpmatch 1
#define __stub_rresvport 1
#define __stub_rresvport_af 1
#define __stub_ruserok 1
#define __stub_ruserok_af 1
#define __stub_scalb 1
#define __stub_scalbln 1
#define __stub_scalbn 1
#define __stub_scandir 1
#define __stub_scandirat 1
#define __stub_sched_getcpu 1
#define __stub_secure_getenv 1
#define __stub_seed48 1
#define __stub_seed48_r 1
#define __stub_sem_close 1
#define __stub_sem_destroy 1
#define __stub_sem_getvalue 1
#define __stub_sem_init 1
#define __stub_sem_open 1
#define __stub_sem_post 1
#define __stub_sem_timedwait 1
#define __stub_sem_timedwait64 1
#define __stub_sem_trywait 1
#define __stub_sem_unlink 1
#define __stub_sem_wait 1
#define __stub_semctl 1
#define __stub_semget 1
#define __stub_semop 1
#define __stub_semtimedop 1
#define __stub_setaliasent 1
#define __stub_setcontext 1
#define __stub_setenv 1
#define __stub_setgrent 1
#define __stub_setgroups 1
#define __stub_sethostent 1
#define __stub_sethostid 1
#define __stub_setipv4sourcefilter 1
#define __stub_setkey 1
#define __stub_setkey_r 1
#define __stub_setlocale 1
#define __stub_setlogin 1
#define __stub_setlogmask 1
#define __stub_setmntent 1
#define __stub_setnetent 1
#define __stub_setnetgrent 1
#define __stub_setprotoent 1
#define __stub_setpwent 1
#define __stub_setrlimit64 1
#define __stub_setrpcent 1
#define __stub_setservent 1
#define __stub_setsourcefilter 1
#define __stub_setspent 1
#define __stub_setstate 1
#define __stub_setstate_r 1
#define __stub_setttyent 1
#define __stub_setusershell 1
#define __stub_setutent 1
#define __stub_setutxent 1
#define __stub_sgetspent 1
#define __stub_sgetspent_r 1
#define __stub_shm_open 1
#define __stub_shm_unlink 1
#define __stub_shmat 1
#define __stub_shmctl 1
#define __stub_shmdt 1
#define __stub_shmget 1
#define __stub_significand 1
#define __stub_sigreturn 1
#define __stub_sin 1
#define __stub_sincos 1
#define __stub_sinh 1
#define __stub_spawnl 1
#define __stub_spawnle 1
#define __stub_spawnlp 1
#define __stub_spawnlpe 1
#define __stub_spawnv 1
#define __stub_spawnve 1
#define __stub_spawnvp 1
#define __stub_spawnvpe 1
#define __stub_sqrt 1
#define __stub_srand48 1
#define __stub_srand48_r 1
#define __stub_srandom_r 1
#define __stub_stty 1
#define __stub_swapcontext 1
#define __stub_system 1
#define __stub_tan 1
#define __stub_tanh 1
#define __stub_tempnam 1
#define __stub_tgamma 1
#define __stub_timespec_get 1
#define __stub_tmpfile 1
#define __stub_tmpnam 1
#define __stub_tmpnam_r 1
#define __stub_ttyslot 1
#define __stub_tzset 1
#define __stub_ualarm 1
#define __stub_ulckpwdf 1
#define __stub_ungetwc 1
#define __stub_ungetwc_unlocked 1
#define __stub_unlockpt 1
#define __stub_unsetenv 1
#define __stub_updwtmp 1
#define __stub_updwtmpx 1
#define __stub_uselocale 1
#define __stub_utmpname 1
#define __stub_utmpxname 1
#define __stub_vfwscanf 1
#define __stub_vhangup 1
#define __stub_vwscanf_unlocked 1
#define __stub_wcsnrtombs 1
#define __stub_wcswidth 1
#define __stub_wcwidth 1
#define __stub_wfreadlinkat 1
#define __stub_wgetlogin 1
#define __stub_wgetlogin_r 1
#define __stub_writev 1
#define __stub_wscanf_unlocked 1
#define __stub_wttyname 1
#define __stub_wttyname_r 1
#define __stub_y0 1
#define __stub_y1 1
#define __stub_yn 1
