name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Restore binutils (i386)
      id: cache-binutils-i386-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          binutils
        key: ${{ runner.os }}-binutils-i386

    - name: Install gcc build dependencies
      if: steps.cache-binutils-i386-restore.outputs.cache-hit != 'true'
      run: sudo apt-get install libmpc-dev

    - name: Build toolchain (i386)
      run: EXTRA_DEEMON_CONFIGURE_ARGS=--without-libffi bash kos/misc/make_toolchain.sh i386-kos

    - name: Save binutils (i386)
      if: steps.cache-binutils-i386-restore.outputs.cache-hit != 'true'
      id: cache-binutils-i386-save
      uses: actions/cache/save@v3
      with:
        path: |
          binutils
        key: ${{ runner.os }}-binutils-i386

    - name: Touch magicgenerator .latest (skip system header re-build)
      run: bash -c "> kos/misc/magicgenerator/.generate_headers.dee.latest && > kos/misc/magicgenerator/.generate_syscalls.dee.arm.latest && > kos/misc/magicgenerator/.generate_syscalls.dee.i386.latest && > kos/misc/magicgenerator/.generate_syscalls.dee.x86_64.latest && > kos/misc/magicgenerator/.generate_syscalls.dee.latest"

    - name: build (i386)
      run: ./binutils/deemon/deemon magic.dee --build-only --target=i386 --config=OD
